- demo/index.html
> chore: add site meta description tags

- packages/avatars/package.json
- packages/buttons/package.json
- packages/checkboxes/package.json
- packages/chrome/package.json
- packages/grid/package.json
- packages/menus/package.json
- packages/modals/package.json
- packages/notifications/package.json
- packages/pagination/package.json
- packages/radios/package.json
- packages/ranges/package.json
- packages/select/package.json
- packages/selection/package.json
- packages/tabs/package.json
- packages/tags/package.json
- packages/testing/package.json
- packages/textfields/package.json
- packages/toggles/package.json
- packages/tooltips/package.json
This adds the new major version of the theming package to all packages.
component
> fix(dependencies): update react-theming peerDependency for all packages

- packages/notifications/src/Well.example.md
Fix typo in Notifications documentation
Thanks @vedranio for bringing this to our attention
component
> fix(notifications): update typo in documentation

- .travis.yml
- README.md
- package.json
- yarn.lock
Configuration along with setup for Coveralls.
https://coveralls.io/github/zendeskgarden/react-components
> chore: configure code coverage report

- packages/buttons/src/index.js
Add `ChevronButton` to package exports.
closes #84 
component
> feat(buttons): add `ChevronButton` export

- packages/autocomplete/src/containers/AutocompleteContainer.spec.js
- packages/buttons/src/containers/ButtonGroupContainer.spec.js
- packages/buttons/src/elements/ButtonGroup.spec.js
- packages/buttons/src/views/Anchor.example.md
- packages/checkboxes/src/elements/Checkbox.spec.js
- packages/menus/src/containers/MenuContainer.spec.js
- packages/menus/src/elements/Menu.spec.js
- packages/menus/src/views/MenuView.spec.js
- packages/menus/src/views/__snapshots__/MenuView.spec.js.snap
- packages/modals/src/containers/FocusJailContainer.spec.js
- packages/modals/src/containers/ModalContainer.spec.js
- packages/modals/src/elements/Modal.spec.js
- packages/pagination/src/containers/PaginationContainer.spec.js
- packages/pagination/src/elements/Pagination.spec.js
- packages/radios/src/elements/Radio.spec.js
- packages/ranges/src/elements/RangeField.example.md
- packages/ranges/src/elements/RangeField.spec.js
- packages/select/src/containers/SelectContainer.spec.js
- packages/select/src/elements/Select.spec.js
- packages/select/src/elements/SelectField.spec.js
- packages/selection/src/containers/FieldContainer.spec.js
- packages/tabs/src/containers/TabsContainer.spec.js
- packages/tabs/src/elements/Tabs.spec.js
- packages/testing/src/utils/mountWithTheme.js
- packages/textfields/src/elements/FauxInput.spec.js
- packages/textfields/src/elements/TextField.spec.js
- packages/theming/README.md
- packages/toggles/src/elements/Toggle.spec.js
- packages/tooltips/src/elements/Tooltip.spec.js
This Pr includes a fix to the notifications documentation to include a valid theming example.
Additionally, I took the time to include a fix to `mountWithTheme` in our `react-testing` package which will now remove the need for the assorted `console.warn` mocks we have sprinkled throughout the codebase.
Closes #67 
component
>  fix(notifications): update notifications documentation

- packages/buttons/src/views/Anchor.example.md
- packages/ranges/src/elements/RangeField.example.md
Prevent markdown (linting) prettier (formatting) errors.
Introduced by #83.
> fix(buttons|ranges): prettier formatting errors

- lerna.json
- package.json
- packages/modals/README.md
- packages/modals/src/containers/ModalContainer.example.md
- packages/modals/src/elements/Modal.example.md
- packages/modals/src/views/ModalView.example.md
- utils/travis/publish-packages.js
To reflect modal design guidance.
Includes lerna fixes needed to tag/publish package patch.
component
> fix(modal): update example cancel buttons to use `basic` styling

- demo/index.html
Use simplified site `index.css` with mobile responsive fixes.
>  chore: update demo page CSS

- .github/ISSUE_TEMPLATE.md
> chore(docs): add ISSUE_TEMPLATE prompt for an online code example

- packages/select/src/elements/Select.example.md
- packages/select/src/elements/SelectField.example.md
Closes #180 
Updates Select examples to have realistic select values.
component
> chore(docs): update Select examples to have realistic selected values

- packages/buttons/package.json
- packages/modals/package.json
These are styling-only component updates needed to support improved footer layout when buttons contain extra long text.
See https://github.com/zendeskgarden/css-components/pull/129 for more info.
component
> fix(buttons|modals): bump CSS dependencies

- packages/modals/package.json
Update to `@zendeskgarden/css-modals@6.3.4`
component
> fix(modals): update styling for sticky header/footer elements

- packages/testing/styleguide.config.js
> fix: update react-testing documentation paths

- .github/ISSUE_TEMPLATE.md
@Anifacted mentioned that it would be a good idea to add a `version` prompt to our issue template.  This PR adds that question to the "Fine Print" section.
I've also modified the heading levels to pass Markdownlint.
> chore: add version prompt to ISSUE_TEMPLATE

- .github/PULL_REQUEST_TEMPLATE.md
Adds new item to the list below.
component~
> chore: add a11y item to PR Template checklist

- CHANGELOG.md
- utils/scripts/version.sh
The `version.sh` flow needs a tweak to allow changelog updates to be pushed to master correctly.
> fix(publish): all version flow to push changelog correctly

- packages/pagination/package.json
Looks like I forgot to update the peerDependencies for `react-pagination`
> fix(pagination): update peerDependencies to match other packages

- .eslintrc.json
This change to our eslint config ensures that we don't begin using any of the unsafe lifecycle events
component
> chore(lint): ensure that no unsafe lifecycle events are used

- packages/datepickers/examples/range.md
Prettier fix to allow deploy to pass.
component
> fix(build): correct prettier error to release

- packages/theming/README.md
Fixes https://github.com/zendeskgarden/react-components/issues/419
> docs: correct react-theming peer dependencies

- CHANGELOG.md
- examples/codesandbox/garden-create-react-app/yarn.lock
- lerna.json
- packages/buttons/package.json
- packages/datepickers/package.json
- packages/datepickers/src/elements/Datepicker/Datepicker.tsx
- packages/datepickers/src/styled/StyledMenu.spec.tsx
- packages/datepickers/src/styled/StyledMenu.tsx
- packages/dropdowns/examples/menu.md
- packages/dropdowns/package.json
- packages/dropdowns/src/Autocomplete/Autocomplete.tsx
- packages/dropdowns/src/Menu/Menu.tsx
- packages/dropdowns/src/Multiselect/Multiselect.tsx
- packages/dropdowns/src/Select/Select.tsx
- yarn.lock
This merges the latest `master` branch into our `next` branch.
component~
> Merge master into next

- packages/tables/src/examples/overflow-menu.md
Remove invalid prop from table docs.
component~
> chore(docs): remove invalid prop from table docs

- packages/datepickers/package.json
- packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
- packages/datepickers/src/elements/Datepicker/Datepicker.tsx
- packages/datepickers/src/elements/Datepicker/utils/datepicker-reducer.ts
This PR cherry-picks #517 onto the `next` branch.
> fix(datepickers): allow controlled value to update internal state (#517)

- packages/tables/src/examples/overflow-menu.md
This PR is a cherry-pick of #518 onto the `next` branch.
> chore(docs): remove invalid prop from table docs (#518)

- package.json
- yarn.lock
It looks like the `master` build is failing intermittently. Updating the `yarn.lock` file to try and dedupe some dependencies.
> fix(build): fix datepickers build step

- BREAKING_CHANGES.md
This file should be alphabetical, by package, to assist when release notes are produced for v8.
> chore: keep breaking changes in alphabetical order

- packages/forms/examples/basic.md
Fixes the overlapping seen here: https://vigorous-davinci-819228.netlify.com/forms/#basic
component~
> fix(forms): basic demo layout

- packages/forms/package.json
- packages/forms/src/styled/radio/StyledRadioInput.ts
- packages/forms/src/styled/range/StyledRangeInput.ts
- packages/forms/src/styled/range/StyledSliderThumb.ts
- packages/forms/src/styled/toggle/StyledToggleInput.ts
A collection of changes to alter radio, checkbox, toggle, and range state styling for improved system alignment.
Demo pre-published for review: https://competent-shirley-cc2f82.netlify.com/forms/
component~
> feat(forms): theming color design updates

- .travis.yml
- lerna.json
This PR enables non-latest lerna publishes for the `v7` support branch.
> chore(build): allow lerna publish

- packages/modals/.size-snapshot.json
- packages/modals/src/elements/Modal.tsx
> feat(modal): update Modal prop type for appendToNode to any

- .circleci/config.yml
- .nvmrc
The `deploy` job is currently failing.
https://app.circleci.com/pipelines/github/zendeskgarden/react-components/18/workflows/2f0cbd4b-d662-44eb-a6c3-6ec178984a54
> chore: fix CircleCI config

- .circleci/config.yml
- utils/scripts/gh-pages.js
- Update commit user
- Skip CI on gh-pages branch
- Persist coverage for deploy
> chore: update gh-pages deploy

- README.md
> fix: correct build status badge links

- packages/loaders/src/elements/Dots.tsx
- packages/loaders/src/elements/Inline.tsx
- packages/loaders/src/elements/Progress.tsx
- packages/loaders/src/elements/Skeleton.tsx
- packages/loaders/src/elements/Spinner.tsx
The remaining Loader API descriptions for Skeleton, Progress, Inline, and Spinner. 
> chore(loaders): update remaining Loaders API descriptions

- packages/tabs/src/elements/Tab.tsx
- packages/tabs/src/elements/TabList.tsx
- packages/tabs/src/elements/TabPanel.tsx
- packages/tabs/src/elements/Tabs.tsx
The new Tabs API descriptions. 
> chore(tabs): update Tabs API descriptions

- .circleci/config.yml
- package.json
- utils/scripts/deploy.js
- utils/scripts/tag.js
- yarn.lock
- Allow non-maintainer deploys via `writer` context.
- Handle `deploy` scripting errors with an error exit code.
- Get default `tag` "master" branch name from lerna config.
- Fix `changelog` release handling.
> chore: deploy script improvements

- package.json
- utils/scripts/tag.js
- yarn.lock
Ensures that the tag stamped by `lerna version` is, indeed, the desired commit tag.
https://github.com/lerna/lerna/pull/2594 landed in v3.22.0
> chore(utils): force version tag

- CHANGELOG.md
- lerna.json
- packages/accordions/package.json
- packages/avatars/package.json
- packages/breadcrumbs/.size-snapshot.json
- packages/breadcrumbs/package.json
- packages/buttons/package.json
- packages/chrome/package.json
- packages/datepickers/package.json
- packages/dropdowns/package.json
- packages/forms/package.json
- packages/grid/package.json
- packages/loaders/.size-snapshot.json
- packages/loaders/package.json
- packages/modals/package.json
- packages/notifications/package.json
- packages/pagination/package.json
- packages/tables/package.json
- packages/tabs/package.json
- packages/tags/package.json
- packages/theming/package.json
- packages/tooltips/package.json
- packages/typography/package.json
- packages/utilities/package.json
Reverts the failed release for `v8.15.1`
> chore: revert v8.15.1 release

- examples/codesandbox/package.json
This PR updates the example `package.json` to include the `react-accordions` package. It also updates the `react-scripts` dependency to use the caret range.
> chore(examples): update codesandbox package.json

- packages/dropdowns/src/Dropdown/Dropdown.spec.tsx
- packages/dropdowns/src/Menu/Items/NextItem.tsx
> fix(dropdowns): allow NextItem to receive an object value

- packages/dropdowns/package.json
Update `downshift` to it's latest version to include several IME and localization bug-fixes.
> fix(dropdowns): update downshift dependency

- packages/datepickers/src/Datepicker/components/Calendar.tsx
> fix(datepickers): use gregorian labels for days

- packages/buttons/yarn.lock
- packages/dropdowns/yarn.lock
- packages/pagination/yarn.lock
- packages/tabs/yarn.lock
This pull request updates the selection based container dependencies. The newest versions of these include a fix for `useSelection`. 
The fix can be verified by navigating to the `ButtonGroup` or `Tabs` components in Storybook and ensuring there is no React warning logged in the console.
This PR closes #891.
> chore: update selection based containers

- packages/breadcrumbs/src/elements/Breadcrumb.tsx
Standardize prop descriptions and add @extends clauses.
> chore(breadcrumbs): update prop descriptions

- packages/avatars/src/elements/Avatar.tsx
Standardize prop descriptions and add @extends clauses.
> chore(avatars): update prop descriptions

- packages/accordions/src/elements/accordion/Accordion.tsx
- packages/accordions/src/elements/stepper/Stepper.tsx
Updates prop descriptions for accordion and stepper components
> chore(accordions): update prop descriptions

- packages/buttons/src/elements/Anchor.tsx
- packages/buttons/src/elements/Button.tsx
- packages/buttons/src/elements/ButtonGroup.tsx
- packages/buttons/src/elements/IconButton.tsx
- packages/buttons/src/elements/ToggleButton.tsx
- packages/buttons/src/elements/ToggleIconButton.tsx
Updates props for button components
> chore(buttons): update prop descriptions

- packages/datepickers/src/elements/Datepicker/Datepicker.tsx
- packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
Updates datepickers package prop descriptions
> chore(datepickers): update prop descriptions

- packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
- packages/dropdowns/src/elements/Fields/Label.tsx
- packages/dropdowns/src/elements/Fields/Message.tsx
- packages/dropdowns/src/elements/Menu/Items/Item.tsx
- packages/dropdowns/src/elements/Menu/Menu.tsx
- packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
- packages/dropdowns/src/elements/Select/Select.tsx
- packages/dropdowns/src/elements/Trigger/Trigger.tsx
Updates dropdowns package props
Could definitely use an extra eye on `Dropdown` function props. I'm not entirely sure how to describe some of these params
> chore(dropdowns): update prop descriptions

- packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
- packages/forms/src/elements/Checkbox.tsx
- packages/forms/src/elements/FauxInput.tsx
- packages/forms/src/elements/FileUpload.tsx
- packages/forms/src/elements/Input.tsx
- packages/forms/src/elements/MediaInput.tsx
- packages/forms/src/elements/MultiThumbRange.tsx
- packages/forms/src/elements/Select.tsx
- packages/forms/src/elements/Textarea.tsx
- packages/forms/src/elements/common/Field.tsx
- packages/forms/src/elements/common/Label.tsx
- packages/forms/src/elements/common/Message.tsx
- packages/forms/src/elements/input-group/InputGroup.tsx
- packages/forms/src/elements/tiles/Tiles.tsx
- packages/forms/src/elements/tiles/components/Tile.tsx
Updates prop descriptions for forms components
> chore(forms): update prop descriptions

- packages/grid/src/elements/Col.tsx
- packages/grid/src/elements/Grid.tsx
- packages/grid/src/elements/Row.tsx
Updates grid package prop docs
> chore(grid): update prop descriptions

- packages/loaders/src/elements/Dots.tsx
- packages/loaders/src/elements/Inline.tsx
- packages/loaders/src/elements/Progress.tsx
- packages/loaders/src/elements/Skeleton.tsx
- packages/loaders/src/elements/Spinner.tsx
Updates loaders package prop descriptions
> chore(loaders): update prop descriptions

- packages/modals/src/elements/DrawerModal/DrawerModal.tsx
- packages/modals/src/elements/Modal.tsx
- packages/modals/src/elements/TooltipModal/TooltipModal.tsx
- packages/modals/src/styled/StyledHeader.ts
Updates modals package prop descriptions
> chore(modals): update prop descriptions

- packages/notifications/src/elements/Alert.tsx
- packages/notifications/src/elements/Well.tsx
- packages/notifications/src/elements/content/Title.tsx
- packages/notifications/src/styled/StyledNotification.ts
- packages/pagination/src/elements/Pagination/Pagination.tsx
Updates notifications and pagination packages prop descriptions
> chore(notifications, pagination): update prop descriptions

- packages/tables/src/elements/SortableCell.tsx
- packages/tables/src/styled/StyledCell.ts
- packages/tables/src/styled/StyledOverflowButton.ts
- packages/tables/src/styled/StyledRow.ts
- packages/tables/src/styled/StyledSortableButton.ts
- packages/tables/src/styled/StyledTable.ts
Updates tables package prop descriptions
> chore(tables): update prop descriptions

- packages/tabs/src/elements/Tab.tsx
- packages/tabs/src/elements/TabPanel.tsx
- packages/tabs/src/elements/Tabs.tsx
Updates tabs package prop descriptions
> chore(tabs): update prop descriptions 

- packages/tags/src/elements/Tag.tsx
Updates tags package prop descriptions
> chore(tags): update prop descriptions

- packages/tooltips/src/elements/Tooltip.tsx
Updates tooltips package prop descriptions
> chore(tooltips): update prop descriptions

- packages/typography/src/elements/Blockquote.tsx
- packages/typography/src/elements/Code.tsx
- packages/typography/src/elements/CodeBlock.tsx
- packages/typography/src/elements/Ellipsis.tsx
- packages/typography/src/elements/LG.tsx
- packages/typography/src/elements/MD.tsx
- packages/typography/src/elements/Paragraph.tsx
- packages/typography/src/elements/SM.tsx
- packages/typography/src/elements/Span.tsx
- packages/typography/src/elements/XL.tsx
- packages/typography/src/elements/XXL.tsx
- packages/typography/src/elements/XXXL.tsx
- packages/typography/src/elements/lists/OrderedList.tsx
- packages/typography/src/elements/lists/UnorderedList.tsx
Updates typography package prop descriptions
> chore(typography): update prop descriptions

- docs/migration.md
Add Modal's Header prop change to V8 migration
> docs: Add Modal's Header prop change to V8 migration

- .circleci/config.yml
- .storybook/preview.js
- package.json
- yarn.lock
Adds [Bojagi](https://bojagi.io/), a visual component comparison tool for PR review
https://bojagi.io/app/github/zendeskgarden/react-components/pull/1163
> chore: add bojagi

- .github/renovate.json
Update renovate config per [latest documentation](https://docs.renovatebot.com/configuration-options/#matchpaths).
> chore(renovate): update to resolve config warnings

- package.json
- tsconfig.json
- utils/scripts/deploy.js
- yarn.lock
Verify available Netlify bandwidth prior to staging deploy.
> chore(scripts): enhance deploy with added bandwidth checking

- packages/accordions/.size-snapshot.json
- packages/accordions/src/elements/accordion/Accordion.tsx
- packages/accordions/src/elements/stepper/Stepper.tsx
- packages/accordions/src/elements/stepper/components/Label.tsx
- packages/accordions/src/elements/timeline/Timeline.tsx
- packages/accordions/src/elements/timeline/components/Item.tsx
- packages/accordions/src/index.ts
- packages/accordions/src/styled/accordion/StyledButton.ts
- packages/accordions/src/styled/accordion/StyledHeader.ts
- packages/accordions/src/styled/accordion/StyledInnerPanel.ts
- packages/accordions/src/styled/accordion/StyledPanel.ts
- packages/accordions/src/styled/accordion/StyledRotateIcon.ts
- packages/accordions/src/styled/stepper/StyledInnerContent.ts
- packages/accordions/src/styled/stepper/StyledStep.ts
- packages/accordions/src/styled/stepper/StyledStepper.ts
- packages/accordions/src/types/index.ts
Move public interfaces to standardized `./types` location.
> chore(accordions): standardize interfaces

- packages/avatars/.size-snapshot.json
- packages/avatars/src/elements/Avatar.tsx
- packages/avatars/src/index.ts
- packages/avatars/src/styled/StyledAvatar.ts
- packages/avatars/src/types/index.ts
Standardize types & interfaces for improved reuse across avatar components.
> chore(avatars): refactor types and interfaces

- packages/datepickers/.size-snapshot.json
- packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
- packages/datepickers/src/elements/Datepicker/Datepicker.tsx
- packages/datepickers/src/elements/Datepicker/utils/datepicker-reducer.ts
- packages/datepickers/src/elements/Datepicker/utils/garden-placements.spec.ts
- packages/datepickers/src/elements/Datepicker/utils/garden-placements.ts
- packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
- packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
- packages/datepickers/src/elements/DatepickerRange/components/End.spec.tsx
- packages/datepickers/src/elements/DatepickerRange/components/Start.spec.tsx
- packages/datepickers/src/elements/DatepickerRange/utils/datepicker-range-reducer.ts
- packages/datepickers/src/index.ts
- packages/datepickers/src/styled/StyledMenuWrapper.ts
- packages/datepickers/src/types/index.ts
Standardize interface and type definitions to fix doc-generated API readability.
> fix(datepickers): refactor types and interfaces

- packages/loaders/.size-snapshot.json
- packages/loaders/src/elements/Dots.tsx
- packages/loaders/src/elements/Inline.tsx
- packages/loaders/src/elements/Progress.tsx
- packages/loaders/src/elements/Skeleton.tsx
- packages/loaders/src/elements/Spinner.tsx
- packages/loaders/src/index.ts
- packages/loaders/src/styled/StyledInline.ts
- packages/loaders/src/styled/StyledLoadingPlaceholder.ts
- packages/loaders/src/styled/StyledProgress.ts
- packages/loaders/src/styled/index.ts
- packages/loaders/src/types/index.ts
- packages/pagination/src/elements/Pagination/Pagination.spec.tsx
- packages/pagination/src/elements/Pagination/Pagination.tsx
- packages/pagination/src/index.ts
- packages/pagination/src/types/index.ts
- packages/tabs/src/elements/Tab.tsx
- packages/tabs/src/elements/TabPanel.tsx
- packages/tabs/src/elements/Tabs.tsx
- packages/tabs/src/index.ts
- packages/tabs/src/types/index.ts
- packages/tags/.size-snapshot.json
- packages/tags/src/elements/Tag.tsx
- packages/tags/src/index.ts
- packages/tags/src/styled/StyledTag.ts
- packages/tags/src/types/index.ts
Standardize interface and type definitions to address doc-generated API readability.
> fix(loaders, pagination, tabs, tags): refactor types and interfaces

- packages/typography/.size-snapshot.json
- packages/typography/src/elements/Blockquote.tsx
- packages/typography/src/elements/Code.tsx
- packages/typography/src/elements/CodeBlock.tsx
- packages/typography/src/elements/Ellipsis.tsx
- packages/typography/src/elements/LG.tsx
- packages/typography/src/elements/MD.tsx
- packages/typography/src/elements/Paragraph.tsx
- packages/typography/src/elements/SM.tsx
- packages/typography/src/elements/XL.tsx
- packages/typography/src/elements/XXL.tsx
- packages/typography/src/elements/XXXL.tsx
- packages/typography/src/elements/lists/OrderedList.tsx
- packages/typography/src/elements/lists/UnorderedList.tsx
- packages/typography/src/elements/span/Span.tsx
- packages/typography/src/index.ts
- packages/typography/src/styled/StyledBlockquote.ts
- packages/typography/src/styled/StyledCode.spec.tsx
- packages/typography/src/styled/StyledCode.ts
- packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
- packages/typography/src/styled/StyledCodeBlockLine.ts
- packages/typography/src/styled/StyledEllipsis.ts
- packages/typography/src/styled/StyledFont.spec.tsx
- packages/typography/src/styled/StyledFont.tsx
- packages/typography/src/styled/StyledList.ts
- packages/typography/src/styled/StyledListItem.ts
- packages/typography/src/styled/StyledParagraph.ts
- packages/typography/src/types/index.ts
- packages/typography/src/utils/useOrderedListContext.ts
- packages/typography/src/utils/useUnorderedListContext.ts
Standardize interface and type definitions to fix doc-generated API readability.
> chore(typography): refactor types and interfaces

- packages/accordions/.size-snapshot.json
- packages/accordions/src/elements/timeline/components/Item.tsx
Fix incorrect path on import which causes `Cannot find module` TS error for consumers.
> fix(accordions): relative type interface import

- .circleci/config.yml
Parity with https://github.com/zendeskgarden/react-containers/pull/534
> chore: add version for clearing corrupted CI cache

- packages/dropdowns/demo/autocomplete.stories.mdx
- packages/dropdowns/demo/combobox.stories.mdx
- packages/dropdowns/demo/multiselect.stories.mdx
- packages/dropdowns/demo/select.stories.mdx
- packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
- packages/dropdowns/src/elements/Combobox/Combobox.tsx
- packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
- packages/dropdowns/src/elements/Select/Select.tsx
Add programmatic and demo pointers to the new `Combobox` component.
> chore(dropdowns): tag and document deprecated components

- package.json
- yarn.lock
Contains a crucial fix for `yarn run tag`.
> chore: upgrade @zendeskgarden/scripts

- packages/dropdowns.next/package.json
- packages/dropdowns.next/yarn.lock
This PR upgrades the combobox container with `onChange` override logic that corrects the underlying Downshift IME entry bug.
https://github.com/zendeskgarden/react-containers/pull/588
> fix(combobox): handle IME via controlled input

- package-lock.json
- packages/dropdowns.next/package.json
Upgrades to `container-combobox` v1.1.3, which provides a bug fix for the cursor jumping to the end of the input value while editing a _controlled_ `Combobox`.
https://github.com/zendeskgarden/react-containers/pull/625
> fix(combobox): prevent controlled input cursor jump

- package-lock.json
- packages/datepickers/src/elements/DatePicker/DatePicker.tsx
- packages/dropdowns/src/elements/menu/MenuList.tsx
- packages/modals/src/elements/TooltipModal/TooltipModal.tsx
- packages/tooltips/src/elements/Tooltip.tsx
Components affected:
- DatePicker
- Menu
- TooltipModal
- Tooltip
> fix: adds rtl fix for floating ui implementations

- docs/changelogs/v8.md
- package-lock.json
- packages/dropdowns/package.json
Cherry picks commits from `main` from 8.74.2 to 8.74.3.
> chore(next): updates from `main`

- packages/avatars/demo/~patterns/stories/MenuStory.tsx
- packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
- packages/chrome/demo/stories/SheetStory.tsx
- packages/chrome/demo/stories/SubNavCollapsibleItem.tsx
- packages/colorpickers/demo/stories/ColorPickerDialogStory.tsx
- packages/colorpickers/demo/stories/ColorSwatchDialogStory.tsx
- packages/datepickers/demo/stories/DatePickerRangeStory.tsx
- packages/datepickers/demo/stories/DatePickerStory.tsx
- packages/dropdowns.legacy/demo/stories/DropdownStory.tsx
- packages/dropdowns.legacy/demo/~patterns/stories/MenuStory.tsx
- packages/dropdowns/demo/stories/ComboboxStory.tsx
- packages/dropdowns/demo/stories/MenuStory.tsx
- packages/dropdowns/demo/~patterns/stories/MenuButtonStory.tsx
- packages/dropdowns/demo/~patterns/stories/MenuNestedStory.tsx
- packages/forms/demo/stories/TilesStory.tsx
- packages/modals/demo/stories/TooltipModalStory.tsx
- packages/notifications/demo/stories/ToastStory.tsx
- packages/theming/demo/stories/MenuStylesStory.tsx
- packages/tooltips/demo/stories/TooltipStory.tsx
- packages/typography/demo/stories/data.ts
> chore: updates Grid.Row and Grid.Col references in stories

- package-lock.json
- packages/.template/package.json
- packages/accordions/package.json
- packages/buttons/package.json
- packages/chrome/package.json
- packages/colorpickers/package.json
- packages/drag-drop/package.json
- packages/dropdowns.legacy/package.json
- packages/dropdowns/package.json
- packages/forms/package.json
- packages/grid/package.json
- packages/modals/package.json
- packages/notifications/package.json
- packages/pagination/package.json
- packages/tables/package.json
- packages/tabs/package.json
- packages/tags/package.json
- packages/typography/package.json
> fix: update theming peer dependencies to ^9.0.0

- packages/dropdowns.next/src/elements/menu/Item.tsx
Smol refactor that has been bugging me for months.
> chore(menu): removes duplicate use of menu context in items

- package-lock.json
Sync latest `main` with `next`
> chore: sync  latest `main` with `next`

- package-lock.json
- package.json
- utils/scripts/deploy.mjs
Pulls the correct commit SHA from updated [GithubCommit](https://github.com/zendeskgarden/scripts/pull/228) script to fix missing deploy status.
> ci: fix missing staging deploy status by associating deploy ref to correct SHA

- package-lock.json
- package.json
- utils/scripts/deploy.mjs
The deploy statuses are back to make design reviews easier. 🎉
> chore: sync `next` with `main`

- packages/chrome/src/elements/nav/NavList.tsx
> fix(chrome): update Nav.List displayName

- .github/renovate.json
- README.md
...to accommodate upstream (`tailwindcss` etc) dependencies
> chore: adjust renovate schedule

- packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
- packages/dropdowns.next/src/elements/combobox/Listbox.tsx
Same as #1987 but for Garden v8.
> fix(Combobox): improve screen reader experience for Select-Only combobox w NVDA 

- package-lock.json
- packages/dropdowns/package.json
Update package with combobox cache fixes.
See https://github.com/zendeskgarden/react-containers/pull/698 for details
> fix(dropdowns): update `useCombobox` container with improved cache coordination
