zendeskgarden/react-components

packages/menus/src/containers/MenuContainer.js
packages/select/src/elements/Select.js

This PR adds the ability to modify the zIndex of a `Select`. This also now defaults to a zIndex that can beat our Modals and the code examples in styleguidist.
Before:
After:
component

feat(select): add zIndex option to Select component

---

packages/tags/package.json

Changes `build:styleguide` to `build:demo`.
The tags package was 404'ing on our website, it was missing the right script for lerna to build the demo page correctly.
This has already been prepublish to fix it: https://garden.zendesk.com/react-components/tags/
component

fix(tags): Add correct build:demo script

---

packages/ranges/package.json

This PR upgrades the `@zendeskgarden/react-ranges` package to the WCAG 2.0 AA compliant color palette.
This is a **BREAKING CHANGE** due to the large visual change.
component

feat(ranges): add WCAG 2.0 AA compliant color palette

---

utils/styleguide/setup.js

When I added in the mobile-responsive Grid to all code examples I also adding in a `margin-bottom` for all columns. This is causing some clipping on the top of some of our focus states.
To fix this I split the distance between `margin-bottom` and `margin-top`.
Before:
After:
component

fix(docs): balance code example margins to avoid clipping

---

packages/tabs/README.md
packages/tabs/src/containers/TabsContainer.js
packages/tabs/src/containers/TabsContainer.spec.js
packages/tabs/src/elements/Tabs.example.md
packages/tabs/src/elements/Tabs.js

`react-tabs` was one of the first packages created during the migration to the new architecture. Because of this, it's missing the `onChange` event that most of the newer components have (Menu, Select, Pagination, etc.) . Another issue is that the first example in the README uses an `onChange` event that doesn't exist yet 😢 
This PR introduces an `onChange` event for consumers that only want to control the currently selected Tab (which is most people).
component

feat(tabs): add onChange event for selection

---

package.json
utils/styleguide/TableOfContentsRenderer/index.js
utils/travis/publish-gh-pages.sh

Currently the travis builds on `master` are running between 12-18 minutes per run. That isn't the best.
The bulk of time is from us building a separate `react-styleguidist` documentation site for every package on each run.  We could drastically decrease the build time by only building the styleguide for packages changed in the most recent commit.
This PR introduces a new `build:demo_changed` yarn command that performs the `build:demo` command with the `--since HEAD^` lerna command to build across all of the updated packages.
This will continue to work as expected due to:
* we are using the gh-pages `add` option to not overwrite old docs
* if there are any interdependencies that change in other documentation areas (i.e. buttons that are used in other package examples) lerna will recognize …

chore(build): update styleguidist to only build recently changed packages

---

packages/grid/package.json

There was some global styling leakage that was fixed in `@zendeskgarden/css-grids`. This PR bumps the dependency to include the fixes.
Pre-published at: http://garden.zendesk.com/react-components/grid
(looks like gh-pages might be down globally, give it some time if it doesn't resolve)
component

fix(grid): update CSS dependency to remove global styling

---

packages/.template/package.json
packages/avatars/package.json
packages/buttons/package.json
packages/checkboxes/package.json
packages/chrome/package.json
packages/grid/package.json
packages/menus/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/radios/package.json
packages/ranges/package.json
packages/select/package.json
packages/selection/package.json
packages/tabs/package.json
packages/tags/package.json
packages/textfields/package.json
packages/theming/README.md
packages/toggles/package.json
packages/tooltips/package.json

When I updated the build to use webpack, lerna didn't update the `peerDependency` of `react-theming` to the new major. This is causing a warning if you install the most recenter version of `@zendeskgarden/react-theming`.
This PR updates the `peerDependency` of react-theming to include ranges within `^1.0.0 || ^2.0.0`
component

fix(dependencies): add new allowed peerDependency for @zendeskgarden/react-theming

---

packages/modals/README.md
packages/modals/package.json
packages/modals/src/containers/ModalContainer.example.md
packages/modals/src/elements/Modal.example.md
packages/modals/src/index.js
packages/modals/src/views/Close.js
packages/modals/src/views/Footer.js
packages/modals/src/views/FooterItem.js
packages/modals/src/views/FooterItem.spec.js
packages/modals/src/views/ModalView.example.md
packages/modals/src/views/__snapshots__/Close.spec.js.snap
packages/modals/src/views/__snapshots__/Footer.spec.js.snap
packages/modals/src/views/__snapshots__/FooterItem.spec.js.snap

Margining no longer applies to all (wildcard) `<Footer>` child elements.
Relies on `.c-dialog__footer__item` css-modals styling for layout.
component

feat(modals): add `<FooterItem>` used to layout modal footer items/buttons

---

demo/index.html

This PR brings over the mobile responsive changes that were included in the root Garden doc page.
Has better spacing now:
component

feat(demo): update root demo page to be mobile responsive

---

packages/menus/package.json
packages/menus/src/containers/MenuContainer.js
packages/menus/src/elements/Menu.js
packages/modals/package.json
packages/select/src/elements/SelectField.example.md
packages/tooltips/package.json
packages/tooltips/src/containers/TooltipContainer.js

After researching #37 I found some assorted issues in relation to React `v15.X` support and the Menu/Select components.
While double checking the dependencies, it looks like `react-portal` dropped their v14 support. Unrelated to the issues experienced above, but I updated our peerDependencies to reflect that in the affected components. All others support `v14` as expected.
Within our positioning library, react-popper, there is an option to not wrap the trigger/popover with a containing element (https://github.com/FezVrasta/react-popper/tree/v0.x#tag-proptypesoneoftypeproptypesstring-proptypesbool).
Since React `v16` supports [Fragments](https://reactjs.org/docs/fragments.html), this was working as expected in the Lotus, Admin Centre, Web Widget, and our local documentation. But, when ran …

fix(menus|select): remove fragment usage to support React v15.X

---

utils/build/webpack.base.js

When using the default configuration of `OptimizeCSSAssetsPlugin` it enables the `reduceIdent` option in cssnano. This option renames our keyframe values and does not scope them with css-modules, which creates classes when multiple packages are used.
This PR updates our css-loader configuration and `OptimizeCSSAssetsPlugin` to now handle the keyframes correctly.
Before:
```
@keyframes a{0%{margin-bottom:-20px}to{margin-bottom:0}}
```
After:
```
@keyframes index__zd-menu--up-open___3qIiH{0%{margin-bottom:-20px}to{margin-bottom:0}}
```
Closes #39 
component

fix(build): scope keyframe names correctly with reduceIdents webpack option

---

packages/testing/src/utils/mountWithTheme.js
packages/testing/src/utils/shallowWithTheme.js
packages/theming/README.md
packages/theming/src/ThemeProvider/ThemeProvider.js

This initial change was made for a team so they could adjust where styled-components injected its CSS, the team is only now starting to use garden.
We've since made the change to make styled-components a peer dependency so it's easy for teams to bring in `StyleSheetManager` themselves.
This PR removes the `target` prop from our `ThemeProvider` component.
This will also fix #24.
component

fix(theming): Remove StyleSheetManager from ThemeProvider

---

packages/buttons/package.json
packages/buttons/src/containers/ButtonGroupContainer.js
packages/buttons/src/containers/ButtonGroupContainer.spec.js

Stop browser double focusing the buttons in side a `<ButtonGroup />` when following the reproduction steps in #43.
~~Not sure on my solution and this hasn't got tests yet but wanted to put it up and see what you think.~~
closes #43 
component

fix: Stop double focus of button group

---

packages/buttons/package.json
packages/buttons/src/elements/SplitButton.example.md
packages/buttons/src/views/Button.js
packages/buttons/src/views/icon-button/ChevronButton.js
packages/buttons/src/views/icon-button/ChevronButton.spec.js
packages/buttons/src/views/icon-button/__snapshots__/ChevronButton.spec.js.snap
packages/buttons/styleguide.config.js
packages/menus/src/views/MenuView.js
packages/menus/src/views/MenuView.spec.js
packages/menus/src/views/__snapshots__/MenuView.spec.js.snap

This PR adds the necessary visual components and examples for a SplittButton component.
Rather than make `react-menus` a dependency of `react-buttons` I have opted to include the necessary visual elements (chevron button) and provided an example usage.
Some reasons for this decision:
- A large majority of consumers are using `react-buttons` without a SplitButton. The menus styling and popper/portal dependencies are not cheap enough to force this bundle size on people that just want a button.
- The API complexity is similar in # of lines as well as complexity between providing all customization needed with a high-abstraction element.
- By not coupling these dependencies it allows these packages to be versioned freely.
Found some interesting issues with forwarding refs in nested …

feat(splitbutton): add ChevronButton view and SplitButton example

---

packages/selection/src/containers/SelectionContainer.js
packages/theming/src/ThemeProvider/ThemeProvider.js
packages/theming/src/index.js
packages/theming/src/utils/getDocument.js
packages/theming/src/utils/getDocument.spec.js

This PR adds a `getDocument` util and an extra prop to `ThemeProvider`. This allows passing down a different `document` context.
component

feat(theming): Add a document prop and getDocument util to help with iframes

---

packages/buttons/src/elements/ButtonGroup.js
packages/checkboxes/src/elements/Checkbox.js
packages/menus/src/elements/Menu.js
packages/modals/src/elements/Modal.js
packages/radios/src/elements/Radio.js
packages/ranges/src/elements/RangeField.js
packages/select/src/elements/Select.js
packages/tabs/src/elements/Tabs.js
packages/textfields/src/elements/TextField.js
packages/toggles/src/elements/Toggle.js

In several of our high-abstraction elements we map over the provided children to apply props and other logic.
For many of these areas we were not using the `isValidElement` React utility to validation that a child is able to receive/interact with these props.
This PR adds that check to all `Children.map()` usages.
Pre-published at: http://garden.zendesk.com/react-components
Packages affected:
* ButtonGroup
* Checkbox
* Menu
* Modal
* Radio
* many others
Closes #50 
component

fix: add isValidElement check for all children mapping within elements

---

packages/notifications/src/content/Close.js
packages/notifications/src/content/__snapshots__/Close.spec.js.snap

Changed `Close` component default type to `button`.
N/A
component

fix(notifications): default Close type to `button`

---

packages/autocomplete/src/containers/AutocompleteContainer.js
packages/menus/src/containers/MenuContainer.js
packages/selection/src/containers/SelectionContainer.js
packages/theming/src/utils/getDocument.js
packages/theming/src/utils/getDocument.spec.js

This guards against `getDocument` being undefined to avoid throwing errors. 
The following scenario where you have <3.0.0 of `react-theming` installed but have a package that utilises `getDocument` added to your project it'll throw on trying to call `undefined` as a function.
component

fix(autocomplete|menus|selection|theming): guard against `getDocument` being undefined

---

packages/chrome/package.json

This PR upgrades the css-chrome dependency to include the [CSS bug](https://github.com/zendeskgarden/css-components/issues/77) that caused weird side-effects in the `Navigation` sidebar in size-constrained situations.
Relates to https://github.com/zendeskgarden/css-components/issues/77
component

fix(chrome): update css-chrome to include navigation minHeight fix

---

packages/.template/package.json
packages/buttons/package.json
packages/buttons/src/elements/SplitButton.example.md
packages/buttons/styleguide.config.js

When I added in the `SplitButton` example in react-buttons, I accidentally added in a circular dependency between buttons and menus.
By using a relative link rather than a devDependency in our example this solves the problem.
Before:
Should go in before #55 
component

fix(buttons): remove cycle dependency between react-button and react-menus

---

packages/tables/src/examples/overflow-menu.md

Since we can't lint markdown files for the JS specific changes, a prettier run wasn't included when I first published the react-tables package.
This PR fixes that markdown example.
component

fix(tables): format table examples

---

packages/menus/package.json
packages/menus/src/containers/MenuContainer.example.md
packages/menus/src/containers/MenuContainer.js
packages/menus/src/elements/Menu.example.md
packages/menus/src/elements/Menu.js
packages/menus/src/views/MenuView.js
packages/menus/src/views/__snapshots__/MenuView.spec.js.snap

This PR adds the `left-top, left-bottom, right-top, and right-bottom` arrow placements to the Menu component.
Similar to #54 
component

feat(menus): add left-top, left-bottom, right-top, and right-bottom arrow placements

---

renovate.json

By default, Renovate respects the schedule provided immediately. For us to run through the full cycle I'm removing the cycle temporarily.
component

chore(deps): drop Renovate schedule temporarily

---

packages/ranges/src/views/SingleThumbView.js
packages/ranges/src/views/__snapshots__/SingleThumbView.spec.js.snap

It looks like something was updated that made the react-ranges package not show it's fill color.
This PR increases the specificity of the `background-size` that we apply to the element.
Closes #64 
component

fix(ranges): increase specificity to show selection fill color

---

packages/radios/src/views/Label.js
packages/radios/src/views/__snapshots__/Label.spec.js.snap

Fix copy/paste.
Rename to `radios.label` to align with https://github.com/zendeskgarden/react-components/blob/%40zendeskgarden/react-toggles%403.2.11/packages/toggles/src/views/Label.js#L14
component

fix(radios): update label component ID to prevent checkbox component collision

---

packages/menus/src/containers/MenuContainer.js
packages/menus/src/containers/MenuContainer.spec.js

If you tried to make dynamic prop changes to `Menu` it would throw due to Popper.js trying to get the computed styles of `null`.
Simple fix here is to just not render the Menu when the menu is closed.
component

fix(menu): Don't render Menu when it's closed

---

packages/chrome/package.json

Bumps the chrome css package to fix an issue with the cursor of an active subnav item.

fix(chrome): update CSS dependency to fix subnav active cursor

---

utils/styleguide/ArgumentsRenderer/index.js
utils/styleguide/LogoRenderer/index.js
utils/styleguide/TableOfContentsRenderer/index.js
utils/styleguide/TableRenderer/index.js
utils/styleguide/github-hljs-theme.css
utils/styleguide/styleguide.base.config.js

This is a small sub-set of the changes originally proposed in #66 
This PR helps increase the accessibility of the internal styleguidist components to pass WCAG 2.0 compliance (originally discussed in #66)
This PR specifically: 
* Creates a custom `ArgumentsRenderer` to use Garden colors
* Adds a top-level role to the `LogoRenderer` component along with screen-reader legible text
* Adds landmark region to `TableofContentsRenderer`
* Creates a custom `TableRenderer` to use our Garden table for prop-types display
* Override hljs theme with `Github + accessible Garden` for accessible code example syntax coloring
component

fix(docs): update styleguidist internal components to pass WCAG 2.0 compliance

---

packages/checkboxes/src/views/Message.js
packages/checkboxes/src/views/Message.spec.js
packages/checkboxes/src/views/__snapshots__/Message.spec.js.snap
packages/radios/src/views/Message.js
packages/radios/src/views/Message.spec.js
packages/radios/src/views/__snapshots__/Message.spec.js.snap
packages/ranges/src/views/Message.js
packages/ranges/src/views/Message.spec.js
packages/ranges/src/views/__snapshots__/Message.spec.js.snap
packages/select/src/views/SelectView.js
packages/select/src/views/fields/Message.js
packages/textfields/src/elements/FauxInput.js
packages/textfields/src/views/Input.js
packages/textfields/src/views/Input.spec.js
packages/textfields/src/views/Message.js
packages/textfields/src/views/Message.spec.js
packages/textfields/src/views/Textarea.js
packages/textfields/src/views/Textarea.spec.js
packages/textfields/src/views/__snapshots__/Input.spec.js.snap
packages/textfields/src/views/__snapshots__/Message.spec.js.snap
packages/textfields/src/views/__snapshots__/Textarea.spec.js.snap
packages/toggles/src/views/Message.js
packages/toggles/src/views/Message.spec.js
packages/toggles/src/views/__snapshots__/Message.spec.js.snap

This adds an extra `none` option the the `validation` prop.
Most uses of the `validation` prop  would be via some dynamic logic around the current validation state of a form field .e.g
```js
const validation = () => !isValid ? 'error' : 'none';
<TextField>
<Label>Username</Label>
<Input required validation={validation} />
{!isValid && <Message validation='error'>Error</Message>}
</TextField>
```
Currently you'd have to spread an object that may contain the validation prop or not based on the `isValid` logic above this change makes it a little easier.

feat(checkboxes|radios|ranges|select|textfields|toggles): Add new `none` option to support dynamic logic with the validation prop

---

packages/menus/src/elements/Menu.example.md
packages/menus/src/elements/Menu.js
packages/menus/src/elements/Menu.spec.js

While converting the `Menu` package I forgot to include a `maxHeight` prop to easily create scrollable Menus.
This should be something that doesn't require us to eject into a render-prop container.
Adds a new `maxHeight` prop
component

feat(menus): add maxHeight prop for scrollable menus

---

packages/textfields/src/elements/FauxInput.example.md

The `FauxInput` documentation currently shows an example with "double focus". This is confusing and the default browser focus should be hidden.
Bad focus:
This PR removes the default outline of the inner div.
Also, lerna is throwing deprecation warnings from the recent v3 upgrade. This fixes the deprecation warning `commands -> command`
Thanks @dlee for bringing this to our attention
component

chore(docs): update FauxInput example to hide focus styling

---

packages/chrome/package.json
packages/chrome/src/views/Chrome.example.md
packages/chrome/src/views/nav/NavItem.js
packages/chrome/src/views/nav/NavItemText.js
packages/chrome/src/views/subnav/SubNavItemText.js

Adds the following element props:
* `<NavItem brandmark />`
* `<NavItemText wrap />`
* `<SubNavItemText wrap />`
component

feat(chrome): add support for nav text wrapping and nav item brandmark

---

packages/tooltips/README.md
packages/tooltips/src/containers/TooltipContainer.example.md
packages/tooltips/src/containers/TooltipContainer.js
packages/tooltips/src/containers/TooltipContainer.spec.js
packages/tooltips/src/elements/Tooltip.example.md
packages/tooltips/src/elements/Tooltip.js
packages/tooltips/src/elements/Tooltip.spec.js

Since tooltips was one of our first usages of Popper.js the visibility logic was slightly different than Menus, Select, and other usages within the codebase.  This difference causes a stutter effect for some renderings in Safari.
Previously, we handled visibility with a custom `aria-hidden` value to toggle the visibility on/off. This was originally for an accessibility requirement that was shown to not be needed in the recent Axe/Lighthouse walkthrough that I recently completed.
This PR:
- Toggles visibility with a ternary rather than a css:hidden trick
- Adds accessibility changes that was originally surfaced in #66 
- Updates tests to work with new logic
Thanks @zillding for finding this one!
component

fix(tooltips): fix rendering stutter in Safari

---

packages/buttons/src/containers/ButtonGroupContainer.js
packages/buttons/src/containers/ButtonGroupContainer.spec.js
packages/buttons/src/elements/SplitButton.example.md
packages/buttons/src/views/Button.example.md
packages/buttons/src/views/icon-button/IconButton.example.md
packages/selection/src/containers/SelectionContainer.js
packages/selection/src/containers/SelectionContainer.spec.js

This is a continuation of #66 
During the accessibility sweep I found an issue with the `aria-selected` value that we use by default in our `SelectionContainer` component.  There are certain usages where that selected attribute might be different (aria-pressed, aria-checked).
This PR introduces a customization option for the `getContainerProps` method for use in those instances.
I also fixed some assorted accessibility issues found in our react-buttons package including missing `aria-label`'s and adding `aria-pressed` into `ButtonGroupContainer`.
component

feat(buttons|selection): allow customization of selected accessibility value

---

packages/chrome/src/views/header/HeaderItem.spec.js
packages/chrome/src/views/header/HeaderItemText.spec.js
packages/chrome/src/views/header/HeaderItemWrapper.spec.js
packages/chrome/src/views/header/__snapshots__/HeaderItem.spec.js.snap
packages/chrome/src/views/header/__snapshots__/HeaderItemText.spec.js.snap
packages/chrome/src/views/header/__snapshots__/HeaderItemWrapper.spec.js.snap
packages/chrome/src/views/nav/Nav.spec.js
packages/chrome/src/views/nav/NavItem.spec.js
packages/chrome/src/views/nav/NavItemText.spec.js
packages/chrome/src/views/nav/__snapshots__/Nav.spec.js.snap
packages/chrome/src/views/nav/__snapshots__/NavItem.spec.js.snap
packages/chrome/src/views/nav/__snapshots__/NavItemText.spec.js.snap
packages/chrome/src/views/subnav/SubNavItemText.spec.js
packages/chrome/src/views/subnav/__snapshots__/SubNavItemText.spec.js.snap

Fills-in the snapshot testing gaps for various Chrome component props.
component

chore(chrome): fill out component prop snapshot testing

---

packages/modals/README.md
packages/modals/src/containers/ModalContainer.example.md
packages/modals/src/elements/Modal.example.md
packages/modals/src/views/ModalView.example.md
packages/notifications/src/Alert.example.md
packages/notifications/src/Notification.example.md
packages/pagination/src/containers/PaginationContainer.js
packages/pagination/src/containers/PaginationContainer.spec.js
packages/tables/src/examples/overflow-menu.md
packages/tables/src/examples/paginated-table.md

This is a continuation of the accessibility tweaks in #66. It includes:
- `Modals`
- Update markdown examples to include `aria-label` on `<Close />` usages
- `Nofitications`
- Update markdown examples to include `aria-label` on `<Close />` usages
- `Tables`
-  Update markdown examples to include `aria-label` on `<IconButton />` usages
- `Pagination`
- Originally I had a `[role="navigation"]` placed on the Pagination containing element. Turns out this is invalid and it should retain the `listbox` role applied by the `SelectionContainer`. This updates our default `aria-label` to be more descriptive.
component

fix(pagination): remove invalid aria role

---

.babelrc
packages/tooltips/src/utils/gardenPlacements.js

Closes #121. Thanks @SabaRathnamK!
We were using `Object.values()` without a babel transform for IE11. This forces consumers to include the applicable polyfills, which isn't something we should force onto people.
This PR:
- Refactors the `Object.values()` code with IE11 compatible logic
Unrelated:
- Removed the `babel-plugin` prefix from `babel-plugin-styled-components` as it's not needed
I tested this locally in `create-react-app` (no polyfills) in IE11 and it's no longer failing!
component

fix(tooltips): remove Object.values usage for IE11 support

---

packages/autocomplete/src/containers/AutocompleteContainer.js
packages/autocomplete/src/containers/AutocompleteContainer.spec.js
packages/buttons/src/containers/ButtonGroupContainer.js
packages/menus/src/containers/MenuContainer.js
packages/pagination/src/containers/PaginationContainer.js
packages/select/src/containers/SelectContainer.js
packages/selection/src/containers/SelectionContainer.js
packages/selection/src/containers/SelectionContainer.spec.js
packages/tabs/src/containers/TabsContainer.js

Closes #111 
Currently, anything that uses `react-selection` relies on the order that items call `getItemProps`. Sometimes this isn't directly related to the order that it is visually show on the page. See #111 for more details.
This PR adds an optional `index` attribute that allows consumers to define their own order, regardless of when/where items were rendered.
Luckily, with the pattern we have been using this is a small code change that will buble up to nearly every component with ordering.
component

feat(selection|autocomplete|menus): include index attribute to getItemProps to allow custom ordering

---

packages/pagination/src/elements/Pagination.example.md
packages/pagination/src/elements/Pagination.js
packages/pagination/src/elements/Pagination.spec.js

Adds `onChange` to the pagination component. Currently, `onStateChange` triggers whenever the pagination component is blurred. onChange will only trigger on changes to the `currentPage`. 
component

feat(pagination): add onChange for pagination component

---

packages/menus/src/containers/MenuContainer.js
packages/menus/src/containers/MenuContainer.spec.js

Fixes: #137 
Take two, as @sunesimonsen suggested, we had a pretty good solution in our previous menu component to handle closing the menu when clicked outside of the containers.
This adds a mousedown event to any same origin iframe documents and triggers the toggle function to see if it should close or not.

fix(menus): Change handleOutsideMouseDown to handle when clicking on iframes

---

packages/typography/src/views/LG.js
packages/typography/src/views/MD.js
packages/typography/src/views/SM.js
packages/typography/src/views/XL.js
packages/typography/src/views/XXL.js
packages/typography/src/views/XXXL.js

The current `propType` value for the `tag` prop limits inclusion to `string` based tags. This limits the available tags to the native DOM nodes.
With `styled-components` you are actually able to replace it with ANY tag provided, including other React components.
This PR removes the `string` limitation to allow more customization.
component

feat(typography): allow non-string tags for DOM replacement

---

packages/autocomplete/src/examples/multiselect.md

The MultiSelect example within the `react-autocomplete` package had some weird behavior:
* Regardless of which tag was selected, the last one was always deleted
* No mouse interaction could select a menu item
component

fix(autocomplete): update multiselect example to not remove invalid tags

---

lerna.json

The most recent Travis builds have been failing due to some authentication issues with the yarn registry.  This PR sets the `lerna publish --registry` command to use the NPM registry exclusively.
I've tested this locally to deploy the packages that were missed in https://travis-ci.org/zendeskgarden/react-components/builds/429674586
component

fix(publish): default lerna publish registry to NPM

---

packages/select/src/elements/SelectField.js

Closes #150 
Due to the ordering of our `render()` method in the `SelectField` component, we were unintentionally returning an array. This was breaking in React version < 16.
This PR updates the render method to now match the `TextField` component and remove the array.
component

fix(select): remove array render to support React <16

---

packages/autocomplete/src/containers/AutocompleteContainer.js

@albertldlan found a bug in our event default prevention logic in `AutocompleteContainer`. Regardless of if we performed an action from a `RIGHT` keyCode, we were calling `preventDefault`. 
This was causing all `RIGHT` keyboard navigation in an input to fail.

fix(autocomplete): remove event default prevention for all right arrow presses

---

packages/testing/src/index.js
packages/testing/src/utils/renderWithTheme.example.md
packages/testing/src/utils/renderWithTheme.js

This pr adds `renderWithTheme` testing helper.
component

feat(testing): add renderWithTheme

---

packages/menus/src/containers/MenuContainer.spec.js
packages/testing/src/utils/mountWithTheme.js
packages/testing/src/utils/renderWithTheme.js
packages/testing/src/utils/shallowWithTheme.js

The Enzyme [`mount`](https://github.com/airbnb/enzyme/blob/9d2ebb7b35197739c3f30a3a0d9a6c21dd6ee95a/packages/enzyme/src/mount.js#L9), [`render`](https://github.com/airbnb/enzyme/blob/9d2ebb7b35197739c3f30a3a0d9a6c21dd6ee95a/packages/enzyme/src/render.js#L18), [`shallow`](https://github.com/airbnb/enzyme/blob/9d2ebb7b35197739c3f30a3a0d9a6c21dd6ee95a/packages/enzyme/src/shallow.js#L9) helpers accept only 2 arguments. So, this fix spreads the passed `enzymeOptions` into the second one before `context` and `childContextTypes` properties.
If `context` or `childContextTypes` is passed through the options, should be there any warning that these properties will be overridden?
component

fix(testing): fix enzyme options passing

---

packages/tabs/src/elements/Tabs.example.md
packages/tabs/src/elements/Tabs.js
packages/tabs/src/elements/Tabs.spec.js

We currently don't allow consumers to spread props onto the Tab components that are created within `Tabs`.
This PR adds an optional `tabProps` attribute for these spreadable props.  Since this surface area is shared with the `TabPanel` props we aren't able to spread like normal.
component

feat(tabs): spread props to Tab component

---

README.md

This PR adds documentation linking to a new CodeSandbox template: https://codesandbox.io/s/1qw90o82pl
Please take a look and let me know if there is anything else that should be added. It is currently using `create-react-app@v2` so everything should be as up-to-date as possible.
component

chore(docs): add CodeSandbox template example

---

packages/tables/src/examples/overflow-menu.md
packages/tables/src/views/Cell.js
packages/tables/src/views/HeaderRow.js
packages/tables/src/views/OverflowButton.js
packages/tables/src/views/__snapshots__/Cell.spec.js.snap
packages/tables/src/views/__snapshots__/HeaderRow.spec.js.snap
packages/tables/src/views/__snapshots__/SortableCell.spec.js.snap

This PR updates header OverflowButton logic to simplify menu placement within a Table.
component

fix(tables): correct placement of OverflowButton menus

---

utils/styleguide/CodeTabButton/index.js
utils/styleguide/styleguide.base.config.js

All the code examples currently have a "View Code" button below the live examples, it's not clear from that that you can actually edit the code to change the live example. 
This PR changes it to "Edit Code".
component

feat(docs): Changed View Code to Edit Code

---

packages/menus/package.json
packages/menus/src/containers/MenuContainer.example.md
packages/menus/src/containers/MenuContainer.js
packages/menus/src/containers/MenuContainer.spec.js
packages/menus/src/views/items/Item.example.md
packages/menus/src/views/items/Item.js
packages/menus/src/views/items/__snapshots__/Item.spec.js.snap
packages/menus/src/views/items/header/HeaderItem.js
packages/menus/src/views/items/header/HeaderItem.spec.js
packages/menus/src/views/items/header/__snapshots__/HeaderItem.spec.js.snap
packages/select/src/views/Dropdown.example.md

Should also force a breaking change onto all dependent packages; rather than the default lerna behavior of marking it as a patch.
- Removes an invalid `active` prop from a Menu example
- Adds `containsIcon` property for `HeaderItem` components (`icon` is a native attribute 😢 )
- Adds `onMouseMove` event to allow "focus on hover" mechanism
- @allisonacs lets meet-up and go over this interaction pattern to double-check a few things
component

feat(menus): update Menu/Select Item indentation and focus based on item hover

---

packages/buttons/src/views/Button.js
packages/buttons/src/views/Button.spec.js
packages/buttons/src/views/__snapshots__/Button.spec.js.snap

@vedranio found an issue when users choose to add `disabled` styling a `<Button` while also using the `danger` styling.
We should add some `disabled` logic checks to our conditional className logic.
component

fix(buttons): disable danger styling if disabled

---

packages/modals/package.json
packages/modals/src/elements/Modal.example.md

Provide consistent header/body/footer stacking...
* whether or not a footer is included
* despite modal dialog element ordering
* for both default & large dialog sizes
See https://github.com/zendeskgarden/css-components/pull/134 for details.
component

fix(modals): update devDependency @zendeskgarden/css-modals to correct padding for various header/body/footer layouts

---

packages/textfields/package.json
packages/textfields/src/elements/FauxInput.js
packages/textfields/src/views/MediaFigure.example.md
packages/textfields/src/views/MediaInput.js
packages/textfields/src/views/MediaInput.spec.js
packages/textfields/src/views/__snapshots__/MediaInput.spec.js.snap
utils/travis/publish-gh-pages.js

Used to apply correct styling to media textfield layouts:
```js
<FauxInput mediaLayout>
<MediaFigure>
<SearchIcon />
</MediaFigure>
<MediaInput aria-label="Media Input Example" placeholder="Example media input" />
<MediaFigure>
<SettingsIcon />
</MediaFigure>
</FauxInput>;
```
Also contains styling fixes provided by `@zendeskgarden/css-forms@6.1.3`.
component

feat(textfields): add new `MediaInput` component

---

packages/menus/src/containers/MenuContainer.js
packages/menus/src/containers/MenuContainer.spec.js
packages/select/src/containers/SelectContainer.js
packages/select/src/elements/Select.js

If you have a disabled `<Select>` and you click it its internal state still updates `isOpen` to true and upon re-enabling will render the dropdown.
Pre-published: https://garden.zendesk.com/react-components/select/
The `disabled` prop is now passed to `MenuContainer` where the visibility toggle method now checks the disabled state before flipping the `isOpen` value.

fix(select): Expanded state is triggered on disabled select click

---

packages/loaders/src/containers/ScheduleContainer.js

We currently have situations where we get multiple requestAnimationFrame callbacks queued up and componentWillUnmount will only cancel the latest one. This results in settings the state on an unmounted component which React warns about.
This fix uses the more conventional way of using requestAnimationFrame, where you start a new animation frame at the end of the last one.

fix(loaders): competing calls to requestAnimationFrame

---

packages/utilities/src/utils/hasType.js
packages/utilities/src/utils/hasType.spec.js

If our `hasType` utility method is passed a falsy value such as `null` it'll fall over as it tries to check an undefined property on it.
`hasType` will return early if passed a falsy value. 
Currently trying to conditionally render components in textfields will throw:
```jsx
<TextField>
<Label>Label</Label>
{state.showHint && <Hint>A hint</Hint>}
<Input />
</TextField>
```
Fixes: #218

fix(utilities): hasType should handle falsy values

---

packages/tabs/README.md

In documentation it looks like that `selectedKey` value in the `initialState` is referencing tab label, instead of the key. The pr fixes this to use the tab key.
Before:
```
initialState = { selectedKey: 'Tab 1' };
```
After:
```
initialState = { selectedKey: 'tab-1' };
```
component

Fixes tabs Readme selected key value

---

packages/chrome/package.json

Updates the nav to use 52px height.
https://github.com/zendeskgarden/css-components/pull/152
component

feat(chrome): update `@zendeskgarden/css-chrome` dependency

---

.travis.yml

Our travis build is slooooow
This PR does a small change to make lint, format & test:all run in parallel if any one of those fail the build fails and it makes it easier to see what was the culprit.
Our longest step is building the demo files so I just wanted to get low hanging fruit tested first and then tackle trying to speed up demo building in another PR.

chore(build): Make some jobs run a parallel to speed up CI build time

---

packages/tooltips/src/containers/TooltipContainer.example.md
packages/tooltips/src/containers/TooltipContainer.js
packages/tooltips/src/containers/TooltipContainer.spec.js
packages/tooltips/src/elements/Tooltip.js

The current `TooltipContainer` wraps the trigger element in a `<div>` to provide a consistent `ref` to Popper.js
This is bad because it limits the amount of areas that a tooltip can be used. A `<div>` may not be a valid element for a specific dom nesting, it may miss-align other items, etc.
Bottom-line, it isn't very flexible.
This PR removes the wrapping `<div>` from `TooltipContainer` and provides a `ref` callback to the `trigger` render-prop.  This can be applied to any element without a wrapper being necessary.
This is a **breaking change** to `TooltipContainer`
For the high-abstraction `Tooltip` element I've moved the `<div>` wrapper to be automatically applied, which shouldn't break any current usages and supports the "easiest" usecase.
Originally brought up by @thebritican with his …

feat(tooltips): remove wrapping div from TooltipContainer

---

packages/typography/src/index.js
packages/typography/src/views/Ellipsis.example.md
packages/typography/src/views/Ellipsis.js
packages/typography/src/views/Ellipsis.spec.js
packages/typography/src/views/__snapshots__/Ellipsis.spec.js.snap
packages/typography/styleguide.config.js

This PR introduces the `Ellipsis` component. The intention of this component is to help abstract common text-overflow implementations into a single component within `@zendeskgarden/react-typography`.
The component is relatively simple and only:
* Applies a `title` attribute based on the children provided.
* This matches the prescribed Garden styling of using a native tooltip for text-overflow scenarios
* Applies some simple `text-overflow` styling
* Allows a custom `tag` to be applied (`div` by default)
I've added @Anifacted and @sunesimonsen as reviewers since this component previously existed in the `core` area of `react-components`.
I experimented with allowing any type of `children` within the component and using a `ref` to capture the `textContent` of the `DOMNode`, but ran into some …

feat(typography): introduce new Ellipsis component

---

packages/modals/src/elements/Modal.example.md
packages/modals/src/views/Header.js
packages/modals/src/views/Header.spec.js
packages/modals/src/views/__snapshots__/Header.spec.js.snap

Adds a `danger` prop to `<Header>` for applying `.c-dialog__header--danger` styling.
component

feat(modals): add "danger" header styling

---

.huskyrc
.lintstagedrc
package.json
yarn.lock

Our `pre-commit` hook has been taking a long enough time that I've found myself consistently using the `--no-verify` flag, which is bad.
This PR introduces the `lint-staged` package into our husky `pre-commit` hook.  This allows us to individually lint, format, and `git add` the files to reduce the time needed.
With this change even large, 40+ file changes run in under 2 seconds during the `pre-commit` hook.
Since `lint-staged` supplies a list of individual files for linting, there is no need to use the current npm scrips since they run through lerna. They're still valuable for the build process, but not for this hook.
The steps added to the hook are:
* `*.js`
* stylelint within styled-componets (failure will exit commit)
* eslint (failure will exit commit)
* write prettier changes
* add …

chore(build): update pre-commit hook to use lint-staged

---

.travis.yml

This changes which version of yarn is installed by travis so we can avoid the `Buffer()` deprecation warnings messing up our logs.
See yarn issue: yarnpkg/yarn#5477
See travis issue: travis-ci/travis-ci#7471
All we do is run the install shell script to grab the latest stable (1.12.3)

chore(build): force latest stable of yarn in ci to fix Buffer warnings

---

packages/autocomplete/src/elements/Autocomplete.js
packages/select/src/elements/Select.js

Closes #247 
This PR corrects two `PropType`'s that were incorrectly listed as allowing both `string & number` `maxHeight` values.
When we originally inlined these values with `style` these prop-types made sense, but with the move of these values into a styled-components context it is no longer possible, unless we use the object syntax which is available in v4.
component

fix(autocomplete|select): limit propTypes of maxHeight to string

---

packages/breadcrumbs/package.json
packages/breadcrumbs/src/containers/BreadcrumbContainer.js
packages/breadcrumbs/src/containers/BreadcrumbContainer.spec.js
packages/breadcrumbs/src/elements/Breadcrumb.js
packages/breadcrumbs/src/elements/Breadcrumb.spec.js

Add container support for consumers that utilize anchor tags for final breadcrumb in the list.
component

feat(breadcrumbs): add support for `aria-current`

---

packages/autocomplete/src/elements/Autocomplete.js
packages/autocomplete/src/elements/Autocomplete.spec.js
packages/buttons/package.json
packages/buttons/src/views/Button.js
packages/buttons/src/views/Button.spec.js
packages/buttons/src/views/__snapshots__/Button.spec.js.snap
packages/buttons/src/views/icon-button/ChevronButton.js
packages/buttons/src/views/icon-button/ChevronButton.spec.js
packages/buttons/src/views/icon-button/__snapshots__/ChevronButton.spec.js.snap
packages/select/src/views/SelectView.js
packages/select/src/views/SelectView.spec.js
packages/select/src/views/__snapshots__/SelectView.spec.js.snap
packages/textfields/package.json
packages/textfields/src/elements/FauxInput.js
packages/textfields/src/views/Input.js
packages/textfields/src/views/Input.spec.js
packages/textfields/src/views/Textarea.js
packages/textfields/src/views/Textarea.spec.js
packages/textfields/src/views/__snapshots__/Input.spec.js.snap
packages/textfields/src/views/__snapshots__/Textarea.spec.js.snap

Supports this type of treatment:
component

feat(autocomplete|buttons|select|textfields): provide `focusInset` styling for stacked element designs

---

.eslintrc.json
demo/index.html
packages/ranges/package.json
packages/ranges/src/elements/MultiThumbRange.example.md
packages/ranges/src/elements/MultiThumbRange.js
packages/ranges/src/elements/MultiThumbRange.spec.js
packages/ranges/src/elements/Range.js
packages/ranges/src/elements/RangeField.js
packages/ranges/src/index.js

This PR adds a new `MultiThumbRange` component. It follows the [Two-Thumb Slider W3C Pattern](https://www.w3.org/TR/wai-aria-practices/#slidertwothumb).
Due to the complexity of the drag functionality and it's tight coupling to how we structure our sliders visually, I've chosen to not break this component into separate Container and View components.
@jzempel @ryanseddon any thoughts on this? If more customization is needed in the future we can re-evaluate the split.
Pre-published at https://garden.zendesk.com/react-components/ranges
component

feat(ranges): introduce MultiThumbRange component

---

packages/ranges/src/elements/MultiThumbRange.js
utils/scripts/get-cids.sh

The original release of `MultiThumbRange` was missing the analytics attributes we use within Pendo.
This PR adds them!
component

fix(ranges): add analytics attributes to MultiThumbRange

---

packages/chrome/package.json
packages/chrome/src/index.js
packages/chrome/src/views/Chrome.example.md
packages/chrome/src/views/footer/Footer.example.md
packages/chrome/src/views/footer/Footer.js
packages/chrome/src/views/footer/Footer.spec.js
packages/chrome/src/views/footer/FooterItem.js
packages/chrome/src/views/footer/FooterItem.spec.js
packages/chrome/src/views/footer/__snapshots__/Footer.spec.js.snap
packages/chrome/src/views/footer/__snapshots__/FooterItem.spec.js.snap
packages/chrome/styleguide.config.js

Supports the addition of a footer action bar.
Follow-on from https://github.com/zendeskgarden/css-components/pull/171
component

feat(chrome): add `Footer` component

---

packages/testing/src/utils/getExports.example.md
packages/testing/src/utils/getExports.js

Glob has a few other options that would be useful to access through this helper method.
I wanted to ignore a directory, rather than add just `ignore` as another parameter I've added the `options` parameter so you can pass through any [glob option](https://github.com/isaacs/node-glob#options).
I've also made this a non-breaking change by keeping `cwd` around. 
Both of these are valid uses of `getExports`.
```js
getExports({ cwd: __dirname, options: { ignore: 'a/**' } });
```
```js
getExports({ options: { ignore: 'a/**', cwd: __dirname } });
```
If you specify the `cwd` option that will override a `cwd` property in the `options` parameter.

chore(testing): Add options object to be able to pass in other glob options

---

packages/loaders/src/Skeleton.js
packages/loaders/src/__snapshots__/Skeleton.spec.js.snap

The alpha value that I used for the background animation in the `Skeleton` component was off by a few percent.
This PR corrects the animation color.
(Reviewed locally by @ginnywood)

fix(loaders): increase alpha of skeleton animation

---

packages/notifications/package.json
packages/notifications/src/Alert.example.md
packages/notifications/src/Alert.js
packages/notifications/src/Alert.spec.js
packages/notifications/src/Notification.example.md
packages/notifications/src/Notification.js
packages/notifications/src/Notification.spec.js
packages/notifications/src/Well.example.md
packages/notifications/src/__snapshots__/Alert.spec.js.snap
packages/notifications/src/__snapshots__/Notification.spec.js.snap

Brings over the new styling from `css-callouts`.
https://github.com/zendeskgarden/css-components/pull/174
component

feat(notifications): add new "info" styled Alert and Notification

---

utils/build/webpack.commonjs.js

When we migrated to `@svgr/webpack` #221 we broke react-buttons as part of that change as we removed `babel-plugin-inline-react-svg`.
Right now if you pull down the latest react-buttons package in something like codesandbox or as part of a create-react-app it'll throw about not finding an svg. See test case https://codesandbox.io/s/pjo7kk1lmj
We just need to whitelist svg-icons from externals so svgr can still inline it correctly.
fixes #281

fix(buttons): Whitelist svg-icons so they get inlined correctly

---

packages/notifications/package.json

It looks like #283 caused the build to break due to the `package.json` being formatted.  I don't know why this didn't fail in the PRs Travis run. I thought that prettier-package-json moved it for you since it stayed alphabetical 🤷‍♂️ 
We will need to force apply a `patch` version to `react-menus` to ensure it gets deployed correctly.

fix(notifications): update package.json to pass build

---

.github/CODE_OF_CONDUCT.md

Fix code of conduct links that got munged by prettier.
component~

chore: fix malformed Code of Conduct links

---

packages/autocomplete/src/elements/Autocomplete.js
packages/autocomplete/src/elements/Multiselect.js

Passing through the popperModifiers prop to the underlying `AutocompleteContainer`.
Right now if people use the high abstraction `Autocomplete` or `MultiSelect` components and want to for example force the menu to always appear below the field they need to pass through the right options to popperjs this change allows them to do that.
component~

fix(autocomplete): Pass through popperModifiers from high abstraction components

---

packages/loaders/src/Inline.example.md
packages/loaders/src/Inline.js
packages/loaders/src/__snapshots__/Inline.spec.js.snap

Per our conversation today, the `Inline` loader should have a default color of `inherit`.
component

fix(loaders): default Inline loader to use inherit color

---

packages/autocomplete/src/elements/Autocomplete.example.md
packages/autocomplete/src/elements/Autocomplete.js
packages/autocomplete/src/elements/Autocomplete.spec.js

- Makes it possible to fully control the Autocomplete component's state from the outside, similarly to how the Menu component works.
- Also adds support for the `children` prop, which can be used to display a custom value while the component is not open.
component

feat(autocomplete): make it a controlled component

---

packages/autocomplete/src/elements/Multiselect.js
packages/autocomplete/src/elements/Multiselect.spec.js

Within `MultiSelect` we currently are not respecting the optional `label` option when we render Tags.
This PR enables that feature.
- ~:ok_hand: design updates are Garden Designer approved (add the
- ~:nail_care: view component styling is based on a Garden CSS
component~

fix(autocomplete): allow tags to render with optional label value

---

packages/tags/package.json
packages/tags/src/views/Tag.example.md
packages/tags/src/views/Tag.js
packages/tags/src/views/Tag.spec.js
packages/tags/src/views/__snapshots__/Tag.spec.js.snap

Adds:
* `fuschia`
* `pink`
* `crimson`
* `orange`
* `lemon`
* `lime`
* `mint`
* `teal`
* `azure`
* `royal`
* `purple`
Demo is pre-published for review: https://garden.zendesk.com/react-components/tags/#!/Tag/5
component

feat(tags): add secondary color options to `type` prop

---

packages/autocomplete/src/elements/Multiselect.js

fix(autoselect): prevent line-height shift on tag delete

---

packages/textfields/src/views/Message.js
packages/textfields/src/views/__snapshots__/Message.spec.js.snap

In current form, a user relying upon assistive technology does not receive feedback as a validation message is updated. Adding this role provides expected feedback.
* Direction provided by WAI-ARIA: https://www.w3.org/WAI/GL/wiki/Using_ARIA_role_of_alert_for_Error_Feedback_in_Forms.
* Some inspiration taken from https://v4-alpha.getbootstrap.com/components/alerts/#examples.
component

fix(textfields): default `<Message/>` with `role="alert"` for improved accessibility

---

packages/tooltips/src/containers/TooltipContainer.js
packages/tooltips/src/containers/TooltipContainer.spec.js

Currently, if a user clicks or keyboard focuses the triggering element the tooltips dismisses itself when a user tries to interact with any link, button, or focusable element in the tooltip body.
This PR introduces some additional `onFocus` and `onBlur` event handlers for the tooltip body to allow elements within it to receive focus via mouse and keyboard regardless of trigger focus state.
component

fix(tooltips): allow focusable content within tooltips

---

utils/styleguide/styleguide.base.config.js

During the large devDependency upgrade there was a change in `core-js` that I missed in their changelog https://github.com/zloirock/core-js/blob/master/CHANGELOG.md#300---20190319
We include `core-js/shim` into our styleguidist examples. This is now just `core-js`.  Since doc builds aren't included in our current travis runs this was missed.
When we explore using Gatsby and showing per-PR doc examples this should no longer be something that doesn't get tested in the PR process.
component~

fix(docs): fix core-js shim during docs build

---

packages/autocomplete/src/containers/AutocompleteContainer.js
packages/autocomplete/src/containers/AutocompleteContainer.spec.js

Currently, when blurring the input, a re-render is triggered when the `isOpen` prop going from `true` to `false`. This should only happen when `isOpen` is `true` already, since side-effects may be attached to this logic. This PR fixes that.
component

fix(autocomplete): Do not always trigger dropdown closing on blur

---

packages/selection/README.md

Fix incorrect docs
The `KeyboardFocusContainer` example incorrectly used a `focused` prop that should be `keyboardFocused`.
component~

docs: Fix incorrect prop used in KeyboardFocusContainer example

---

__mocks__/popper.js.js
packages/dropdowns/src/Menu/Menu.js
packages/dropdowns/src/Menu/Menu.spec.js

There are some performance issues with the original dropdown implementation, specifically with how we handle scheduled updates within PopperJS.
The specific issues that are fixed include:
- `eventsEnabled` prop was enabled when dropdown was closed
- This was causing popper to re-position as a user was scrolling, even when the menu were closed. This isn't needed. It now disables this option while the menu is closed.
- Constantly scheduling updates
- I originally placed a `scheduleUpdate()` call within the Popper renderer. This causes an infinite loop of renders 💀 
- This isn't as noticeable in some instances since Popper is using requestAnimationFrame for its positioning logic, but can become noticeable with a lot of state updates in Downshift.
- There is now logic to only run this once …

fix(dropdowns): improve performance of Menu updates

---

packages/dropdowns/src/Dropdown/Dropdown.js
packages/dropdowns/src/Dropdown/Dropdown.spec.js
packages/dropdowns/src/examples/autocomplete.md
packages/dropdowns/src/examples/menu.md

Now that the new `Dropdown` component is getting some moderate usage a few friction points have come up. These include:
> Most interactions include modifying multiple stateful properties (isOpen, highlightedIndex, inputValue, and selectedItem). With these being modified with separate callbacks it can become difficult to modifying these values together.
Downshift uses a singular [onStateChange](https://github.com/downshift-js/downshift#onstatechange) property to allow these to be handled together. 
This PR includes a **BREAKING CHANGE** to move to this model. It removes the `onInputValueChange, onOpen, and onHighlight` props and adds `onStateChange`.
> When toggling Dropdown, option for the input to be selected/highlighted or reset. Closes #322 
By default Downshift will set the …

feat(dropdowns): migrate Dropdown to use an onStateChange handler

---

packages/avatars/package.json
packages/avatars/src/Avatar.js
packages/avatars/src/Avatar.spec.js
packages/theming/package.json
packages/theming/src/utils/withTheme.spec.js
packages/typography/package.json
packages/typography/src/views/Code.spec.js
packages/typography/src/views/Ellipsis.js
packages/typography/src/views/Ellipsis.spec.js
packages/typography/src/views/LG.spec.js
packages/typography/src/views/MD.spec.js
packages/typography/src/views/SM.spec.js
packages/typography/src/views/XL.spec.js
packages/typography/src/views/XXL.spec.js
packages/typography/src/views/XXXL.spec.js

In an effort to split up the review sizes for the React v16 upgrade I've created a new base upgrade branch `agreen/react-16-upgrade`.
This base branch already has the root `package.json`, nextjs example, and template file upgrades.  I will be upgrading 1 package per commit and grouping theming into several PRs to help with the review strain.
Each upgrade will
- Upgrade the `package.json` with new peerDependencies and remove any unnecessary packages
- Refactor all styled-components usage to eliminate deprecated APIs
- Refactor all refs to use the new `forwardRef` API to match styled-components
- Remove portal and fragment polyfills where necessary
- Upgrade all tests to `react-testing-library` to better align with the new packages
- With these being a full mount and render we will see any …

Upgrade avatars, theming, and typography packages

---

packages/buttons/README.md

ThemeProvide will only accept a single child.
```
The above error occurred in the <Context.Consumer> component:
in ThemeProvider (created by ThemeProvider)
in ThemeProvider (created by MyApp)
in MyApp
...
Error: React.Children.only expected to receive a single React element child.
```

docs: ThemeProvide will only accept a single child.

---

packages/buttons/README.md

Remove an invalid deprecation warning from the button docs.

fix(docs): remove invalid deprecation warning

---

packages/forms/src/fields/other/MediaInput.js
packages/forms/src/fields/other/MediaInput.spec.js

With the new `MediaInput` component in `react-forms` the disabled option for the native `<input />` doesn't apply the disabled styling of the containing `FauxInput`.
This PR destructures the `disabled` prop and applies the styling correctly.
Even though this isn't directly about #265 it was closed with the addition of react-forms. Going to close here just as a reference.
Closes #265 
component

fix(forms): allow disabled styling with MediaInputs

---

packages/dropdowns/src/Menu/Items/AddItem.js
packages/dropdowns/src/Menu/Items/NextItem.js

All Dropdown items other than `AddItem` and `NextItem` allow `value` to be of type `PropTypes.any`. This just makes `AddItem` and `NextItem` consistent with the other Items.
component

fix(dropdowns): make dropdown item value types consistent

---

utils/build/webpack.base.js

@louisscruz and @bmson were able to find some CSS collisions between our `react-menus` and `react-dropdowns` package.
Depending on how CSS is handled within a consuming application this may or may not be affecting all consumers at this point.
Due to our split lerna build we have to add some more advanced options to generate a unique hash for CSS modules to be unique.
Our current webpack config includes the follow CSS-modules customization:
```js
{
test: /\.css?$/u,
include: /@zendeskgarden\/css/u,
use: [
MiniCssExtractPlugin.loader,
{
loader: 'css-loader',
options: {
modules: true,
localIdentName: '[name]__[local]___[hash:base64:5]'
}
}
]
}
```
The `localIdentName`, specifically `hash:base64:5` was being duplicated. 
This has been creating common hashes in the computed CSS.
After looking …

fix(build): remove duplicate classNames from webpack build

---

utils/build/webpack.umd.js

This PR fixes an instance where `prop-types` was exported as `rop-types` in the webpack.umd.js config file.
component

Fix umd webpack config for prop-types

---

packages/tags/src/views/Tag.example.md
packages/tags/src/views/Tag.js
packages/tags/src/views/Tag.spec.js

Picks up missing shape styling from https://garden.zendesk.com/css-components/tags/.
component

feat(tags): prop for "round" tag styling

---

packages/dropdowns/src/styled/field/StyledField.js
packages/dropdowns/src/styled/field/StyledLabel.js
packages/dropdowns/src/styled/field/StyledSelect.js

This PR fixes a few invalid COMPONENT_ID prefixes within the dropdowns package.
component~

fix(dropdowns): namespace styled elements correctly

---

packages/checkboxes/README.md
packages/checkboxes/src/index.js
packages/radios/README.md
packages/radios/src/index.js
packages/textfields/README.md
packages/textfields/src/index.js
packages/toggles/README.md
packages/toggles/src/index.js

This PR adds deprecation warnings to the root import and documentation of `react-checkboxes`, `react-radios`, `react-textfields`, and `react-toggles`.
component~

chore(forms): add deprecation notices to checkboxes, radios, textfields, and toggles

---

packages/tables/src/examples/paginated-table.md

`32` (avatar) + `24` (cell padding) = `56px`.
component

fix(tables): adjust paginated example cell width to accommodate small-sized avatar

---

utils/scripts/version.sh

During the `v6.0.1` publish we found a few more issues with `version.sh`. This PR addresses:
- Ensure `GITHUB_AUTH` is available to all scripts
- Ensure all git tags are up-to-date
component

fix(build): add tag fetching to process

---

packages/avatars/package.json
packages/avatars/src/Avatar.example.md
packages/avatars/src/Avatar.js
packages/avatars/src/Avatar.spec.js
packages/avatars/src/styled.js
packages/avatars/src/styled.spec.js

Use `@zendeskgarden/css-avatars` v6.0.0.
Notice, with the removal of the `<figcaption>` element, all badge transitions now scale in/out as desired.
Described under https://github.com/zendeskgarden/css-components/pull/202
component

fix(avatars): update avatar CSS for badge animation

---

packages/buttons/src/views/icon-button/Icon.js
packages/buttons/src/views/icon-button/Icon.spec.js

Hi, this is my first Garden PR. Happy to learn and to adjust anything :)
Passes down the className prop to the <Icon /> component, for using it with styled components, fela and other CSS in JS libraries.
https://github.com/zendeskgarden/react-components/issues/365

fix(buttons): Pass className to <Icon />

---

packages/avatars/src/Avatar.js
packages/avatars/src/Avatar.spec.js

Noticed some testing errors and `console.errors` while doing the pre-publish steps. This fixes a single propType error and remove an invalid test.

fix(avatars): update propTypes to accurately check badge type

---

packages/avatars/package.json
packages/avatars/src/Avatar.example.md
packages/avatars/src/Avatar.js
packages/avatars/src/Avatar.spec.js
packages/avatars/src/styled.js

Corrects business logic that fails to display crimson ring and notification count when avatar has a status of `away`. Additionally enhances example demo page with improved accessibility and usage instructions.
The demo has been temporarily pre-published for review: https://garden.zendesk.com/react-components/avatars/. Check it out before other merged PRs re-write GH pages.
component

fix(avatars): display badge status whenever badge data exists

---

packages/notifications/src/Alert.js
packages/notifications/src/Alert.spec.js
packages/notifications/src/Notification.js
packages/notifications/src/Notification.spec.js

It looks like the `.attrs()` logic in styled-components has changed again https://github.com/styled-components/styled-components/issues/2372
This was working after our 4.2.0 upgrade, but now certain props aren't being passed to their composed elements.
This is working in other packages as we only add to the `className` attribute.
To resolve this issue I removed all usages of `styled(Well)` and am now applying the required styles directly.
component

fix(notifications): show correct Notification and Alert styling

---

packages/dropdowns/src/styled/field/StyledSelect.ts

When products use normalize.css, specifically https://github.com/necolas/normalize.css/blob/master/normalize.css#L195-L200, and `@zendeskgarden/css-bedrock` it is possible to have some styling conflicts with the `Select` and `Autocomplete` components in `react-dropdowns`.
This PR introduces an appearance rule with higher specificity.
component

fix(dropdowns): remove webkit button styling when used with css-bedrock

---

examples/nextjs/components/layout.js
examples/nextjs/package.json
examples/nextjs/pages/_app.js
examples/nextjs/pages/_document.js
examples/nextjs/pages/index.js
examples/nextjs/yarn.lock
packages/dropdowns/src/index.ts

While upgrading the dependencies for the nextjs example, I found that our `react-dropdowns` package doesn't handle SSR correctly.
This PR upgrades the nextjs dependencies and adds a re-export to the [resetIdCounter](https://github.com/downshift-js/downshift#resetidcounter) utility provided by downshift.
component

feat(dropdowns): export resetIdCounter to allow SSR

---

packages/dropdowns/src/Dropdown/Dropdown.tsx
packages/dropdowns/src/examples/menu.md

Within the `Dropdown` component it was possible for the `PreviousItem` to not be selected correctly with the `LeftArrow` key if a previous item had been selected. This is now fixed.
There was logic to detect if there was a non-empty `inputValue` within Downshift to restrict this navigation. This is useful for autocompletes where the left arrow can be used to navigate the text.
To resolve this I now remove the `inputValue` on all item selection.
cc @louisscruz 
component

fix(dropdowns): allow previous item selection with arrow key

---

packages/datepickers/README.md
packages/datepickers/src/Datepicker.tsx
packages/datepickers/src/examples/localization.md

There is some stale documentation relating to `date-fns` usage in the `Datepicker` docs. This PR updates these areas.
component~

chore(datepicker): update examples to include correct localization names

---

packages/dropdowns/src/examples/autocomplete.md

The bug is originally captured by rollbar whitin Zendesk, after upgrading dropdown component @zendeskgarden/react-dropdowns": "6.2.1" .
The problem is that Google Translate replaces text nodes with <font> tags containing translations while React keeps references to the text nodes that are no longer in the DOM tree. 
React throws in the following cases:
- A text node is conditionally rendered and it's not the only child of its parent.
- A node before a text node is conditionally rendered
The easiest workaround is to wrap those text nodes with <span> so that nodes referenced by React will stay in the DOM tree even though their contents are replaced with <font> tags.
- [Issue reported to React](https://github.com/facebook/react/issues/11538#issuecomment-390386520) …

Update autocomplete dropdown example due to google translate issue

---

packages/breadcrumbs/package.json
packages/breadcrumbs/src/containers/BreadcrumbContainer.js
packages/breadcrumbs/src/elements/Breadcrumb.js

Replace `BreadcrumbContainer` with `useBreadcrumb` hook.
This PR deprecates `BreadcrumbContainer` by adding `console.warn` message in non production environments.
It also removes `BreadcrumbContainer` in `Breadcrumb` element in favour of `useBreadcrumb`.
component~

feat(breadcrumbs): Migrate package to container-breadcrumb

---

packages/buttons/src/views/icon-button/ChevronButton.js
packages/buttons/src/views/icon-button/IconButton.js

With the new `React.createRef` usages, some of our old "forward-ref" props have invalid prop-types. An example error:
```
// When supplying React.createRef() to `buttonRef`
Warning: Failed prop type: Invalid prop `buttonRef` of type `object` 
supplied to `IconButton`, expected `function`.
```
This PR corrects the invalid prop-types for the `react-buttons` package. There are also other usages of `PropTypes.func` for refs in additional packages, but they are currently deprecated. I am excluding them from this PR.
component~

fix(buttons): allow correct ref validation in PropTypes

---

packages/buttons/src/views/Anchor.js

`white-space: pre;` blocks `word-wrap: break-word;` from taking effect in both Chrome and Firefox. 
As an example, the following string in the screenshot is actually "one line" but the text within the link is not wrapping properly:
`white-space: pre-wrap;` seems to work in all browsers.

fix(buttons): white-space/word-wrap styling in the Anchor component

---

packages/dropdowns/src/Menu/Items/Item.ts

The `Item` subcomponent of `Menu` checks the presence of the `value` prop by using `!value`, which will return `true` if the `value` prop is `0`. This PR aims to change the error handling to be exclusive of `0`, and explicitly just check if `value` is undefined or null.

feat(Menu/Items/Item): change Item 'value' requirement to be inclusive of 0

---

utils/scripts/get-cids.sh

Some of our theming ids are not referenced via the `COMPONENT_ID` const and are in fact inline. This PR fixes that.
Changed the awk script to find inline and referenced component ids.
Local table generated here now includes the missing `forms` theming ids:
Fixes: #401 
component~

docs: Theme ids missing for inline examples

---

utils/scripts/get-cids.sh

Seems there was some slight difference in grep regexp on macos vs linux the search also missed some other ids.
The last PR would capture some of the missing ids on macOS but when running on the travis linux boxes it failed to find those.
I loosened the grep regexp and instead do more cleanup in the awk script, this should capture all ids now.
#401 actually fixes that now
Tested this on a linux box to verify correct results.
component~

docs: Theme ids missing

---

packages/dropdowns/src/Dropdown/Dropdown.tsx
packages/dropdowns/src/examples/autocomplete.md

Due to the concurrent nature of the `stateReducer` and `onStateChange` customizations in Downshift the cursor position may be lost for certain key commands (i.e. combinations of unicode symbols).
Downshift provides the [onInputValueChange](https://github.com/downshift-js/downshift#oninputvaluechange) prop which is ran before the sequential stateReducers.
I've added an `onInputValueChange` prop which proxies directly to Downshift. I've also updated our example to use that prop.
It looks like Downshift doesn't respect `stateReducer` customizations when it calls `onInputValueChange`. This doesn't affect our basic usages of Autocomplete, but may cause issues for heavy customizations. I will try and open a PR against Downshift to correct this.
component

fix(dropdowns): persist cursor location in Autocomplete

---

packages/forms/styleguide.config.js

Clicking on the open isolated button only for the [checkboxes examples](https://garden.zendesk.com/react-components/forms/#checkbox) throws, see gif.
Seems for whatever reason that the name `Checkbox` somehow conflicts with react-styleguidist internals, they do have a `Checkbox` component that I tried renaming to see of that would fix the conflict but it still threw.
This is a quick fix.
component~

docs(forms): Checkbox example in forms is throwing

---

packages/datepickers/examples/range.md
packages/datepickers/src/Datepicker/Datepicker.spec.tsx
packages/datepickers/src/Datepicker/components/Calendar.tsx
packages/datepickers/src/DatepickerRange/DatepickerRange.spec.tsx
packages/datepickers/src/DatepickerRange/components/Calendar.tsx
packages/datepickers/src/DatepickerRange/components/Month.tsx
packages/datepickers/src/DatepickerRange/utils/datepicker-range-reducer.ts

While making some additional datepicker examples I found a few issues that I have resolved in this PR.
- `minValue` and `maxValue` displays were off by a single day due to us comparing date values without finding a common day baseline
- `DatepickerRange` usages were unable to have a start and end date that were the same value
component

fix(datepicker): correct minValue and maxValue displays and allow same date selection within Range

---

__mocks__/dom-helpers/util/scrollTo.js

Since we upgraded JS-DOM I have noticed several `not implemented` console.errors from our usage of the `dom-helper` utility library.
This PR adds a global mock for that specific utility. We should see an improved test output now 🎉

fix(test): mock scrollTo dom-helper utility in tests

---

packages/dropdowns/src/examples/autocomplete.md

There is an invalid ARIA role attribute used in the autocomplete (autocomplete.md) example page. I updated the attribute from `role="image"` to `role="img"`.
Resources:
- https://www.w3.org/TR/wai-aria-1.1/#img
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img

fix(dropdowns): Fix invalid ARIA role

---

packages/breadcrumbs/package.json
packages/breadcrumbs/src/containers/BreadcrumbContainer.example.md
packages/breadcrumbs/src/containers/BreadcrumbContainer.js
packages/breadcrumbs/src/elements/Breadcrumb.js

This PR deprecates the `BreadcrumbContainer` component within `react-breadcrumbs` and migrates the packages to the `useBreadcrumb()` container.
component

feat(breadcrumbs): deprecate BreadcrumbContainer and migrate to useBreadcrumb() container

---

packages/autocomplete/package.json
packages/menus/package.json
packages/select/package.json
packages/tooltips/package.json
packages/tooltips/src/containers/TooltipContainer.example.md
packages/tooltips/src/containers/TooltipContainer.js
packages/tooltips/src/elements/Tooltip.js
packages/tooltips/src/elements/Tooltip.spec.js

This PR deprecates the `TooltipContainer` component and migrates `Tooltip` to the `useTooltip()` hook.
Since this component didn't provide `onStateChange` from its propTypes we can remove the `ControlledComponent` usage and use the hook directly.
Also, I have not upgraded to the `v1` release of `react-popper` to avoid refactoring the existing `TooltipContainer`.
When we migrate to CSS-in-JS we can bump that dependency and remove the weird wrapping `<div>` around the tooltip in a breaking change.
component

feat(tooltips): deprecate TooltipContainer and migrate to useTooltip

---

packages/datepickers/package.json
packages/dropdowns/package.json
packages/dropdowns/src/Dropdown/Dropdown.tsx
packages/dropdowns/src/Fields/Label.tsx
packages/forms/package.json
packages/pagination/package.json
packages/pagination/src/containers/PaginationContainer.example.md
packages/pagination/src/containers/PaginationContainer.js
packages/pagination/src/elements/Pagination.js
packages/pagination/src/elements/Pagination.spec.js
packages/tabs/package.json
packages/tooltips/package.json
utils/build/declarations.d.ts

This PR deprecates the `PaginationContainer` component and migrates usage to the `PaginationContainer` from `container-pagination`.
This PR also updates all `container-*` packages across the repo. 
Closes #436 
component

feat(pagination): deprecate PaginationContainer and migrate to container-pagination

---

packages/autocomplete/package.json
packages/menus/package.json
packages/modals/package.json
packages/modals/src/containers/FocusJailContainer.example.md
packages/modals/src/containers/FocusJailContainer.js
packages/modals/src/containers/ModalContainer.example.md
packages/modals/src/containers/ModalContainer.js
packages/modals/src/elements/Modal.js
packages/select/package.json

This PR deprecates the `FocusJailContainer` and `ModalContainer` found within `react-modals`.
No breaking changes.
component

feat(modals): deprecate FocusJailContainer and ModalContainer

---

packages/modals/src/elements/Modal.js
packages/modals/src/index.spec.js
packages/modals/src/utils/useCombinedRefs.js
packages/modals/src/utils/useCombinedRefs.spec.js

Consumers of Modal may sometimes need to focus the modal element, this PR adds that functionality.
A custom hook that combines multiple refs into a single, valid ref. This allows us to use `React.forwardRef` while also sharing a ref with custom hooks, like `useModal` which requires a modal ref.
component

fix(modals): allow Modal to receive ref prop

---

packages/autocomplete/package.json
packages/buttons/package.json
packages/buttons/src/containers/ButtonGroupContainer.example.md
packages/buttons/src/containers/ButtonGroupContainer.js
packages/buttons/src/elements/ButtonGroup.js
packages/buttons/src/elements/ButtonGroup.spec.js
packages/menus/package.json
packages/tabs/package.json

This PR deprecates the `ButtonGroupContainer` component within `react-buttons`.
In this deprecating I opted to mimic the `onStateChange` callback rather than use the `ControlledComponent` from `react-selection`. Since there was only one value being provided this ended up being simpler.
component

feat(buttons): deprecate ButtonGroupContainer

---

packages/chrome/package.json
packages/chrome/src/containers/AccordionContainer.example.md
packages/chrome/src/containers/AccordionContainer.js
packages/chrome/src/views/subnav/CollapsibleSubNavItem.js

This PR deprecates the `AccordionContainer` component and replaces it's usage with the `useAccordion` hook.
component

feat(chrome): deprecate AccordionContainer

---

packages/avatars/package.json

Pull the fix forward from https://github.com/zendeskgarden/css-components/pull/238.
component

fix(avatars): prevent badge `content-box` sizing overrides

---

package.json
yarn.lock

The recent upgrade of `react-docgen-typescript` in #470 caused a silent 'build failure in the styleguidist docs for all TypeScript packages (dropdowns and datepickers).
The format returned is valid for the most recent version of `react-styleguidist`, but we are still unable to upgrade due to IE11 compatibility issues.
Let's sit tight on this upgrade until we can figure out how to get the build to pass.
component

fix(build): revert react-docgen-typescript upgrade

---

packages/modals/package.json
packages/modals/src/elements/Modal.spec.js
packages/modals/src/views/Close.js
packages/pagination/package.json
packages/pagination/src/elements/Pagination.spec.js
packages/tables/package.json
packages/tables/src/views/OverflowButton.js
packages/tables/src/views/Row.js
packages/tags/package.json
packages/tags/src/views/Close.example.md
utils/build/declarations.d.ts

In preparation for the `react-selection` deprecation I've migrated all usage of `KEY_CODES` and `composeEventHandlers` in non-container and non-deprecated packages to `@zendeskgarden/container-utilities`.
Some of these only occurred in the examples so they have been added as `devDependencies`.
The remaining exports in `react-selection` will need to handled during the final merges before we cut v7.
component

chore(selection): remove usages of react-selection KEY_CODES and composeEventHandlers

---

packages/loaders/README.md
packages/loaders/src/Progress.example.md
packages/loaders/src/Progress.js
packages/loaders/src/Progress.spec.js
packages/loaders/src/index.js

Introduces a new progress component.
component

feat(loaders): introduce Progress component

---

packages/forms/src/fields/other/MediaInput.js

The current `MediaInput` component has a bug where the `ref` prop assumes all refs are in the older, `(ref) => void` callback form. This fails if a modern `RefObject<any>` is provided. i.e. by the `DatepickerRange.Start` component
To allow all valid types of refs I have refactored this component to use the `useCombinedRef` hook provided in `@zendeskgarden/container-utilities`. Manually testing shows this working with the `DatepickerRange` component.
component

fix(forms): allow MediaInput to receive all possible ref values

---

packages/datepickers/src/DatepickerRange/utils/datepicker-range-reducer.ts
packages/datepickers/src/styled/styled-datepicker.tsx

There is currently a bug where the `DatepickerRange` doesn't persist values correctly if certain inputs are not `blurred` before a mouse interaction.
This PR corrects the issue above by updating the blurred state if either the start or end input receives focus.
I have also updated a visual bug where the selected day was receiving the `bold` font weight instead of `semi-bold`
component

fix(datepicker): ensure mouse events are propogated correctly

---

packages/buttons/package.json
packages/chrome/package.json
packages/forms/package.json

This PR upgrades `container-keyboardfocus` to allow event composition to work correctly.
component

chore(internal): upgrade @zendeskgarden/container-keyboardfocus

---

README.md
demo/index.html
packages/buttons/package.json
packages/chrome/package.json
packages/modals/package.json
packages/pagination/package.json
packages/pagination/src/elements/Pagination.example.md
packages/pagination/src/elements/Pagination.js
packages/pagination/src/elements/Pagination.spec.js
packages/selection/src/index.js
packages/tabs/package.json
packages/tabs/src/elements/Tabs.example.md
packages/tabs/src/elements/Tabs.js
packages/tabs/src/elements/Tabs.spec.js
packages/tooltips/package.json
utils/styleguide/styleguide.base.config.js

This PR removes all `react-selection` usages in our components and adds a deprecation warning to the default export of the package.
Breaking changes below.
Due to us deprecating the `ControlledComponent` utility we added breaking changes to 2 packages:
* `react-pagination`
* The `focusedKey` prop is no longer valid. The focused state cannot be controlled.
* The `onStateChange` prop is no longer valid. Use the `onChange` prop to receive `currentPage` updates.
* `react-tabs`
* The `selectedKey` prop has been renamed to `selectedItem`
* All `<TabPanel>`'s now require an `item` prop instead of a `key` prop
* The `onStateChange` prop is no longer valid. Use the `onChange` prop to receive `selectedItem` updates.
component

chore(internal): deprecated react-selection and migrate Tabs and Pagination components BREAKING

---

packages/datepickers/package.json
packages/dropdowns/package.json
packages/tooltips/package.json
packages/tooltips/src/elements/Tooltip.js

This PR upgrades all `react-popper` dependencies across the packages.
Because `Tooltip` is always rendering it's content in the DOM, and hiding it with `aria-hidden`, there was a noticeable flash of positioning whenever the tooltip became visible.
To help mitigate this flash I have added a quick `10ms` fade transition to the tooltip. This is fast enough to not be noticeable, but removes the initial flash of positioning. Please let me know if you know of a better strategy here.
component

chore(internal): update react-popper dependencies

---

packages/.template/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/datepickers/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/selection/package.json
packages/tables/package.json
packages/tables/src/examples/paginated-table.md
packages/tabs/package.json
packages/tabs/src/elements/Tabs.spec.js
packages/tags/package.json
packages/tooltips/package.json
packages/typography/package.json

This PR adds a new `v7` dependency range for `@zendeskgarden/react-theming` to all packages.
I've also bumped a few unrelated `container` dependencies to get everything up to latest
component

chore(deps): upgrade react-theming peerDependencies to allow v7

---

packages/buttons/src/views/Button.js

In recent version of `styled-components` the `attrs` method overrides all props that are provided. This has lead to the `Button` component being unable to change it's default `[type="button"]` attribute.
This PR adds a prop check to this logic.
component

fix(buttons): allow buttons to control type attribute

---

packages/buttons/src/views/Button.js

This is a v6 backport for the button type bug fixed in #498 
component

fix(buttons): allow buttons to control type attribute (#498) [BACKPORT v6]

---

.gitignore
packages/buttons/src/views/Anchor.js
packages/buttons/src/views/Anchor.spec.js

`<a>` elements are unable to have a `disabled` state semantically. This PR removes the `disabled` prop for the `Anchor` element to align with the spec.
component~

fix(buttons): remove invalid disabled prop from Anchor

---

.gitignore
packages/dropdowns/examples/menu.md

There have been some style specificity changes in the `Advanced Usage` example in the dropdowns package. The example had become unaligned for several menu items.
Since the custom visualizations shown aren't visible in any product usages I have removed the examples menu items instead of increasing the specificity.
Now that we are using netlify for our local publishes in the `next` branch. I have added a `.netlify` rule to our gitignore.
component~

chore(docs): remove invalid advanced dropdown example

---

.gitignore
packages/datepickers/package.json
packages/datepickers/src/Datepicker/Datepicker.tsx
packages/datepickers/src/styled/styled-menu.spec.tsx
packages/datepickers/src/styled/styled-menu.tsx

This PR removes the invalid `arrow` prop available on the `Datepicker` component. 
This prop was erroneously added while mimicking the `Dropdown` API. Since no arrow is intended in its usage lets remove it rather than add the functionality at this time.
component

chore(datepicker): remove invalid arrow prop

---

packages/dropdowns/src/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/Multiselect/Multiselect.tsx

When originally implementing the `react-dropdowns` package we neglected to include some common `forwardRef` implementations to allow users to programmatically focus the containing `<div>` and `<input />` of the Multiselect and Autocomplete components.
This PR uses the `useCombinedRefs` utility to surface two changes:
- Both `Autocomplete` and `Multiselect` now allow the `ref` prop to return the containing `<div>` of the element.
- This could allow unique positioning logic
- Both `Autocomplete` and `Multiselect` now provide an `inputRef` object which can receive a ref callback or `RefObject`
- This would allow consumers to focus the internal input with custom logic
component~

feat(dropdowns): add inputRef prop to Autocomplete and Multiselect

---

packages/dropdowns/src/Menu/Menu.tsx

By default the `Menu` component matches the width of the `Select` element which triggers it. In some use-cases the width of the `Select` can be dramatically smaller than a default width of a `Menu`.
This PR allows inline width overrides to take precedence over the width of the paired `Select`.
```jsx
<Menu style={{ width: 500 }}>
// Renders at 500px width
</Menu>
```
component~

fix(dropdowns): allow inline style to override Menu width

---

packages/datepickers/src/Datepicker/Datepicker.tsx
packages/dropdowns/src/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/Multiselect/Multiselect.tsx
packages/dropdowns/src/Select/Select.tsx

A recent release of `react-popper` has updated it's TS definitions and is currently breaking the build. They have enabled `RefObject` support for their render-props which has caused some ambiguity in the types. I have added some `any` casts for now.
This update was able to break our build due to the fact that we don't persist `yarn.lock` files within each of the `packages/*` directories. This seems like lerna best practice, but we should keep an eye on this to see if it keeps causing issues.
component~

fix(build): correct TS usages of react-popper

---

packages/forms/src/fields/MultiThumbRange.js
packages/forms/src/fields/MultiThumbRange.spec.js

The current `MultiThumbRange` in `react-forms` is using an invalid property to determine range position based on mouse drag actions.
The original implementation was using the [invalid x property](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) which is only supported in a subset of browsers.
This PR moves it to the `left` property which is supported in all of our browsers.
component~

fix(forms): allow MultiThumbRange to position correctly in Edge and IE11

---

bundlesize.config.js
packages/datepickers/package.json
packages/datepickers/src/Datepicker/Datepicker.spec.tsx
packages/datepickers/src/Datepicker/Datepicker.tsx
packages/datepickers/src/Datepicker/utils/datepicker-reducer.ts

The `Datepicker` component can run into issues when the controlled `value` prop is changed without Calendar interaction.
Our use of an effect hook to trigger the `onChange` callback is flawed and can create conditions where a `CONTROLLED_VALUE_CHANGE` reducer event doesn't update all values.
This PR updates the logic of how the `onChange` callback is triggered.
component~

fix(datepickers): allow controlled value to update internal state

---

packages/tags/examples/advanced.md
packages/tags/examples/basic.md

The `react-tags` example is logging a React warning because the `<Toggle>` examples start off as uncontrolled component — and then switches to a controlled component when users toggle the element.
The resolve this issue, I declared default state values for the `<Toggle>`s checked value. This causes the components to be a controlled component for the duration of their lifecycle and the React warning goes away.
**Before**: `<Toggle>` begins as uncontrolled component then switches to controlled. React warns.
**After**: `<Toggle>` begins as controlled component and remain so for the duration of its lifecycle. There is no React warning.
~- [ ] :ok_hand: design updates are Garden Designer approved (add the
~- [ ] :nail_care: view component styling is based on a Garden …

fix(tags): use controlled components in tags example

---

packages/tabs/src/elements/Tab.spec.tsx
packages/tabs/src/elements/Tab.tsx
packages/tabs/src/elements/TabList.spec.tsx
packages/tabs/src/elements/TabList.tsx
packages/tabs/src/elements/TabPanel.spec.tsx
packages/tabs/src/elements/TabPanel.tsx
packages/tabs/src/elements/Tabs.spec.tsx
packages/tabs/src/elements/Tabs.tsx
packages/tabs/src/index.ts
utils/styleguide/TableOfContentsRenderer/index.js

While migrating `react-tabs` to TypeScript I forgot to include `forwardRef` usages for our high-level exports.
This PR adds `forwardRef` usages.
TypeScript and styleguidist seem to fall apart when using `default` exports and `forwardRef` usages. This can be corrected by using a named export so I have moved our non-`withTheme` usages.
component~

fix(tabs): allow forwardRef usages

---

packages/forms/src/elements/MultiThumbRange.js
packages/forms/src/elements/MultiThumbRange.spec.js

This PR is a cherry-pick of #516 onto the `next` branch.

fix(forms): allow MultiThumbRange to position correctly in Edge and IE11 (#516 backport)

---

packages/tabs/examples/default-tabs.md

React Styleguidest updates to global state is causing the toggles to lose focus. This causes the `activeElement` to lose focus on state changes. To solve this problem, I used the global `<State>` to encapsulate the example state so the toggles do not lose focus.
**Before:** User focuses on the toggle component and presses the `space` key twice. The first press triggers the toggle. The second key press scrolls the user to the bottom of the page:
**After:** User focuses on the toggle component and presses the `space` key multiple times. The key presses trigger the toggle back and forth, without scrolling the user to the bottom of the page:
~- [ ] :ok_hand: design updates are Garden Designer approved (add the
~- [ ] :nail_care: view component styling is based on a …

fix(tabs): use state helper to avoid example re-rendering

---

packages/modals/src/elements/Modal.js
packages/modals/src/elements/Modal.spec.js

Being able to define the portal container would allow us to render the modal into a shadow root element.
component

Allow the portal container to be passed in as a prop

---

packages/breadcrumbs/package.json
packages/breadcrumbs/src/elements/Breadcrumb.spec.tsx
packages/breadcrumbs/src/elements/Breadcrumb.tsx
packages/breadcrumbs/src/styled/StyledBreadcrumb.spec.tsx
packages/breadcrumbs/src/styled/StyledBreadcrumb.ts
packages/breadcrumbs/src/styled/StyledBreadcrumbItem.spec.tsx
packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts
packages/breadcrumbs/src/styled/StyledCenteredBreadcrumbItem.tsx
packages/breadcrumbs/src/styled/StyledChevronIcon.tsx
packages/breadcrumbs/src/styled/index.ts

This pull request refactors CSS to JS.
Breadcrumbs has been updated to use 12x12 chevron stroke icons from svg-icons. For a **visual check**, a review link for the breadcrumb package Storybook is published [**here**](https://gallant-blackwell-63466f.netlify.com/breadcrumbs/).
~- [ ] :nail_care: view component styling is based on a Garden CSS
component~

feat(breadcrumbs): CSS-in-JS Refactor

---

.gitignore
packages/autocomplete/src/containers/AutocompleteContainer.js
packages/buttons/src/containers/ButtonGroupContainer.js
packages/chrome/src/containers/AccordionContainer.js
packages/datepickers/src/Datepicker/Datepicker.tsx
packages/dropdowns/src/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/Multiselect/Multiselect.tsx
packages/dropdowns/src/Select/Select.tsx
packages/menus/src/containers/MenuContainer.js
packages/modals/src/containers/ModalContainer.js
packages/pagination/src/containers/PaginationContainer.js
packages/select/src/containers/SelectContainer.js
packages/selection/src/containers/FieldContainer.js
packages/selection/src/containers/SelectionContainer.js
packages/tabs/src/containers/TabsContainer.js
packages/tooltips/src/containers/TooltipContainer.js

`v6 backport`
In codebases which use a combination of `v6` and `v7` components, it is possible to have conflicting IDs between components. This breaks the UX and accessibility.
The most notable instance is with `react-selection/FieldContainer` and the `useField()` hook. These utilities used the same global ID prefix which led to duplicate ID's when used together.
To stop this from occurring I have added a `-deprecated` suffix to all IdManager usages in the deprecated container packages.
component~

fix(all): update ID prefixes to reflect deprecated status

---

packages/tags/src/styled/StyledTag.spec.tsx
packages/tags/src/styled/StyledTag.ts

Replacing a couple of places where I was incorrectly accessing foreground/background via `getColor`. That function is used to resolve hues/shades. The foreground/background colors should be taken directly from the theme.
component~

fix: access foreground/background directly via theme

---

packages/datepickers/src/styled/StyledHeaderPaddle.ts

Now that the theme has `iconSizes`, these are the values that should be used for component SVG dimensions.
component~

fix: update to use theme `iconSizes.md` for paddle SVGs

---

.travis.yml
lerna.json
package.json
utils/scripts/version-next.sh

This PR enables the ability to release `preMajor` versions in the `next` branch. It will force all packages to be deployed under the `next` tag in NPM.

chore(build): allow preMajors from next branch

---

packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts
packages/buttons/package.json
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/styled/StyledIconButton.ts
packages/chrome/src/styled/body/StyledContent.tsx
packages/chrome/src/styled/header/StyledBaseHeaderItem.ts
packages/chrome/src/styled/nav/StyledNavItemText.ts
packages/chrome/src/styled/subnav/StyledSubNavItemText.ts
packages/loaders/package.json
packages/loaders/src/styled/StyledSkeleton.ts
packages/tags/src/styled/StyledTag.ts

- swap out various `line-height` calculations with `getLineHeight` from theming
- fix button heights at various zoom levels
@ginnywood the components that got touched by this PR include:
- breadcrumb
- portions of chrome
- loaders
- tags
which are all 1:1 swaps. But the most important for visual review would be the fixes for buttons, which can be seen here: https://silly-haibt-18bd35.netlify.com/buttons/
component~

chore: use `getLineHeight` utility

---

packages/buttons/src/styled/StyledIconButton.spec.tsx
packages/buttons/src/styled/StyledIconButton.ts

Design changes requested by @ginnywood.
component~

fix(buttons): default `IconButton` foreground to neutral hue

---

.eslintrc.json
package.json
packages/breadcrumbs/src/styled/StyledBreadcrumb.ts
packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts
packages/breadcrumbs/src/styled/StyledCenteredBreadcrumbItem.tsx
packages/modals/src/views/Body.js
packages/modals/src/views/Close.js
packages/modals/src/views/Footer.js
packages/modals/src/views/FooterItem.js
packages/modals/src/views/Header.js
packages/modals/src/views/ModalView.js
packages/pagination/src/views/Gap.js
packages/pagination/src/views/NextPage.js
packages/pagination/src/views/Page.js
packages/pagination/src/views/PaginationView.js
packages/pagination/src/views/PreviousPage.js
utils/eslint/index.js
utils/eslint/package.json
utils/eslint/rules/require-default-theme.js
yarn.lock

This PR introduces a local ESLINT rule that requires all `styled` usages to have a `DEFAULT_THEME` provided via `defaultProps`.
It turns out adding a local ESLINT rule is actually pretty crazy. I had to:
- Create a local, private package within our `utils` package
- Add it to our `node_modules` path via a relative path in the `package.json`
- Enable it like a standard rule under the `garden-local` rule naming
The `garden-local/require-default-theme` rule ensures that all styled `TaggedTemplateExpression`s include a `defaultProp` of `theme`. This is able to work across both TS and JS files.
I tried to get the "suggested fix" syntax working within VS Code, but it doesn't seem to be working locally for me.
component~

chore(lint): create styled-component default theme eslint rule

---

BREAKING_CHANGES.md
packages/chrome/examples/basic.md
packages/chrome/src/elements/Chrome.spec.tsx
packages/chrome/src/elements/Chrome.tsx
packages/chrome/src/elements/nav/Nav.spec.tsx
packages/chrome/src/elements/nav/Nav.tsx
packages/chrome/src/elements/nav/NavItem.tsx
packages/chrome/src/elements/subnav/SubNav.tsx
packages/chrome/src/elements/subnav/SubNavItem.tsx
packages/chrome/src/index.ts
packages/chrome/src/styled/index.ts
packages/chrome/src/styled/nav/StyledLogoNavItem.ts
packages/chrome/src/styled/nav/StyledNav.ts
packages/chrome/src/styled/nav/StyledNavItem.ts
packages/chrome/src/styled/subnav/StyledSubNav.ts
packages/chrome/src/styled/subnav/StyledSubNavItem.tsx
packages/chrome/src/utils/useChromeContext.ts

The `hue` prop is used to alter `Nav` and `SubNav` color treatments.
Additionally, this PR includes opacity fixes for navigation hover/focus states.
Demo is pre-published for review: https://vigorous-davinci-819228.netlify.com/chrome/
component~

feat(chrome): replace background color with `hue` prop

---

packages/tooltips/src/elements/Paragraph.tsx
packages/tooltips/src/styled/StyledParagraph.ts

In the Notifications, CSS-in-JS migration,  the `p` tag was used instead of a `div` for `<Paragraph>` to [improve semantics](https://github.com/zendeskgarden/react-components/pull/563#discussion_r364009950). 
This PR refactors the `StyledParagraph` in the Tooltips package to use a more semantic `<p>`. There should be no visual difference from before.

fix(tooltips): use semantic tag for paragraph element

---

packages/tooltips/src/elements/Tooltip.js

@agoodno found some performance issues when a large amount of `Tooltip` components are being rendered. I was able to reproduce a noticeable slowdown in the initial render with approx. 500 tooltips.
To correct this issue I tweaked our PopperJS logic by:
* Disabling the `eventsEnabled` listener if the tooltip is not visible.
* This aligns with the logic in `react-dropdowns`
* I have also removed the initial `ref` assignment from `Popper` is the tooltip is not visible
* Even with `eventsEnabled` turned off the initial positioning performed by popper was causing a large slowdown
* By delaying the `ref` assignment this greatly reduces the initial render time
https://github.com/popperjs/react-popper/issues/185 has some additional performance implications if we keep seeing an issue
I don't …

fix(tooltips): improve tooltip rendering performance

---

packages/modals/package.json
packages/modals/src/elements/Modal.js

Focusable elements in modals package examples persist their focused states causing the UI to show that multiple elements are focused after a user tabs through elements.
It looks like the cause of this problem is because the modals' children are rendered within a portal, rather than the root node. To fix this issue I updated the modal component to pass the `modalRef` into `useFocusVisible`.
Here is a [demo](https://blissful-babbage-396374.netlify.com/modals/) of the fixed example.
**BEFORE:**
**AFTER:**
component

fix(modals): use focusvisible in Modal component

---

packages/forms/examples/basic.md
packages/tooltips/examples/basic.md
packages/tooltips/src/styled/StyledTooltip.ts
utils/styleguide/setup.js

With updated `styled-components` the `global.Row` attrs override is hostile as `alignItems` cannot be modified via props.
While updating the tooltips demo, I discovered that the `text-align` styling on a parent can have unintended consequences for tooltip styling. A CSS property was added to correct that issue.
component~

fix(demo): remove global.Row `alignItems` attrs override.

---

packages/datepickers/examples/compact.md

Updated `Input` with correct `isCompact` (vs `small`) prop.

fix(datepickers): compact example

---

packages/forms/package.json
packages/forms/src/styled/common/StyledHint.ts
packages/forms/src/styled/common/StyledLabel.ts
packages/forms/src/styled/common/StyledMessage.ts
packages/forms/src/styled/text/StyledTextInput.ts

swap out various `line-height` calculations with `getLineHeight` from theming
component~

chore(forms): use `getLineHeight` utility

---

packages/pagination/src/elements/Pagination.spec.js

Somehow a test in our `Pagination` suite has began failing. I'm not sure if this is a nested dependency upgrading our JSDom version or something in `container-pagination`, but our historical builds have all passed.
I've updated the `Pagination` test suite to more accurately test the functionality of the `Previous` and `Next` actions.
component~

fix(build): correct failing tests

---

packages/dropdowns/examples/multiselect.md
packages/dropdowns/src/styled/field/StyledMultiselect.tsx

We currently wrap multiselect items in a div that doesn't have overflow hidden, that makes it impossible to do text truncation. 
Before:
After:

fix(dropdowns): overflow in Multiselect items

---

packages/dropdowns/src/Dropdown/Dropdown.tsx
packages/dropdowns/src/Menu/Menu.tsx

Garden `react-dropdowns` components are sporadically force-closing some versions of Chrome browsers in Android. This isn't consistent by to Android version, device, or chrome version.
Running LogCat with ADB shows a segmentation fault where Chromium is attempting to modify GPU thresholds for specific devices.
The only GPU intensive operations with `react-dropdowns` is the `translate(...)` operations done by PopperJS when the menu is positioned. These operations are consistent across all `<Menu>` usages so I'm not sure why it's only affecting `Select`, `Autocomplete`, and `Multiselect` components.
To fix the issue I have removed the Popper computation reference while the menu is closed. This disables `react-popper` and seems to fix the issue across the problem browsers.
I attempted to …

fix(dropdowns): limit PopperJS computations while dropdowns are closed

---

packages/dropdowns/src/Menu/Items/Item.spec.tsx
packages/dropdowns/src/Menu/Items/NextItem.spec.tsx
packages/dropdowns/src/Menu/Items/PreviousItem.spec.tsx
packages/dropdowns/src/Menu/Menu.tsx

We are continuing to see rendering issues in specific Pixel devices similar to #613 
This PR corrects our conditional ref placement and now conditionally renders menu items.
component

fix(dropdowns): conditionally render menu items to correct android rendering

---

packages/modals/package.json
packages/modals/src/styled/StyledClose.ts
packages/modals/src/styled/index.ts

Update the modal close button to match icon buttons.
Icon button states have been updated to use opacities for hover and active states. The "X" close button on a modal needs to be styled to match regular icon buttons.
https://henry-next.netlify.com/modals#basic (Updated as of 2/6/2020).
~- [ ] :guardsman: includes new unit tests~

feat(modals): Update the modal close button style

---

packages/theming/src/index.ts

This PR adds a deprecated alias for `retrieveComponentStyles` (`retrieveTheme`). This alias will allow v7 components to consume `react-theming@v8`.
I have not added a deprecation warning in this release as it would be called on every render of every component. We should add this in once products have been given time to migrate.
component

feat(theming): add retrieveTheme alias for v7 consumers

---

packages/loaders/src/Dots.js
packages/loaders/src/Dots.spec.js

In Lotus, we are seeing repeated renders of `Dots` even though they do not have any props that have changed.
This is because `useSchedule` is continuously rescheduling as `loop`'s default is `true`, and causing rerenders.
Since Dots only needs rerender when `noAnimatedSVGSupport` is true, we will set `loop` based on this value.
component

perf(loaders): prevent rerender for dots

---

packages/tags/examples/advanced.md
packages/tags/examples/basic.md
packages/tags/src/styled/StyledTag.ts

`border-box` sizing provides a more reliable layout for when a `Tag` is meant to be a child of another Garden container (`Multiselect`, for example).
Also:
- reduce `math` calculations
- prevent "Advanced" example from squishing tags
- fix `justify-content` bug on pill tags
- use a `1ch` min-width for default tag content

fix(tags): utilize `border-box` box sizing model

---

packages/dropdowns/src/Select/Select.tsx
packages/dropdowns/src/index.ts

The `Select` component is currently unable to accept a `ref` attribute to allow consumers access to the wrapping DOM element.
This PR adds the `forwardRef` API to this component. We were already forwarding ref's for other elements in this package.
We have already began updating this package structure in the `next` branch so this should already be resolved in #610 
component~

fix(dropdowns): allow forwardRef usage of Select component

---

BREAKING_CHANGES.md
README.md
demo/index.html
packages/buttons/package.json
packages/buttons/src/elements/Button.tsx
packages/buttons/src/elements/ButtonGroup.spec.tsx
packages/buttons/src/elements/ButtonGroup.tsx
packages/buttons/src/elements/IconButton.tsx
packages/buttons/src/elements/SplitButton.tsx
packages/buttons/src/utils/useButtonGroupContext.ts
packages/buttons/src/utils/useSplitButtonContext.ts
packages/utilities/README.md
packages/utilities/src/index.js

This PR deprecates `@zendeskgarden/conatiner-utilities` and includes a new warning message for consumers that consume it. We should be able to remove this package during `v9` to allow people to upgrade.
The only package where these utilities were in `react-buttons`. Specifically the `ButtonGroup` component.  This component was still using our legacy `Children.map()` approach to applying nested props.
To remove this dependency I migrated the components to use custom context hooks to consume these prop-getters. The `ButtonGroup` can now support nesting and `styled(Button)` usages.
component~

feat(buttons): remove react-utilities dependency and deprecate package

---

packages/notifications/examples/basic.md
packages/notifications/src/elements/Alert.spec.tsx
packages/notifications/src/elements/Notification.spec.tsx
packages/notifications/src/styled/StyledAlert.ts
packages/notifications/src/styled/StyledNotification.ts

This pull request adds `role="alert"` to the `Alert`component and the `role="status"` to the `Notification` component.
Recently, there was a report that `Alert` component content was not read aloud by screen readers. It required consumers to manually add a `role="alert"` to the underlying HTML element. This PR aims to bake in `role="alert"` and `role="status"` as a reasonable defaults.
The demo for this branch can be found here: https://happy-hugle-9a77f5.netlify.com/notifications
**Before:**
1) Navigate to the [published demo](https://henry-next.netlify.com/notifications/#basic) for `next`.
2) Turn on VoiceOver. 
3) Toggle between the different types of `Alert` and `Notification` components. 
4) Notice that the screen reader does not read the notification content aloud.
**After:**
1) …

fix(notifications): Add ARIA role to Notification components

---

BREAKING_CHANGES.md
packages/tooltips/examples/basic.md
packages/tooltips/src/elements/Tooltip.tsx

This PR renames the `<Tooltip>` `delayMilliseconds` prop to `delayMS` and aligns it with other packages.
component~

fix(tooltip): rename delayMilliseconds prop to delayMS

---

packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/datepickers/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/loaders/package.json
packages/modals/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/tooltips/package.json

This change ensures that all Garden packages are supported in IE11. By bumping all `container-*` packages to their most recent patch consumers won't have to compile any `node_module`s.
This has been manually tested in IE11.
component

fix(deps): ensure all garden container packages support ie11

---

BREAKING_CHANGES.md
packages/dropdowns/.size-snapshot.json
packages/dropdowns/examples/advanced-menu.md
packages/dropdowns/src/elements/Menu/Items/HeaderItem.spec.tsx
packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
packages/dropdowns/src/styled/items/header/StyledHeaderItem.ts
packages/dropdowns/src/styled/menu/StyledMenu.tsx
packages/loaders/.size-snapshot.json
packages/loaders/examples/skeleton.md
packages/loaders/src/elements/Skeleton.spec.tsx
packages/loaders/src/elements/Skeleton.tsx
packages/loaders/src/styled/StyledSkeleton.ts
packages/theming/.size-snapshot.json
packages/theming/src/utils/arrowStyles.spec.tsx
packages/theming/src/utils/arrowStyles.ts
packages/tooltips/.size-snapshot.json
packages/tooltips/src/elements/Tooltip.tsx
packages/tooltips/src/styled/StyledTooltip.ts

- (dropdowns) menu `HeaderItem` containsIcon -> hasIcon
- (loaders) `Skeleton` isDark -> isLight
- (tooltips) initialIsVisible -> isInitialVisible
- (theming) reverse semantics for `arrowStyles` inset parameter
Updated demo: https://competent-shirley-cc2f82.netlify.com/
component~

chore: prop renames for API consistency

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Menu/Menu.spec.tsx
packages/dropdowns/src/styled/menu/StyledMenu.tsx

Our current `Dropdown` animations can experience some shifting/jank depending on placement, animation, arrow props, and browser type. Our current version of PopperJS (v1) is having trouble computing our current margin transitions.
This PR moves the `margin-*` animations to `translate*()` to allow PopperJS to compute the positioning correctly.
The `translate*` animations were able to be carried over easily, but there was some complications with our existing arrow styles. Using `transform` on the `Menu` element created a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). This caused the existing arrow styles to not be positioned correctly on the z-axis with it's parent Menu.
I attempted several workarounds …

fix(dropdowns): update animation to use translate instead of margin

---

lerna.json
packages/datepickers/package.json

While preparing for the v8 release I noticed that our `v6` support branch doesn't publish under a non-`latest` NPM dist tag.
I've updated the lerna config to ensure that any `v6` publish no longer wipes out the `@latest` package version.

fix(build): allow lerna to publish under non-latest tag

---

packages/.template/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/datepickers/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/selection/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/tooltips/package.json
packages/typography/package.json

This PR allows all `v7` packages to consume the new `react-theming@v8` packages as a valid peer dependency.

feat(build): allow all packages to consume v8 theming

---

demo/index.html

During the v8 release we forgot to link to the v7 documentation for consumers during the migration period. I've hosted a v7 docs site at https://garden-v7.netlify.com/ temporarily.
This PR adds a link to the react-components homepage.
I'm not sure what is the best copy/placement for this link so please throw any ideas in.

chore(docs): add link to v7 docs

---

demo/index.html

This PR adds a link to the v6 docs for consumers that haven't upgraded to the newer versions of Garden yet.

chore(docs): add link to v6 documentation

---

demo/index.html

Now that Netlify is resolving https://garden-v7.netlify.com/ correctly I've updated the v7 documentation link.

chore(docs): update v7 documentation link

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/Datepicker/Datepicker.tsx
packages/datepickers/src/styled/StyledMenu.tsx

When updating the `Dropdown` animation in #634 I neglected to apply the same treatment to `Datepicker`. This PR aligns the menu animation strategy between the two packages.

fix(datepickers): ensure animation is positioned correctly

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx

Removed `aria-labelledby` values provided by Downshift for `Dropdown` `Trigger` that don't make sense for menus.

fix(dropdowns): remove invalid aria-labelledby value from Trigger

---

packages/modals/package.json
packages/modals/yarn.lock

This pull request updates the `react-modal` container dependencies so that modals can take advantage of the [new restore focus](https://github.com/zendeskgarden/react-containers/pull/161) feature which was added to `container-focusjail`.
The demo can be found here: https://modals-dep-update.netlify.com/modals/#examples. The keyboard focus is now restored upon closing the modal for three scenarios:
1) When a user selects the "X" close button in the top corner of the modal.
2) When a user presses the "Escape" key.
3) When a user clicks the backdrop.

chore(modals): update container dependencies

---

.github/CONTRIBUTING.md
README.md
docs/api.md
docs/development.md
docs/versioning.md
examples/codesandbox/garden-create-react-app/src/components/ExampleWrapper.js
examples/codesandbox/garden-create-react-app/src/examples/Example.js

Major updates to README and development.md along with recovering an api.md that represents current v8 architecture. Other updates are general copy/structure cleanup.
Codesandbox has updated copy along with simply using a `<Header isStandalone>` to simplify chrome applied to sandbox examples.

chore: update documentation for v8

---

packages/modals/examples/basic.md

docs(modals): include a11y note on restoring focus
This pull request adds a sentence about Garden's restoring focus capability, and potentially the need for developers to manage keyboard focus in certain circumstances.
Recently Garden's `modals` package was updated to returns focus back to the trigger element. Specifically, the `modals` package uses one of `useFocusJail`'s newest features to [return the keyboard focus](https://github.com/zendeskgarden/react-containers/blob/master/packages/focusjail/src/useFocusJail.ts#L130) back to the trigger element.

docs(modals): include a11y note on restoring focus

---

package.json
packages/typography/examples/lists.md

This pull request updates the `lint:markdown` glob patterns to include markdown files that were added in v8 under `packages/*/examples/*md`. 
* Removed the `packages/*/src/*.md` pattern because no markdown file exists under `src`.
* Updated `lists.md` which fixes markdown line length issues.

chore(markdown): include package examples in lint:markdown

---

packages/chrome/.size-snapshot.json
packages/chrome/examples/header.md
packages/chrome/src/styled/header/StyledHeader.ts
packages/chrome/src/styled/nav/StyledLogoNavItem.ts
packages/chrome/src/styled/nav/StyledNav.ts
packages/chrome/src/styled/subnav/StyledSubNav.ts

Attempts to demo `Chrome` brought out a couple of issues:
1. The box shadow for a standalone header is not displaying beyond `Main` content
1. Foreground colors not displaying correctly when nav is themed for a "dark mode"
This PR addresses both of these issues.

fix(chrome): box-shadow and color styling

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/Range.spec.tsx
packages/forms/src/elements/Range.tsx

While working on the `Steppers` demo, I noticed that the `Range` component does not render the correct background-size when used as a controlled component.
I've added `props.value` to the `useEffect` dependency array which correctly updates the background-size when a controlled value changes. I've also added a test that verifies the background-size is updated correctly when `Range` is used as a controlled component.
The following screen recordings are from a contrived example but demonstrates the fix.

fix(forms): allow controlled range to render background-size

---

.eslintrc.json
packages/forms/.size-snapshot.json
packages/forms/examples/tiles.md
packages/forms/src/elements/tiles/Tiles.spec.tsx
packages/forms/src/elements/tiles/Tiles.tsx
packages/forms/src/elements/tiles/components/Description.tsx
packages/forms/src/elements/tiles/components/Icon.tsx
packages/forms/src/elements/tiles/components/Label.tsx
packages/forms/src/elements/tiles/components/Tile.tsx
packages/forms/src/index.ts
packages/forms/src/styled/index.ts
packages/forms/src/styled/tiles/StyledTile.ts
packages/forms/src/styled/tiles/StyledTileDescription.ts
packages/forms/src/styled/tiles/StyledTileIcon.ts
packages/forms/src/styled/tiles/StyledTileInput.ts
packages/forms/src/styled/tiles/StyledTileLabel.ts
packages/forms/src/utils/useTilesContext.ts
packages/forms/styleguide.config.js

This PR introduces the new `Tiles` pattern. Semantically this is similar to a [Radio Group](https://www.w3.org/TR/wai-aria-practices/#radiobutton), but this implementation uses native `<input type="radio" />` elements rather than roving tabIndex.
Consumers can treat this as a controlled or uncontrolled input. It also allows more traditional `<form>` usages if needed.
Common usage:
```jsx
<Tiles name="form-name" onChange={...} value={...}>
<Tiles.Tile value="item-1">
<Tiles.Icon>...</Tiles.Icon>
<Tiles.Label>label</Tiles.Label>
<Tiles.Description>description</Tiles.Description>
</Tiles.Tile>
</Tiles>
```
`Tiles` are currently used in a variety of sizes and layouts with only some needing mobile-responsiveness. Rather than bake all of these layouts into the component consumers can use our …

feat(forms): introduce new Tiles component

---

packages/modals/src/elements/Modal.js

Since iframes have their own Element type, this prop will fail when using any element from an iframe for the portal destination.
Super brief stack overflow post discussing iframes having their own `Element` type https://stackoverflow.com/questions/26248599/instanceof-htmlelement-in-iframe-is-not-element-or-object

fix: Update Modal's prop type for appendToNode to be PropType.any

---

packages/modals/.size-snapshot.json
packages/modals/package.json
packages/modals/src/elements/Modal.tsx
packages/modals/yarn.lock

This PR allows consumers of `Modal` to determine whether a modal should focus on mount and restore focus when the modal is dismissed. 
The `container-modal` dependency has been updated which forwards `restoreFocus` to the `useFocusJail` hook. `<Modal>` now exposes two new props `focusOnMount` and `restoreFocus` which forwards boolean values to the underlying `useModal` and `useFocusJail` hooks.
Note: `focusOnMount` isn't a new feature, however it was never exposed to consumers as a prop.
The new props can be tested with "Edit Code" in the demo example, and providing a boolean value to the `Modal`'s `restoreFocus` or `focusOnMount` prop.
The demo can be found at: [https://modal-updated-props.netlify.com/modals/](https://modal-updated-props.netlify.com/modals/#basic)

fix(modals): include useModal args as props

---

.circleci/config.yml
demo/index.html
package.json
packages/.template/README.md
packages/accordions/README.md
packages/avatars/README.md
packages/avatars/examples/advanced.md
packages/breadcrumbs/README.md
packages/buttons/README.md
packages/chrome/README.md
packages/datepickers/README.md
packages/dropdowns/README.md
packages/forms/README.md
packages/grid/README.md
packages/loaders/README.md
packages/modals/README.md
packages/notifications/README.md
packages/pagination/README.md
packages/tables/README.md
packages/tabs/README.md
packages/tags/README.md
packages/theming/README.md
packages/tooltips/README.md
packages/typography/README.md
packages/utilities/README.md
renovate.json
utils/scripts/gh-pages.js
yarn.lock

Fixes the following:
- Need to `git config` user name and email for successful `gh-pages` deploy
- Invalid `accordions` href on demo index page
- Revert `react-docgen-typescript` (and ignore with Renovate) to fix this Styleguidist error:
> <img width="567" alt="Screen Shot 2020-03-11 at 6 17 53 PM" src="https://user-images.githubusercontent.com/143773/76480627-87244200-63cc-11ea-9743-6b4d9b2109b6.png">
- Revert package README title badges to fix this error:
> <img width="814" alt="Screen Shot 2020-03-11 at 6 18 10 PM" src="https://user-images.githubusercontent.com/143773/76480647-9a371200-63cc-11ea-9add-f0c49d64c03f.png">
- Chrome `isRound` prop in `avatars` example
Error: https://app.circleci.com/pipelines/github/zendeskgarden/react-components/69/workflows/02769243-baa5-4795-b90a-778a8ff4 …

chore: fix CircleCI deploy

---

packages/theming/.size-snapshot.json
packages/theming/README.md
packages/theming/package.json
packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
packages/theming/src/elements/palette/index.ts

This one slipped through the cracks on `next` between #381 and zendeskgarden/css-components#240.
`#e7afa2`

feat(theming): add gather product color

---

packages/theming/src/utils/getColor.ts
utils/build/styled.d.ts

Closes #677 
This PR removes the `Hue` export from our local `styled-components` `Theme` definitions. This requires all `Hue` usages within the packages to use a local type that fits the same definition.
So far `Hue` is only used with the `getColor` utility.

fix(theming): remove Hue usage to allow TS projects to build

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/tiles/StyledTile.ts
packages/forms/src/styled/tiles/StyledTileIcon.ts
packages/forms/src/styled/tiles/StyledTileLabel.ts

This PR updates the following styles in the `Tiles` component:
The label component now wraps in the same way that the description does.
The icon, label, and description colors have been tweaked to no longer look like secondary text.
Updated documentation https://austin-next.netlify.com/forms/#tiles

fix(tiles): update Tiles label wrapping and Icon colors

---

utils/scripts/version.sh

A few version script changes to improve `yarn run tag`:
- Prune invalid local tags
- Edit temp changelog as a markdown file
- Use conventional format for the changelog commit

chore: sync local tags with remote

---

packages/tags/.size-snapshot.json
packages/tags/examples/advanced.md
packages/tags/examples/basic.md
packages/tags/src/elements/Tag.tsx
packages/tags/src/styled/StyledTag.ts

Update the `hue` prop type so that it can receive any valid Garden hue beyond fixed primary and secondary palette values. Also fix foreground/background color selection which would break if a "dark" theme was applied.
Pre-published for review with advanced `Hue` control: https://amazing-poincare.netlify.com/tags/#advanced

feat(tags): allow flexible tag hue

---

.circleci/config.yml
package.json

Knock out `dir:` config.
https://circleci.com/orbs/registry/orb/circleci/node#commands-with-cache
**Restoring a cache that isn't needed because `yarn` is provided by the orb**
**No cache hit on install**
**Smaller node_modules restore**
**Zero time spent on install**

fix: use default CircleCI node_modules cache

---

packages/dropdowns/src/Menu/Menu.tsx

Implements a check in the dropdowns `Menu` component to conditionally check `isOpen` before forwarding a ref to `Popper`.
Backport of #613 to v6.

fix(dropdowns): conditionally apply popper ref to Menu

---

packages/avatars/.size-snapshot.json
packages/avatars/examples/advanced.md
packages/avatars/examples/basic.md
packages/avatars/src/elements/Avatar.tsx
packages/avatars/src/styled/StyledAvatar.spec.tsx
packages/avatars/src/styled/StyledAvatar.ts

This PR adds a XXS avatar size for use in future `Menu` updates. Also reduce the number of expensive `math` calls while we're in here.
Pre-published to https://amazing-poincare.netlify.com/avatars/ for review

feat(avatars): add XXS avatar size

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/styled/StyledMenuWrapper.ts
packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/styled/field/StyledSelect.ts
packages/dropdowns/src/styled/menu/StyledMenuWrapper.ts
packages/forms/.size-snapshot.json
packages/forms/examples/advanced.md
packages/forms/src/styled/text/StyledTextFauxInput.ts
packages/theming/src/utils/menuStyles.example.md

This PR addresses several styling issues:
- calls to `menuStyles` failed to pass the `theme` object, preventing menus from receiving theming
- the `FauxInput` wrapped by `StyledSelect` did not have access to the current theme prop 🤷‍♂ 
- restore `vertical-align: baseline` styling for any child `Input` of `FauxInput` in order to retain expected 40px height (without this, the `FauxInput > Input` height is calculated to be 41.33px in Chrome)
Using the following "dark" mode theming object:
```js
const theme = {
...DEFAULT_THEME,
colors: {
...DEFAULT_THEME.colors,
background: PALETTE.kale[800],
foreground: PALETTE.white,
chromeHue: PALETTE.black,
neutralHue: PALETTE.kale[400]
}
};
```

fix(dropdowns, datepickers): restore menu theming and prevent autocomplete pixel nudge

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButton.spec.tsx
packages/buttons/src/styled/StyledButton.ts

An `.attrs()` usage for the `<Button>` component isn't allowing consumer provided values for the `type` attribute. This PR now allows the component to receive this prop.
Closes #695 

feat(buttons): allow custom Button type

---

packages/tooltips/.size-snapshot.json
packages/tooltips/src/elements/Tooltip.tsx

While working on the new Garden site I noticed that a `Tooltip`'s content is updated while open the tooltip doesn't reposition its Popper instance until it is closed.
This PR adds the `content` prop the positioning effects dependency array.

fix(tooltips): ensure updated content triggers new position

---

packages/loaders/src/elements/Dots.tsx

This is the first submission as part of the Propstravaganza initiative to align API descriptions to be consistent in structure and generally understood by a designer audience.
I think future PRs might include more than one component at a time, but I wanted to see if the structure of this PR is correct or if anything could be improved before continuing on. 

chore(loaders): update Dots API descriptions

---

renovate.json

To help with common dependencies on `@types/react` and `@types/react-dom` we moved to an open dependency range in our root `package.json`.
This is conflicting with our base renovate config. This PR updates the `rangeStrategy` for this package.json only.
[Renovate docs](https://docs.renovatebot.com/configuration-options/#rangestrategy)

chore(renovate): allow open ranges for dev dependencies

---

examples/codesandbox/package.json
examples/codesandbox/yarn.lock
examples/gatsby/package.json
examples/gatsby/yarn.lock
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/datepickers/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/theming/package.json
packages/tooltips/package.json
packages/typography/package.json

This PR upgrades the styled-components peer dependency to include v5 as a valid range. I've also updated the codesandbox and gatsby examples and tested locally.
We are still unable to upgrade our local dependency due to [react-styleguidist environment issues](https://github.com/styled-components/styled-components/issues/3100), but that shouldn't stop consumers from upgrading.

feat(all): add styled-components v5 as valid peer dependency

---

packages/chrome/.size-snapshot.json
packages/chrome/package.json
packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
packages/chrome/yarn.lock

Recently, `container-accordion` was released as a major. This PR updates the `container-accordion` dependency in the `react-chrome` package and addresses the breaking changes from the major upgrade.
The demo for this PR can be found here: https://update-chrome.netlify.com/chrome/

fix(chrome): update accordion usage

---

packages/accordions/.size-snapshot.json
packages/accordions/package.json
packages/accordions/src/elements/stepper/components/Content.tsx
packages/accordions/src/styled/stepper/StyledInnerContent.tsx
packages/accordions/yarn.lock

This PR updates the `maxHeight` of the vertical `Stepper`'s inner content when the inner content's `scrollHeight` changes.
The Stepper’s inner content height is [calculated and applied](https://github.com/zendeskgarden/react-components/blob/master/packages/accordions/src/elements/stepper/components/Content.tsx#L23) in order to animate the Stepper’s inner content. However, **when the inner content’s `scrollHeight` changes, the height is not updated, resulting in a UI bug where the Stepper content has the old height value**. In the following screenshot examples, this problem is demonstrated by adjusting the browser window, which in turn changes the inner content’s `scrollHeight` as its text content readjusts to fit the new width.
**The inner content’s `maxHeight` needs to be updated to the …

fix(accordions): update height when content scrollHeight changes

---

packages/pagination/styleguide.config.js

This PR fixes the styleguidist path for`react-pagination`. The path names should point to `Pagination` and `CursorPagination` rather than `pagination` and `cursorpagination`.
Here is a confirmation of the two directory names committed to master: [one](https://github.com/zendeskgarden/react-components/blob/master/packages/pagination/src/elements/CursorPagination/CursorPagination.tsx
) & [two](https://github.com/zendeskgarden/react-components/blob/master/packages/pagination/src/elements/Pagination/Pagination.tsx
).
https://goofy-snyder-db7361.netlify.com/pagination/

fix(pagination): fix styleguidist path

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/examples/advanced-menu.md
packages/dropdowns/examples/tree-menu.md
packages/dropdowns/src/elements/Menu/Items/HeaderIcon.spec.tsx
packages/dropdowns/src/elements/Menu/Items/HeaderItem.spec.tsx
packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
packages/dropdowns/src/elements/Menu/Items/MediaFigure.spec.tsx
packages/dropdowns/src/styled/items/StyledItem.ts
packages/dropdowns/src/styled/items/StyledItemIcon.ts
packages/dropdowns/src/styled/items/StyledItemMeta.ts
packages/dropdowns/src/styled/items/StyledNextItem.ts
packages/dropdowns/src/styled/items/header/StyledHeaderIcon.ts
packages/dropdowns/src/styled/items/header/StyledHeaderItem.ts
packages/dropdowns/src/styled/items/media/StyledMediaBody.ts
packages/dropdowns/src/styled/items/media/StyledMediaFigure.ts
packages/dropdowns/src/styled/items/media/StyledMediaItem.ts
packages/dropdowns/src/styled/menu/StyledMenu.ts

This PR revises and simplifies the menu item spacing between compact and default sizes in preparation for Select Media Items. 

feat(menu): revise menu spacing

---

packages/typography/.size-snapshot.json
packages/typography/examples/code.md
packages/typography/examples/lists.md
packages/typography/examples/typography.md
packages/typography/src/elements/LG.spec.tsx
packages/typography/src/elements/LG.tsx
packages/typography/src/elements/MD.spec.tsx
packages/typography/src/elements/MD.tsx
packages/typography/src/elements/SM.spec.tsx
packages/typography/src/elements/SM.tsx
packages/typography/src/elements/XL.spec.tsx
packages/typography/src/elements/XL.tsx
packages/typography/src/elements/XXL.spec.tsx
packages/typography/src/elements/XXL.tsx
packages/typography/src/elements/XXXL.spec.tsx
packages/typography/src/elements/XXXL.tsx
packages/typography/src/styled/StyledFont.spec.js
packages/typography/src/styled/StyledFont.tsx
utils/build/styled.d.ts

All typography t-shirt sizes now expose an `isBold` prop for applying a semibold font-weight to the text content.
Demo pre-published for review at https://affectionate-curran-d65162.netlify.com/typography/#typography
FWIW, this is how semibold treatment looks on Android (Samsung Galaxy S10):

feat(typography): add bold option

---

packages/notifications/.size-snapshot.json
packages/notifications/src/styled/content/StyledClose.ts

This PR restores transitions for the `background-color` and `color` styles on focus and hover for the close button on `react-notifications`. 
The changeset brings the styles to parity with [css-callouts](https://garden.zendesk.com/css-components/callouts/). I've also added a style to override the default focus border on Firefix, as I noticed it during cross-browser testing:

fix(notifications): restore transition to close button focus & hover styles

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/radio/StyledRadioLabel.spec.tsx
packages/forms/src/styled/radio/StyledRadioLabel.ts
packages/forms/src/styled/toggle/StyledToggleLabel.ts

When `css-bedrock` is used in conjunction with Garden 8.x, the following line prevents checkmarks from displaying on radio/checkbox/toggle inputs with `<Label hidden>`:
https://github.com/zendeskgarden/css-components/blob/d781e314f271223495abcabd61a16cc414e7f4b2/packages/bedrock/src/_base.css#L63
The code was updated with a pixel-valued line-height due to the fact that `font-size: 0` for hidden labels.
Fix can be verified by using dev tools to add `<link rel="stylesheet" href="https://zendeskgarden.github.io/css-components/bedrock/index.css">` to the head of the deployed demo page and toggling "Hidden label" on the basic demo for radio, checkbox, and toggle inputs.

fix(forms): retain line height for hidden radio/checkbox/toggle labels

---

.github/PULL_REQUEST_TEMPLATE.md
utils/scripts/tag.js

Prevent the thing that happened on [29.04.2020](https://github.com/zendeskgarden/react-components/commits/master) where a single push of two `tag` commits ("release" and "changelog") prevented the release from triggering a CI run.
Compare https://github.com/zendeskgarden/react-components/commit/dc6809b2a64781d4ed5737bcc9602f28c32b6d5c
with https://app.circleci.com/pipelines/github/zendeskgarden/react-components?branch=master

chore(scripts): ensure version commit hits CI, triggering npm publish

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/examples/field-variants.md
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Select/Select.spec.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/styled/field/StyledSelect.ts

This PR adds the ability to provide a `start` icon to `Select` and `Autocomplete` components. Due to the interaction of `MultiSelect` I have not added the `start` option at this time for that components. 
I was originally hoping to mimic (or use directly) the styling provided by the `MediaInput` in `react-forms`. But, due to our use of `FauxInput` and necessity to dynamically render the internal `<input />` of the component I was unable to match the styling directly.
I was able to reuse the styling for the chevron icon though. The `start` slot will style it's child to match the `sm` and `md` icon sizes based on `isCompact`. It also plays well with the overflow styling already defined for both components.
I have also removed the `translateY(-1px)` styling from the chevron rotation. Let me …

feat(dropdowns): add start slot to autocomplete and select components

---

packages/breadcrumbs/.size-snapshot.json
packages/breadcrumbs/src/styled/StyledChevronIcon.tsx

The chevrons in the `Breadcrumbs` component should be displaying the secondary color (`grey-600`) instead of `currentColor`, which is black.
https://zendesk.atlassian.net/browse/GARDEN-1191

fix(breadcrumbs): change chevron color from black to grey-600

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Select/Select.spec.tsx
packages/dropdowns/src/styled/field/SelectWrapper.tsx
packages/dropdowns/src/styled/field/StyledSelect.ts
packages/forms/.size-snapshot.json
packages/forms/src/elements/MediaInput.tsx
packages/forms/src/styled/text/StyledTextInput.ts
packages/forms/src/styled/text/StyledTextMediaFigure.spec.tsx
packages/forms/src/styled/text/StyledTextMediaFigure.ts

This PR:
- Updates the default vertical padding for all `Input`, `Select`, `Autocomplete`, and `Multiselect` components.
- Updates default color of media items to `grey-600` (`grey-400` when disabled)
- Add consistent icon and padding to `compact` and `default` sizes across all inputs and dropdowns
After refactoring there are several styling assertions in our tests that break stylelint, even when stylelint is disabled. I've removed these tests as they were only asserting styles.

feat(forms/dropdowns): improve start icon sizing

---

package.json
yarn.lock

`v0.1.9` contains an important fix to `github-repository` that should be in-place before Garden's next release cycle.
Adds support for both HTTPS and SSH github URLs.

chore(deps): update @zendeskgarden/scripts

---

packages/accordions/.size-snapshot.json
packages/breadcrumbs/.size-snapshot.json
packages/buttons/.size-snapshot.json
packages/chrome/.size-snapshot.json
packages/datepickers/.size-snapshot.json
packages/dropdowns/.size-snapshot.json
packages/forms/.size-snapshot.json
packages/modals/.size-snapshot.json
packages/notifications/.size-snapshot.json
packages/pagination/.size-snapshot.json
packages/tables/.size-snapshot.json
packages/tags/.size-snapshot.json
yarn.lock

#737 passed in CI, but is failing on `master` due to `yarn.lock` conflicts. This PR updates the root `yarn.lock` and ensures that all packages have updated babel plugins and size snapshots.

chore(build): update yarn.lock file

---

packages/grid/.size-snapshot.json
packages/grid/examples/basic.md
packages/grid/src/elements/Col.tsx
packages/grid/src/styled/StyledCol.spec.tsx
packages/grid/src/styled/StyledCol.ts
packages/grid/src/utils/types.ts

We continue to see a desire to control horizontal alignment within `Col` components. This PR adds that capability (with RTL awareness) and will eradicate many of the `StyledCol` usages that are continuing to proliferate – even in Garden's own codebase.
See https://github.com/zendeskgarden/website/blob/master/src/examples/button/ButtonSizes.tsx for example (should not have a `margin-bottom` within a single `Row`).

feat(grid): add `textAlign` prop to `Col` component

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
packages/dropdowns/src/elements/Dropdown/Dropdown.tsx

While using the `onInputValueChange` prop within Autocomplete, Select, and Multiselect there are certain situations where the input value can be populated with an items string unexpectedly.
This is due to `onInputValueChange` being handled outside of the common state reducer in Downshift. This helps with IME input, but complicates how we have historically kept all this state inline.
I have included some additional checks around `isOpen` state when `onInputValueChange` is called.
The components now consistently reset their `inputValue` whenever the dropdown is closed. Whether that's via a selection, ESC key, or mouse interaction.
@ginnywood you found these issues originally. Please let me know if these aren't the intended actions.

fix(dropdowns): inputValue logic when selected

---

utils/scripts/tag.js

Editor execution needs to inherit stdio from parent process.
Tested with `vim` as editor.

fix(scripts): support terminal-based editors for changelog step in tag sequence

---

packages/accordions/.size-snapshot.json
packages/accordions/src/styled/stepper/StyledContent.spec.tsx
packages/accordions/src/styled/stepper/StyledContent.ts
packages/accordions/src/styled/stepper/StyledIcon.spec.tsx
packages/accordions/src/styled/stepper/StyledIcon.ts
packages/accordions/src/styled/stepper/StyledLine.ts

This pull request improves the spacing around the long label steps on the mobile vertical `Stepper` component.
The content padding-top has been reduced to zero (for all screen sizes) and the icon is now vertically centered to the vertical label.
| Mobile Before  |Mobile After  |
|---|---|
| <img src="https://user-images.githubusercontent.com/1811365/81968873-de63b000-95d1-11ea-8f46-a0c0b4d6391b.png" width="320">  | <img src="https://user-images.githubusercontent.com/1811365/81967543-ec183600-95cf-11ea-95a9-4732476dab7d.png" width="320"> 
**Desktop Before**
**Desktop After**

fix(accordions): improve vertical mobile stepper spacing

---

package.json
utils/scripts/tag.js

See https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-force
I encountered problems with a linked lint config package that inadvertently bombed the release script. This will fix for that.

chore(scripts): update tag script to force install

---

package.json
packages/modals/.size-snapshot.json
packages/modals/src/styled/StyledClose.ts
utils/styleguide/TableOfContentsRenderer/index.js
utils/styleguide/Wrapper/index.js
utils/styleguide/styleguide.base.config.js
yarn.lock

Adds a `vertical-align: middle` rule for the child SVG.
The rest of this PR adds support for a `?bedrock` demo page toggle in order to view component styling with CSS Bedrock enabled. The `qs` library was added for robust handling of URL `location.search` parameters.

fix(modals): vertically center close button SVG

---

packages/tags/.size-snapshot.json
packages/tags/examples/advanced.md
packages/tags/examples/basic.md
packages/tags/src/elements/Tag.tsx
packages/tags/src/styled/StyledTag.spec.tsx
packages/tags/src/styled/StyledTag.ts

Tags need the ability to display bold + non-bold text. For example:
> **Category** item
This PR adds an `isRegular` prop (similar to https://garden.zendesk.com/react-components/forms/#label) along with associated styling to make this possible.
See the basic and advanced demos for details.

feat(tags): support mixed weight content

---

.github/PULL_REQUEST_TEMPLATE.md
packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Select/Select.spec.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/styled/field/SelectWrapper.tsx
packages/dropdowns/src/styled/field/StyledSelect.ts

Along with abstracting common code (1k+ reduction in minified size) this PR fixes a list of styling problems:
- hover color not being applied to chevron
- focus color not being applied to chevron
- color transition timing not applied
- prevent icon wrapper height from exceeding container
Fixes icon sizing when CSS Bedrock is being used.
https://github.com/zendeskgarden/css-components/blob/9a80f2d1f053d17d8447b96feb46e01f2d378397/packages/bedrock/src/_base.css#L33-L35

fix(dropdowns): prevent icon box-sizing inheritance

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButton.ts

This pull request refines the horizontal padding to more appropriately space the button content depending on size and be friendlier in applications with limited space.
Padding increments have been refined to the following: 
```
large buttons: 28px -> 20px horizontal padding
medium buttons: 28px -> 16px horizontal padding
small buttons: 28px -> 12px horizontal padding
```

feat(buttons): revise button padding

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/styled/field/StyledSelect.ts

There exists a bug that causes the Select Dropdown to render `appearance: button` in Safari. The problem can be seen be visiting this [Codesandbox example](https://codesandbox.io/s/dropdownbedrock-0i0rd) in Safari. This bug blocks https://github.com/zendeskgarden/website/pull/52#discussion_r433376778.
The Select Dropdown forwards an unnecessary `type=button` attribute that is applied to the Select Dropdown `div`. CSS bedrock correctly [resets styles](https://github.com/necolas/normalize.css/blob/master/normalize.css#L196) based on `type="button"` on valid elements, but the Select Dropdown incorrectly applies `type=button` onto the `div` element.
I've decided to pluck off the `type="button` and not forward the attribute to be spread onto the `div` based on these findings:
1) I didn't see …

fix(dropdowns): remove type attribute from div

---

.eslintrc.json
packages/buttons/.size-snapshot.json
packages/buttons/README.md
packages/buttons/examples/basic.md
packages/buttons/src/elements/Button.tsx
packages/buttons/src/elements/ChevronButton.tsx
packages/buttons/src/elements/IconButton.tsx
packages/buttons/src/elements/ToggleButton.spec.tsx
packages/buttons/src/elements/ToggleButton.tsx
packages/buttons/src/elements/ToggleIconButton.spec.tsx
packages/buttons/src/elements/ToggleIconButton.tsx
packages/buttons/src/index.ts
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/styled/StyledIconButton.ts

Provides component support for https://www.w3.org/TR/wai-aria-1.1/#aria-pressed toggle buttons, including:
- new `ToggleButton` component with `isPressed` prop
- new `ToggleIconButton` component with `isPressed` prop
- styling connected with `[aria-pressed]` attribute applied to any button
@rossmoody I realized I ran a bit in front of official designs for this one. The styling for `[aria-pressed="true"]` is exactly the same as the existing `:active` state. If this is not desired, let's talk. It will be trivial to modify the CSS.

feat(buttons): new toggle button components

---

.github/PULL_REQUEST_TEMPLATE.md
.github/renovate.json

Coordinate schedule with other Garden repos. Override `ignorePaths` default [config](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests), allowing Renovate to run over `/examples` directory.
Slipped in a PR checklist change as problems with Bedrock CSS are becoming more acute with 8.x.

chore: update renovate schedule

---

packages/theming/.size-snapshot.json
packages/theming/src/utils/menuStyles.ts

When combined with `css-bedrock`, we see top menu (with arrow) positioning that looks like this:
Proper menu positioning is restored with this fix.
Currently affecting https://github.com/zendeskgarden/website/pull/55

fix(menus): prevent inherited line-height from affecting positioning

---

packages/accordions/.size-snapshot.json
packages/accordions/src/styled/accordion/StyledRotateIcon.ts

The `Accordion` chevron rotate icon is not visible when CSS Bedrock is turned on. 
Using `padding` for spacing incorporates spacing into the size of the icon making the icon smaller and not visible. By using margin the size is retained.
**Before** (with Bedrock CSS turned on)
**After** (with Bedrock CSS turned on)

fix(accordions): correct spacing for rotate icon

---

packages/dropdowns/examples/multiselect.md

This PR ensures all `react-dropdowns` examples use the `onInputValueProp` to allow IME inputs.

chore(docs): update Multiselect example to allow IME input

---

packages/tables/.size-snapshot.json
packages/tables/examples/paginated-table.md
packages/tables/examples/selectable-table.md
packages/tables/src/elements/Cell.spec.tsx
packages/tables/src/styled/StyledCell.ts

Per design specs:
- `<Cell>`s are meant to have 12px R/L padding (v8 CSS-in-JS regression)
- Overflow `<Button>` should be positioned 4px from edge of table
Also added `<span>` tags around long text demo examples. Without this, text flows into cell padding.

fix(tables): cell and overflow padding

---

packages/typography/.size-snapshot.json
packages/typography/examples/span.md
packages/typography/src/elements/Span.tsx

Supports toggling on a monospace `font-family` within a `<Span>` tag.

feat(typography): add isMonospace prop to Span component

---

packages/grid/.size-snapshot.json
packages/grid/src/styled/StyledCol.spec.tsx
packages/grid/src/styled/StyledCol.ts

This PR removes the unnecessary relative position on the `Col` element. 
A bug was recently discovered where a dropdown menu is clipped when the menu is rendered inside a `Col` that was positioned relative. 

fix(grid): remove relative position from col

---

package.json
utils/styleguide/styleguide.base.config.js

The snippet added in #80 is no longer being used. This PR reduces Garden's cookie footprint.
In addition, the `start:demo` script was simplified to improve the launch/testing experience. A contributor will need to run the time-intensive `build:demo` once in order to get the latest home page.

chore: remove pendo snippet

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButtonGroup.ts

#758 introduced a `ButtonGroup` regression by setting `display: flex`. This PR corrects that to be `display: inline-flex` so that the button group does not eat up unintended surrounding space.

fix(buttons): inline display for button groups

---

.circleci/config.yml
packages/dropdowns/src/Dropdown/Dropdown.tsx
packages/dropdowns/src/Menu/Items/Item.ts
packages/dropdowns/src/Menu/Menu.tsx
packages/dropdowns/src/Select/Select.tsx
packages/dropdowns/src/Trigger/Trigger.tsx

This PR allows users to highlight `Select` values based on the W3C list pattern
> Type a character: focus moves to the next item with a name that starts with the typed character.
> 
> Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.
I based this interaction from the [Collapsible Dropdown List W3C example](https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html) as well as the [Reach UI Listbox example](https://reacttraining.com/reach-ui/listbox).
The _type multiple characters in rapid succession_ feature adds some complexity to this implementation. To accomplish this I:
- Register the `innerText` of each `<Item>` on render
- We are unable to rely on `itemToString()` as this is …

feat(dropdowns): allow Select to receive alphanumeric selection

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
packages/dropdowns/src/elements/Menu/Items/Item.tsx
packages/dropdowns/src/elements/Menu/Menu.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx
packages/dropdowns/src/utils/useDropdownContext.ts

This is a cherry-pick of #786 for the `v8` major
Similar to #786 JSDOM limitations make this addition difficult to test accurately.

feat(dropdowns): allow Select to search with keyboard interaction

---

packages/notifications/.size-snapshot.json
packages/notifications/examples/basic.md
packages/notifications/src/elements/content/Title.spec.tsx
packages/notifications/src/elements/content/Title.tsx
packages/notifications/src/styled/content/StyledTitle.ts

Add the ability to show a Notification's title in regular font-weight.

fix(notifications): add support for regular weight title

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/radio/StyledRadioLabel.ts

Fix for specificity ordering affecting hidden label examples on `website`.

fix(forms): override Bedrock CSS [hidden] styling for radios, checkboxes, and toggles

---

packages/chrome/.size-snapshot.json
packages/chrome/examples/basic.md
packages/chrome/examples/header.md
packages/chrome/src/elements/Chrome.spec.tsx
packages/chrome/src/elements/Chrome.tsx

Prevent fixed positioning from being applied to the <html> element
This [CodeSandbox](https://codesandbox.io/s/loving-fast-86t3l?file=/src/examples/Example.js) demonstrates the issue. Notice that there is extra white space on the bottom. Also, click the `Checkbox` and notice the screen jumps to the bottom of the white space. Applying a fixed position to the `html` element resolves the issue.

fix(chrome): add fixed positioning to html element

---

packages/avatars/examples/advanced.md

This PR updates the avatar example to use a fluid `Chrome` component.
There is a bug on the Avatar styleguidst page where the page cannot be scrolled. Recently the `Chrome` component was updated to render a `position: fixed` on the `html` tag. For examples such as `Avatars` that render `Chrome` as an example and not a full page shell, `isFluid` needs to be passed to remove the fixed position.
**before**:
The production `Avatar` example [page](https://garden.zendesk.com/react-components/avatars/) cannot scroll. 
**after**:
The Avatar component [page](https://5f035b1c314ea07bb8760f40--zendeskgarden-react-components.netlify.app/avatars/) can scroll.

fix(avatars): use fluid chrome in avatars example

---

packages/typography/.size-snapshot.json
packages/typography/src/elements/lists/UnorderedList.spec.js
packages/typography/src/elements/lists/UnorderedList.tsx

Go with the grain of the web: https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type#Values
Addresses regression in [#441](https://github.com/zendeskgarden/react-components/pull/441/files#diff-fb8b1446a33100a6c854bf9746751199R31).

fix(typography): set UnorderedList type default to "disc"

---

packages/theming/.size-snapshot.json
packages/theming/src/index.ts
packages/theming/src/utils/mediaQuery.spec.ts
packages/theming/src/utils/mediaQuery.ts

Add convenience helper for producing `@media ...` CSS query strings based on theming breakpoints. Will be used, initially, to correct media queries throughout the Garden website.
Takes some API direction from:
- https://material-ui.com/customization/breakpoints/#api
- https://www.npmjs.com/package/styled-breakpoints.

feat(theming): add mediaQuery utility

---

packages/tables/examples/selectable-table.md

This PR adds some keyboard logic to our selection example. This logic follows the logic shown in [ag-grid](https://www.ag-grid.com/example-runner/grid-vanilla.php?section=javascript-grid-selection&example=multiple-row-selection&generated=1&grid=%7B%22noStyle%22%3A0%2C%22height%22%3A%22100%25%22%2C%22width%22%3A%22100%25%22%2C%22enterprise%22%3Anull%7D)
There are some edge-cases since we provide checkboxes for selection rather than a grid pattern, but overall this feels like a good middle-ground.

chore(docs): update Table selection example to allow keyboard

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
packages/dropdowns/src/elements/Menu/Items/NextItem.tsx

Fixes #816 
This PR allows `NextItem` component to handle keyboard navigation correctly when the provided value is an `object`.

fix(dropdowns): allow object values for NextItem selection

---

packages/buttons/.size-snapshot.json
packages/buttons/src/elements/Anchor.spec.tsx
packages/buttons/src/elements/Anchor.tsx

Adds default values for the `target` and `rel` attributes for Anchors that include the `isExternal` prop. These values are customizable for advanced use-cases.
https://web.dev/external-anchors-use-rel-noopener/

feat(buttons): default external links to use safe referrer attributes

---

packages/forms/.size-snapshot.json
packages/forms/examples/basic.md
packages/forms/src/elements/Textarea.spec.tsx
packages/forms/src/elements/Textarea.tsx
packages/forms/src/styled/text/StyledTextarea.ts

This PR introduces the concept of auto-resizing to the `Textarea` component. This functionality is disabled by default.
This feature is enabled with two new props, `minRows` and `maxRows`. These new props define the upper and lower bounds for overflow when resizing and only enable auto-resizing if the `isResizable` props is not provided.
After looking at several other implementations, the most common way of achieving this functionality in a cross-browser compatible way is to use hidden "shadow" input with the same styling to calculate when an overflow occurs. This shadow input is only rendered if the auto-resizing props are provided.
Resizing is handled on initial render, when the screen is resized (with debounce), and when the input value is changed. It also handles both controlled and …

feat(forms): allow Textarea to dynamically change height

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/Textarea.spec.tsx
packages/forms/src/elements/Textarea.tsx

During the v7 backport I found that the current logic for Textarea resizing doesn't perform well if the `value` is controlled. This change adds a `useLayoutEffect` for any render and also adds the new props to the `propTypes` definition.

fix(forms): ensure Textarea autoresizing is calculated with controlled value

---

packages/buttons/src/elements/Anchor.tsx

Updates the prop-type docs for `isExternal` `Anchor` usage.

chore(buttons): update Anchor isExternal prop docs

---

package.json
packages/accordions/src/elements/accordion/components/Header.spec.tsx
packages/buttons/src/elements/ButtonGroup.spec.tsx
packages/chrome/src/elements/subnav/CollapsibleSubNavItem.spec.tsx
packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
packages/datepickers/src/elements/DatepickerRange/DatepickerRange.spec.tsx
packages/datepickers/src/elements/DatepickerRange/components/End.spec.tsx
packages/datepickers/src/elements/DatepickerRange/components/Start.spec.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
packages/dropdowns/src/elements/Fields/Label.spec.tsx
packages/dropdowns/src/elements/Menu/Items/AddItem.spec.tsx
packages/dropdowns/src/elements/Menu/Items/Item.spec.tsx
packages/dropdowns/src/elements/Menu/Items/MediaItem.spec.tsx
packages/dropdowns/src/elements/Menu/Menu.spec.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
packages/dropdowns/src/elements/Select/Select.spec.tsx
packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
packages/forms/src/elements/FauxInput.spec.tsx
packages/forms/src/elements/MediaInput.spec.tsx
packages/forms/src/elements/MultiThumbRange.spec.tsx
packages/forms/src/elements/Range.spec.tsx
packages/forms/src/elements/tiles/Tiles.spec.tsx
packages/modals/src/elements/Modal.spec.tsx
packages/pagination/src/elements/Pagination/Pagination.spec.tsx
packages/tables/src/elements/OverflowButton.spec.tsx
packages/tables/src/elements/Row.spec.tsx
packages/tabs/src/elements/Tabs.spec.tsx
packages/tooltips/src/elements/Tooltip.spec.tsx
yarn.lock

This pull request integrates the [@testing-library/user-event](https://www.npmjs.com/package/@testing-library/user-event) package to help better simulate real events. From the docs:
> user-event tries to simulate the real events that would happen in the browser as the user interacts with it. 
* This PR only touches `package.json` and `.spec` files
* Most of this PR is a simple migration from `fireEvent` to `userEvent`
* Some tests will still require `fireEvent` as `userEvent` is not a 1 to 1 replacement
* I rewrote two tests as they were false positives which have been highlighted in the comments
* The testing-lib docs have a [great section](https://testing-library.com/docs/guide-events) on events and testing
* A list of available `userEvent` APIs from [the …

chore(tests): add user-event testing library

---

packages/forms/examples/text-input.md
packages/forms/src/fields/Textarea.js
packages/forms/src/fields/Textarea.spec.js
packages/forms/src/styled/text/StyledTextarea.js

v7 backport for #820 
This PR includes a fix to ensure controlled Textarea usages are calculated correctly.

feat(forms): allow Textarea to autoresize based on content

---

packages/notifications/.size-snapshot.json
packages/notifications/src/styled/StyledBase.spec.tsx
packages/notifications/src/styled/StyledBase.ts
packages/notifications/src/styled/StyledIcon.ts
packages/notifications/src/styled/StyledWell.ts

This PR fixes a spacing issue on the `Alert` and `Notification` component.
Recently it was discovered that the `Well` text content didn't align with `Alert` and `Notification`. Turns out `Alert` and `Notification`'s spacing does not match the current design assets.
This PR ensures that the padding for `Well`, `Alert`, and `Notification` are consistent by inheriting the padding from the base component. That padding is now consistent with design assets.
**Before**: `Alert` and `Notification` has start padding of `50px`. `Well` has start padding of `40px`.
**After**: `Well`, `Alert` and `Notification` has start padding of `40px`.

fix(notifications): update notification padding

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/Datepicker/components/Calendar.tsx

The `Datepicker` components are currently formatting individual days using the `DateTimeFormat` utility. This is creating invalid localizations for some locales.
_Invalid Japanese Days_
The value `DateTimeFormat` makes sense in the context of a date string, but not as standalone numbers. To format these values correctly I've modified our day formatting logic to use the `Intl.NumberFormat` utility. This uses the same BCP tag as `DateTimeFormat` and provides a valid localization for our main locales.
_English_
_Japanese_
_Arabic_

fix(datepickers): format day with NumberFormat utility

---

packages/buttons/.size-snapshot.json
packages/buttons/examples/basic.md
packages/buttons/src/styled/StyledButton.ts

Danger styled anchors aren't retaining red color when CSS Bedrock is in the mix.
**Before**
**After**

fix: danger anchor focus color

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledIconButton.ts

Icon buttons in `flex` environments are squishing to accommodate for other elements inline. This PR adds a min-width designation to make them retain their size. 

fix(buttons): apply min-width to icon buttons

---

packages/tooltips/src/elements/Tooltip.tsx

I noticed that the link to the Popper Modifiers documentation is incorrectly pointing to the latest (v2) version of the library docs, whereas this component is [dependent on v1.3.4](https://github.com/zendeskgarden/react-components/blob/main/packages/tooltips/package.json#L28). This had me scratching my head for a while trying to figure out why nothing would work.
I also made a small grammatical correction while I was here. "It's" is a contraction for "it is" and does not denote ownership.

docs(tooltip) fix errors in tooltip docs

---

packages/typography/.size-snapshot.json
packages/typography/src/styled/StyledIcon.ts

Clears a React console error re: `isStart` being applied to `<Span.StartIcon>`.

fix(typography): prevent prop from being added to DOM element

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/accordion/components/Header.tsx
packages/accordions/src/elements/accordion/components/Label.spec.tsx

When an accordion is inside a `<form>` the accordion buttons cause a form submission due to the default button behavior. This PR removes the default button behavior on accordions by adding a `type=button` to the accordion buttons.

fix(accordions): remove default button behavior

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/common/Label.tsx
packages/forms/src/styled/checkbox/StyledCheckSvg.ts
packages/forms/src/styled/checkbox/StyledDashSvg.ts

There is a bug in Firefox which prevents checkboxes from being selected when a user performs a `shift + click` on the checkbox label. 
A small Firefox-specific snippet of code has been added to manually call events when a checkbox label is clicked which allows the checkbox to become checked when a user performs `shift + click` on a checkbox label.
❌ **Before (`react-forms`)**: `shift + click` on the label does not select the checkbox in Firefox
✅ **After (`react-forms`)**: `shift + click` on the label selects the checkbox in Firefox
---
❌ **Before (`react-tables`)**: `shift + click` does not select multiple rows in Firefox
✅ **After (`react-tabels`)**: `shift + click` selects multiple rows in Firefox

fix(forms): workaround shift+click checkbox labels on Firefox

---

packages/forms/src/fields/common/Label.js

fix(forms): allow checkbox label click for Firefox

---

.github/workflows/pull-request-labels.yaml

This PR adds a [Github action](https://github.com/marketplace/actions/require-labels) to ensure that all pull requests include a semantic release label for changelog generation.
I have intentionally left the label off to validate that it fails a PR.

chore(ci): ensure all PRs include semantic release label

---

packages/forms/examples/input-group.md

This PR removes he primary `Button` from the input group docs.
- ~[] :guardsman: includes new unit tests~

chore(docs): remove primary button from input-group docs

---

packages/pagination/src/elements/CursorPagination/components/First.tsx
packages/pagination/src/elements/CursorPagination/components/Last.tsx
packages/pagination/src/elements/CursorPagination/components/Next.tsx
packages/pagination/src/elements/CursorPagination/components/Previous.tsx

While adding cursor pagination to the website (https://github.com/zendeskgarden/website/pull/165), it was discovered that cursor pagination buttons had type definition issues. It seems like the interface for these buttons can be a little bit more specific.
I've swapped out `HTMLAttributes` with `ButtonHTMLAttributes` which allows button props such as `disabled` to be passed to the cursor pagination button components.

fix(pagination): fix cursor button type definitions

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/styled/multiselect/StyledMultiselectInput.ts
packages/dropdowns/src/styled/multiselect/StyledMultiselectItemWrapper.ts
packages/dropdowns/src/styled/multiselect/StyledMultiselectItemsContainer.ts
packages/dropdowns/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
packages/dropdowns/src/styled/select/StyledFauxInput.ts
packages/dropdowns/src/styled/select/StyledInput.ts
packages/dropdowns/src/styled/select/StyledSelect.ts

This PR adds some missing `retrieveComponentStyles()` calls from the `react-dropdowns` package.

fix(dropdowns): allow internal elements to receive custom component styles

---

packages/dropdowns/src/Multiselect/Multiselect.spec.tsx
packages/dropdowns/src/Multiselect/Multiselect.tsx

The left (or right in RTL) arrow key ends up focusing the last tag in the input for Multi-select components with nested menus. This PR makes it such that pressing the left (or right in RTL) arrow key does not end up focusing the last tag in the input for Multi-select component with nested menus.

fix: correct keyboard navigation for nested multiselect menus

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/Datepicker/Datepicker.tsx
packages/datepickers/src/elements/DatepickerRange/components/End.tsx
packages/datepickers/src/elements/DatepickerRange/components/Start.tsx

After playing around with the `Datepicker` and `DatepickerRange` components I've found that we are unable to compose event handlers in a similar way to other components.
This can make it difficult to override default functionality and have more granular control over the datepicker state. To help with this control I've added our `composeEventHandler` utility to all events within the components.
An example use-case where this could be helpful is if a consumer wants to remove the date value when an empty string is provided. With these new event handlers it could be accomplished with a simple `onChange` event.
```jsx
<Field>
<Label>Select a date</Label>
<Datepicker value={state.value} onChange={newDate => setState({ value: newDate })}>
<Input
onChange={e => {
if (e.target.value === '') { …
```

fix(datepickers): allow event composition on Datepicker inputs

---

package.json
packages/accordions/.size-snapshot.json
packages/accordions/src/elements/accordion/components/Header.tsx
yarn.lock

While investigating Chromium auto-scroll issues with the Accordion, I noticed an **unrelated** browser inconsistency/bug in Firefox where pressing the `space` key in Firefox on an accordion header button causes an accordion panel to expand slightly and then immediately collapse.
It seems like pressing the `space` key on a button element triggers a `click` event. Somehow, Firefox treats this a little differently than other browsers firing both a `click` and `keydown` event.
This issue can be reproduced in the [basic Accordion example](https://zendeskgarden.github.io/react-components/accordions/#basic):
1) Open the example in Firefox
2) Use the `Tab` key to navigate to an accordion header in the "Basic" example
3) Press the `space` key
❌ **Before:** The accordion panel expands slightly …

fix(accordions): prevent double trigger invocation on Firefox

---

packages/accordions/.size-snapshot.json

It looks like the `accordions` bundle snapshot is out of sync. This PR updates the `accordions` snapshot.

internal(accordions): update snapshot

---

packages/typography/.size-snapshot.json
packages/typography/examples/codeblock.md
packages/typography/package.json
packages/typography/src/elements/CodeBlock.spec.tsx
packages/typography/src/elements/CodeBlock.tsx
packages/typography/src/index.ts
packages/typography/src/styled/StyledCodeBlock.spec.tsx
packages/typography/src/styled/StyledCodeBlock.ts
packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
packages/typography/src/styled/StyledCodeBlockLine.ts
packages/typography/src/styled/StyledCodeBlockToken.spec.tsx
packages/typography/src/styled/StyledCodeBlockToken.ts
packages/typography/src/styled/index.ts
packages/typography/styleguide.config.js
packages/typography/yarn.lock

The new `CodeBlock` component statically renders blocks of code with language syntax highlighting based on [Prism](https://prismjs.com/) and with Garden color palette theming.
After careful evaluation, I selected [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer) due to flexibility of the model, structural semantics (block -> line -> token), and reduced interference with the underlying Prism tokenization. While more popular, [highlight.js](https://highlightjs.org/) proved to be problematic on each of these points.
There are still plenty of styling nits with the final result, but we obtained the best result that the underlying technology is able to give us. Ideally, Prism improves over time, and our `CodeBlock` will improve with it.

feat(typography): introduce CodeBlock component

---

packages/forms/.size-snapshot.json
packages/forms/examples/file-upload.md
packages/forms/package.json
packages/forms/src/elements/FileUpload.spec.tsx
packages/forms/src/elements/FileUpload.tsx
packages/forms/src/index.ts
packages/forms/src/styled/file-upload/StyledFileUpload.ts
packages/forms/src/styled/index.ts
packages/forms/styleguide.config.js
packages/forms/yarn.lock

This PR introduces a new `FileUpload` component. 
File uploads are dependent on business logic and backend support for common features like thumbnails, upload progress, and file restrictions. [react-dropzone](https://react-dropzone.js.org/) is a popular library that helps abstract some of this complexity.
To support as many use-cases as possible this component is a simple, styled `<div>` that is able to be used with `react-dropzone` or any other file upload abstraction.
For a11y considerations this is built within the `react-forms` package and allows it to be used along our existing `Field/Label/Hint/Message/Input` components.
The example includes an implementation of a file list. It includes some mocked random file upload speeds to demonstrate a common upload pattern.
designer as a …

feat(forms): introduce FileUpload component

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/radio/StyledRadioInput.ts
packages/forms/src/styled/text/StyledTextInput.ts
packages/forms/src/styled/tiles/StyledTile.ts

Per design directive in order to smooth out `InputGroup` component set.

fix(forms, datepickers, dropdowns): bump input border hover color from blue-400 to blue-600

---

packages/typography/.size-snapshot.json
packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
packages/typography/src/styled/StyledCodeBlockLine.ts

Noticed a couple of styling problems when I started to port `CodeBlock` over to the Garden website. Code comments in `StyledCodeBlockLine` describe it best:
- Fix line display for mobile.
- Match parent padding for overflow scroll.

fix(typography): codeblock styling tweaks

---

packages/modals/.size-snapshot.json
packages/modals/package.json
packages/modals/src/elements/Modal.tsx
packages/modals/yarn.lock

While implementing some `TooltipModal` documentation in the `website` repo I found a server-side rendering issue with our `Modal` component.
Our usage of `document.body` in the `propTypes` definition for `Modal` makes it unable to run within SSR environments. To resolve this I've made the implementation use the updated `useDocument` hook which provides this element safely.
Now that we are conditionally rendering the `Modal` content based on `useDocument` this has found some issues with the `useCombinedRefs` hook that we use throughout the components. It works well for our common use-cases, but fell apart here.
After looking into it some more, there are now some popular solutions that are more graceful 😄 https://github.com/gregberge/react-merge-refs stood out as the best option and gives …

fix(modals): allow Modal to be used in SSR environments

---

packages/forms/.size-snapshot.json
packages/forms/examples/basic.md
packages/forms/examples/input-group.md
packages/forms/src/elements/FauxInput.tsx
packages/forms/src/elements/Input.spec.tsx
packages/forms/src/elements/Input.tsx
packages/forms/src/elements/MediaInput.spec.tsx
packages/forms/src/elements/MediaInput.tsx
packages/forms/src/elements/Textarea.spec.tsx
packages/forms/src/elements/Textarea.tsx
packages/forms/src/styled/text/StyledTextFauxInput.spec.tsx
packages/forms/src/styled/text/StyledTextFauxInput.ts
packages/forms/src/styled/text/StyledTextInput.spec.tsx
packages/forms/src/styled/text/StyledTextInput.ts

Adds `readOnly` attribute support for `<Input>`, `<Textarea>`, `<FauxInput>`, and `<MediaInput>`. Features:
- updated `readonly` color styling
- text auto-selection on focus/click (does not apply to `<FauxInput>`)
@m-lai please kick the tires pretty hard on this one by going through all the permutations under the forms "Basic" example. I made some assumptions about state (hover, focus) styling was meant to work along with `readOnly`. I also upgraded the "Input Group" example to demonstrate `readOnly`.

feat(forms): add readonly support for text inputs

---

packages/.template/tsconfig.build.json
packages/accordions/tsconfig.build.json
packages/avatars/tsconfig.build.json
packages/breadcrumbs/tsconfig.build.json
packages/buttons/tsconfig.build.json
packages/chrome/tsconfig.build.json
packages/datepickers/tsconfig.build.json
packages/dropdowns/tsconfig.build.json
packages/forms/tsconfig.build.json
packages/grid/tsconfig.build.json
packages/loaders/tsconfig.build.json
packages/modals/tsconfig.build.json
packages/notifications/tsconfig.build.json
packages/pagination/tsconfig.build.json
packages/tables/tsconfig.build.json
packages/tabs/tsconfig.build.json
packages/tags/tsconfig.build.json
packages/theming/tsconfig.build.json
packages/tooltips/tsconfig.build.json
packages/typography/tsconfig.build.json

Looking through the `dist` of the latest release, it looks like the `dist/typings` directory is no longer valid.
The addition of the `paths` entry to our root config seems to have messed with the relative paths in `ts-loader`. By overriding this entry in the package-specific `tsconfig.build.json` this resolves the issues and fixes TS usages.

fix(build): ensure ts types directory is relative

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/Modal.tsx

It was recently discovered that focusvisible behavior broke within modal components.
It looks like the `environment` changes when the modal is mounted but the change is not captured by the `useFocusVisible` hook. 
In order to capture this change, the `environment` is passed to `useFocusVisible` as the `relativeDocument`. A `useEffect` within `useFocusVisible` re-runs the effect accordingly when the `relativeDocument` is updated. 
🙏  Thanks @austin94 for helping figure out the root problem.
**Before:**
**After:**

fix(modals): provide ref object for focusvisible

---

packages/tables/src/elements/Cell.tsx
packages/tables/src/elements/HeaderCell.tsx

This PR is a little bit of a reach as my TS knowledge is non-existent but I took a stab at a fix. While doing the Table examples for the site, I was getting an error that colSpan didn't exist on the Cell component. It looks like `colSpan` doesn't exist on `HTMLAttributes` but it does on `ThHTMLAttributes`. 

fix(table): revise cell type definition

---

packages/theming/.size-snapshot.json
packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
packages/theming/src/elements/palette/index.ts

Just a handful of hex updates corresponding with https://brandland.zendesk.com/.

fix(theming): update brand spec'd product colors

---

packages/buttons/.size-snapshot.json
packages/buttons/examples/basic.md
packages/buttons/src/styled/StyledIcon.ts
packages/buttons/src/styled/StyledIconButton.ts

- We may need to ease the `opacity` transition between stroke/fill buttons on toggle.
- Removes invalid `theme` attribute from the cloned icon.
@ginnywood please have a look at the "Toggle Button" example in the PR deployment. Note the affect of the various knobs (i.e. "Primary") on the transition animation.
Will impact or be impacted by #889.

fix(buttons): improve stroke/fill icon swap for ToggleIconButton

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
packages/modals/src/elements/DrawerModal/DrawerModal.tsx
packages/modals/src/elements/Modal.spec.tsx
packages/modals/src/elements/Modal.tsx

When Bedrock CSS is turned on and the `Modal` and `DrawerModal` components are opened the main window should be inert, but the user can scroll the main window.
**Steps to reproduce:**
1) Navigate to https://zendeskgarden.github.io/react-components/modals/
2) Turn on Bedrock CSS
3) Open a `Modal` or `DrawerModal`
4) Trigger some scroll events; **the main window behind the backdrop scrolls, but it shouldn't**
The Bedrock CSS that normalizes CSS in the Garden ecosystem applies an `overflow-y:scroll;` to the `html` element. In some cases like modal components, the `overflow-y:scroll;` should be overwritten so that inert windows behind an open modal dialog cannot be scrolled. 
This PR proposes to modify overflow CSS for the `html` element instead of the `body` element. By doing so, the …

fix(modals): prevent html overflow

---

packages/modals/src/elements/Close.tsx
packages/modals/src/elements/DrawerModal/Close.tsx
packages/modals/src/elements/TooltipModal/Close.tsx
packages/notifications/src/elements/content/Close.tsx

This PR updates the type definition for `Close` buttons in the modals and notifications packages.
Applying native button attributes such as `disabled` to Garden's `Close` buttons results in TypeScript erroring with. For example, 
```jsx
<Modal>
<Close disabled>Close</Close>
</Modal>
```
results in the following TypeScript error
```
error TS2322: Type '{ disabled: boolean; }' is not assignable to type 'IntrinsicAttributes & HTMLAttributes<HTMLButtonElement> & RefAttributes<HTMLButtonElement>'.
Property 'disabled' does not exist on type 'IntrinsicAttributes & HTMLAttributes<HTMLButtonElement> & RefAttributes<HTMLButtonElement>'
```
It looks like [ButtonHTMLAtrributes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1960) is needed to support native …

fix(modals|notifications): update type definition for button elements

---

packages/theming/.size-snapshot.json
packages/theming/src/elements/ThemeProvider.spec.tsx
packages/theming/src/elements/ThemeProvider.tsx
packages/theming/styleguide.config.js

Items of note for this PR:
- Adds support for `focusVisibleRef={null}` to prevent render of `:focus-visible` scoping div default
- Adds associated spec tests
- Fills out ThemeProvider prop documentation in prep for website.
- Restores `ThemeProvider` prop sheet to the example page

feat(theming): provide scoping <div> knock-out for ThemeProvider

---

packages/pagination/.size-snapshot.json
packages/pagination/src/elements/Pagination/Pagination.tsx

This PR refactors the `Pagination` to receive the `theme` via context.
I noticed that the prop type descriptions were not rendering in Storybook while migrating `Pagination` from Styleguidist to Storybook. It looks like the prop type and description information was being swallowed since the `Pagination` was wrapped in a `withTheme` higher-order component.
This situation felt like a good opportunity to refactor `Pagination` to use a more modern approach to getting the `theme` value, which also should allow Storybook to properly display the prop type and description text.

chore(pagination): get theme from context

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Fields/Field.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx

We have seen some reports of screenreader inconsistencies in Safari within our `react-dropdowns` package. This PR is an attempt to get Safari in a state that is usable.
These screenreader issues affect the `Autocomplete` and `Multiselect` components. `Menu` and `Select` are a traditional listbox pattern and seem to be working correctly.
Currently, Chromium, Firefox, and legacy Edge browsers are able to handle the default downshift layout for our `Autocomplete` and `Mutliselect` components. 
```
<div {...getRootProps()}> // role="combobox"
<label {...getLabelProps()}>...</label>
<input {...getInputProps()} />
</div>
```
But, in Safari, Voiceover is unable to interact with content within `combobox` elements in a traditional manner. You are able to trigger some interactions with non-standard …

fix(dropdowns): support Safari Voiceover commands

---

packages/dropdowns/src/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/Fields/Field.tsx
packages/dropdowns/src/Multiselect/Multiselect.tsx
packages/dropdowns/src/Trigger/Trigger.tsx

This is a cherrypick of #902 to allow Voiceover to interact with our dropdowns in Safari.

fix(dropdowns): improve safari voiceover support

---

packages/tables/.size-snapshot.json
packages/tables/src/styled/StyledSortableButton.ts

This PR resolves a bug where the `SortableHeaderCell` component was showing focus styling on non-keyboard actions. It is now updated to show this styling on hover and focus-visible interactions only.

fix(tables): ensure sortable header cells have focus-visible styling

---

packages/modals/.size-snapshot.json
packages/modals/src/styled/StyledClose.spec.tsx
packages/modals/src/styled/StyledClose.ts

This PR aligns the modal's "X" close button with the CTA buttons in a modal.

fix(modals): align close button

---

docs/migration.md

This PR updates the V8 migration doc to highlight the removal of the `muted` prop for `react-buttons` and corrects the `v7` prop name to `bare` for `react-dropdowns`.

chore(docs): update migration doc

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx

Support implements a nested `Multiselect` using the `PreviousItem` component. When a user presses an arrow key to navigate back to the parent menu (from the nested menu), the menu closes and the input is focused — it does not navigate to the parent menu.
This PR checks that `previousIndexRef` is `undefined` before focusing on the input. If a user is on a nested menu, `previousItem` component is used and `previousIndexRef` will be defined.
**After:** user can navigate back to the parent menu by hitting the arrow key

fix(dropdowns): keep focus on multiselect input when navigating previous item

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/DrawerModal/DrawerModal.tsx
packages/modals/src/elements/TooltipModal/TooltipModal.tsx

In the `react-modals` Storybook migration PR #910, I noticed some prop types checks are missing. I wanted to keep the Storybook PR labeled as documentation, I am opening this PR up to add the missing prop type checks.

feat(modals): add prop type checks

---

package.json
yarn.lock

There is a duplicate version of React causing the `storybook` build to fail. Upgrade our `React` dependency brings it in line with the valid range of the other `@storybook/*` dependencies.

chore(deps): update react

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/accordion/Accordion.tsx
packages/accordions/src/elements/accordion/components/Panel.tsx
packages/accordions/src/styled/accordion/StyledInnerPanel.spec.tsx
packages/accordions/src/styled/accordion/StyledInnerPanel.ts
packages/accordions/src/styled/accordion/StyledPanel.spec.tsx
packages/accordions/src/styled/accordion/StyledPanel.ts
packages/accordions/src/utils/useAccordionContext.ts
packages/accordions/stories/examples/Uncontrolled.tsx

This PR adds an `isAnimated` prop which allows consumers to disable accordion panel transitions.
In order to transition accordion panels, the component must know the `height` so that it can transition to and from that `height`. This becomes very difficult when content is loaded asynchronously. The solution for this problem would be to dynamically load the accordion-based on when the content is ready.
In certain circumstances, this may prove challenging due to the context in which the `Accordion` is used. Turning animation off may be helpful in these circumstances.
Please see "View Deployment" link and navigate to the `Accordion` Storybook. There should be an `isAnimated` Storybook control.
Alternatively, navigate directly to the Storybook: …

feat(accordions): allow animation to be turned off

---

packages/typography/.size-snapshot.json
packages/typography/src/elements/Blockquote.spec.tsx
packages/typography/src/elements/Blockquote.tsx
packages/typography/src/elements/Paragraph.spec.tsx
packages/typography/src/styled/StyledBlockquote.spec.tsx
packages/typography/src/styled/StyledBlockquote.ts
packages/typography/src/styled/StyledParagraph.spec.tsx
packages/typography/src/styled/StyledParagraph.ts
packages/typography/stories/2-Blockquote.stories.tsx

- Add `size` to `Blockquote`
- Handle margining between interleaved paragraphs and blockquotes

feat(typography): add Blockquote size prop to control sibling spacing

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/common/StyledField.ts

Prevents absolutely-positioned contents (i.e. Checkbox, Radio, Toggle) from drifting out-of-bounds and affecting overflow. Restores the CSS from https://github.com/zendeskgarden/css-components/blob/53947ce7cdea07b0447c71eccfb2cf6c1e3f86a9/packages/forms/src/_checkbox/_base.css#L30-L35, etc.
closes #938 

fix(forms): restore relative positioning context on Field container

---

.circleci/config.yml
.storybook/gardenTheme.js
.storybook/preview.js

- https://github.com/storybookjs/storybook/issues/13017
- https://github.com/storybookjs/storybook/issues/12111
- respect O/S light v. dark mode
Accordingly, the `--no-dll` hack should be unnecessary with Storybook v6.1.

chore: fix production storybook navigation

---

package.json
yarn.lock

Ensure jest is able to finish test runs in all environments. Related to https://github.com/facebook/jest/issues/10777

fix(build): ensure jest is able to run tests in all environments

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/examples/advanced-select.md
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns/src/elements/Select/Select.spec.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx

This PR enables the item selection in all Dropdown components using the `tab` key. This logic is similar to the current "filter" ability in `Menu` and `Select`.

fix(dropdowns): ensure Tab key selects highlighted items

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx

This PR allows Voiceover users in Safari to use the `space` key while filtering and selecting content within the `react-dropdowns` package.

feat(dropdowns): ensure dropdowns allow space key in Safari with voiceover

---

packages/dropdowns/README.md

Updating an old `arrow` reference from the dropdowns README.
Closes #945

chore(docs): update Menu arrow usage

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns/src/elements/Select/Select.spec.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/elements/Trigger/Trigger.spec.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx

Revert #942 due to unintentional item selection when `defaultHighlightedIndex` is provided.

fix(dropdowns): revert tab selection #943

---

packages/chrome/src/elements/Chrome.tsx
packages/chrome/src/elements/body/Body.tsx
packages/chrome/src/elements/header/HeaderItem.tsx
packages/chrome/src/elements/nav/Nav.tsx
packages/chrome/src/elements/nav/NavItem.tsx
packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
packages/chrome/src/elements/subnav/SubNavItem.tsx
packages/chrome/src/styled/header/StyledBaseHeaderItem.ts
packages/chrome/src/styled/header/StyledHeader.ts
packages/chrome/src/styled/header/StyledHeaderItemText.ts
packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
packages/chrome/src/styled/nav/StyledNavItemText.ts
packages/chrome/src/styled/subnav/StyledSubNavItemText.ts

Updates chrome package element prop docs

chore(chrome): update prop descriptions

---

packages/tables/.size-snapshot.json
packages/tables/examples/basic.md
packages/tables/src/elements/Row.spec.tsx
packages/tables/src/elements/Row.tsx
packages/tables/src/elements/Table.tsx
packages/tables/src/styled/StyledRow.ts
packages/tables/src/utils/useTableContext.ts

This PR introduces a new `isReadOnly` prop to the `Table` component. This prop removes the hover/focus styling and logic from `Row` elements when provided.

feat(tables): introduce read-only styling

---

packages/accordions/src/elements/accordion/components/Label.tsx
packages/accordions/src/elements/stepper/components/Step.tsx
packages/avatars/src/elements/Avatar.tsx
packages/buttons/src/elements/Button.tsx
packages/chrome/src/elements/header/HeaderItemIcon.tsx
packages/chrome/src/elements/nav/NavItemIcon.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Menu/Items/AddItem.tsx
packages/dropdowns/src/elements/Menu/Items/HeaderIcon.tsx
packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
packages/dropdowns/src/elements/Menu/Items/Item.tsx
packages/dropdowns/src/elements/Menu/Items/ItemMeta.tsx
packages/dropdowns/src/elements/Menu/Items/MediaBody.tsx
packages/dropdowns/src/elements/Menu/Items/MediaFigure.tsx
packages/dropdowns/src/elements/Menu/Items/MediaItem.tsx
packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
packages/dropdowns/src/elements/Menu/Items/PreviousItem.tsx
packages/dropdowns/src/elements/Menu/Menu.tsx
packages/dropdowns/src/elements/Menu/Separator.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx
packages/forms/src/elements/MultiThumbRange.tsx
packages/loaders/src/elements/Progress.tsx
packages/tooltips/src/elements/Tooltip.tsx
packages/typography/src/elements/Code.tsx
packages/typography/src/styled/StyledCode.ts

- Add missing `@extends` clauses
- Fix misplaced `@extends` JSDoc blocks (not being picked-up by docgen)
- Improve subcomponent type definitions

chore: add missing and fix existing @extends clauses

---

packages/modals/src/index.ts

This PR exports the `GARDEN_PLACEMENT` type for consumers to use. This export matches packages that do the same, such as `react-dropdowns` and `react-datepickers`.

feat(modals): export placement type for tooltip modal

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/styled/select/StyledInput.ts
packages/tables/examples/scrollable-table.md

We have found that when `Dropdowns` (mostly `Trigger`) are used within a `Table` component we see additional scroll space and scrolling issues when dropdowns are interacted.
https://codesandbox.io/s/brave-cray-7yzwt?file=/src/App.js
During the investigation, I found the culprit was our hidden `<input />` that is included for a11y and Downshift reasons. The `position: absolute` value works as intended in standard flows, but placing it within a `td` or `th` element resets this positioning.
To maintain styling across standard page layouts and table usages I have moved this to `position: fixed`.
I looked into different approaches of apply `position: relative` to the table cell and content, but all solutions required a wrapping `<div>` as well as complications for positioning the menu within …

fix(dropdowns): allow menu usage in table elements

---

utils/build/styled.d.ts

#996 found that our TS declarations are including their relative path (including package name) inside their type directories.
I was able to trace this back to #984 [specifically this change](https://github.com/zendeskgarden/react-components/commit/4c75d91272216a8ed02681851a902ccd6cc6af7f#diff-e381f7475150ea1e1c7ffd6575dc1e88fca2d215fb8c452195e393c853e18dd8R9).
By referencing the `*.ts` file (`/src`) rather than the compiled `dist` this is changing the declaration paths somehow. By updating this reference the TS declarations have the expected structure.

fix(build): ensure typescript declarations are built with correct path

---

packages/accordions/.size-snapshot.json
packages/accordions/src/styled/accordion/StyledButton.ts
packages/accordions/src/styled/accordion/StyledRotateIcon.spec.tsx
packages/accordions/src/styled/accordion/StyledRotateIcon.ts

@m-lai noticed that the current `Accordion.Label` is showing the default button text color. This header color should be `GREY-800`.
I've updated the color logic to include the themed foreground color by default.

fix(accordions): correct default color of accordion labels

---

packages/chrome/.size-snapshot.json
packages/chrome/src/styled/StyledSkipNav.ts

The `SkipNav` uses `clip: rect(0, 0, 0, 0)` to accessibly hide the element when not in focus. I discovered that browsers are unable to animate between `rect` values and `auto` – effectively defeating the intended fade out transition animation. I've applied a ginormous `rect` value on focus so that the opacity fade out can be triggered and the element subsequently clipped from view or any interaction.

fix(chrome): enable SkipNav fade out transition animation

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/styled/StyledButtonGroup.spec.tsx
packages/buttons/src/styled/StyledIconButton.spec.tsx
packages/buttons/src/styled/StyledIconButton.ts

This PR is comprised of a bit of design rationale combined with dev rationale.
**Design rationale**
- Disabled icon buttons should reflect enabled icon buttons.
- Icon buttons don’t have a background when enabled, and they should not suddenly get a background when disabled. It would throw off our language around icon buttons if they suddenly got a heavy background.
- Garden icon buttons in split buttons do get a background, so they should still have a background when disabled.
**Dev rationale**
Since added state combinations are available on the code side, the design rationale is enhanced with:
- if the button isPrimary, we’ll retain the grey-200 disabled background
- if the button participates within any grouping (`GroupButton` or `SplitButton`), we’ll retain the grey-200 disabled …

fix(buttons): disabled IconButton background color

---

utils/scripts/tag.js

When updating `commander` I missed some breaking changes in our `yarn run tag` logic. This PR allows the options to be read successfully when cutting new versions.

fix(build): allow version tagging process to complete

---

packages/typography/.size-snapshot.json
packages/typography/package.json
packages/typography/src/elements/CodeBlock.spec.tsx
packages/typography/src/elements/CodeBlock.tsx
packages/typography/src/styled/StyledCodeBlock.ts
packages/typography/src/styled/StyledCodeBlockContainer.spec.tsx
packages/typography/src/styled/StyledCodeBlockContainer.ts
packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
packages/typography/src/styled/StyledCodeBlockLine.ts
packages/typography/src/styled/index.ts
packages/typography/stories/3-CodeBlock.stories.tsx
packages/typography/yarn.lock

- adds a new `highlightLines` prop for specifying an array of lines to highlight
- while restructuring the component, I discovered the a11y need for [scrollable region focus](https://dequeuniversity.com/rules/axe/4.1/scrollable-region-focusable) if the code content exceeds the boundaries of the code block container; a `tabindex` is now applied accordingly
@steue in the situations where the `CodeBlock` allows keyboard focus, I've applied our standard `box-shadow` treatment. Please double-check that this maps to design intent. :pray:
The `ScrollableRegionFocusable` logic needs to be pulled out into a new `react-containers` hook.

feat(typography): add line highlighting to CodeBlock component

---

packages/typography/.size-snapshot.json
packages/typography/src/elements/lists/OrderedList.spec.tsx
packages/typography/src/elements/lists/OrderedListItem.spec.js
packages/typography/src/elements/lists/OrderedListItem.tsx
packages/typography/src/elements/lists/UnorderedList.spec.js
packages/typography/src/elements/lists/UnorderedListItem.spec.js
packages/typography/src/elements/lists/UnorderedListItem.tsx
packages/typography/src/styled/StyledListItem.spec.tsx
packages/typography/src/styled/StyledListItem.ts
packages/typography/stories/13-OrderedList.stories.tsx
packages/typography/stories/14-UnorderedList.stories.tsx

This cleaner implementation ends up addressing a bug where `<div>` padding was piling up, resulting in large padding when a list popped out from nesting.
Additionally, the storybook demo has been restored with previous Styleguidist controls behavior so we can stress test these components going forward.

fix(typography): simplify DOM structure for list components

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/stepper/components/Step.spec.tsx
packages/accordions/src/elements/stepper/components/Step.tsx

In [React.StrictMode](https://reactjs.org/docs/strict-mode.html), components are rendered twice. This causes the `Label` in the `Stepper` to go up in twos (e.g. step 2, 4, 6  instead of 1, 2, 3), which is undesired behaviour.
> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
> 
> * Class component constructor, render, and shouldComponentUpdate methods
> * Class component static getDerivedStateFromProps method
> * Function component bodies
> * State updater functions (the first argument to setState)
> * Functions passed to useState, useMemo, or useReducer
This change uses useEffect to increment/ decrement the value as the component is …

fix(accordions): Stop stepper's counter incrementing twice in React.StrictMode

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledIconButton.ts

Should retain `dangerHue` by preventing `neutralHue` overrides.

fix(buttons): danger IconButton foreground color styling

---

packages/tables/.size-snapshot.json
packages/tables/src/elements/Row.spec.tsx
packages/tables/src/elements/Row.tsx

The `isReadOnly` prop for `react-tables` is experiencing a bug where a nested focusable element can still propagate focus styling. This PR ensures that the controlled `isFocused` state on a row is computed correctly.
It now:
- Respects any directly controlled (non-undefined) value provided to the `Row`
- Disables focus styling if `isReadOnly` is provided to `Table`
- Renders `isFocused` based on the current focus state

fix(tables): ensure readonly tables don't show focus treatment

---

packages/modals/package.json
packages/modals/yarn.lock

This PR upgrades `@zendeskgarden/container-modal` to the latest version. The latest version includes a fix (https://github.com/zendeskgarden/react-containers/pull/270) that ensures modals are not closed when click originates within modals.

chore(modals): upgrade container-modal version

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/TooltipModal/TooltipModal.tsx
packages/modals/src/styled/StyledTooltipModal.ts
packages/modals/src/styled/StyledTooltipModalBackdrop.ts
packages/modals/stories/4-TooltipModal.stories.tsx

This PR fades out the tooltip modal using `react-transition-group`.  
Tooltip modals with the `isAnimated` prop hook into `react-transition-group`'s exit transition state and transitions the opacity to `0`. The outcome is that the fade-out transition is achieved without any API changes for the end consumers. There are edge cases where dynamic modal content could change immediately `onClose`, but this can be handled by consumers.
~- [ ] :guardsman: includes new unit tests~

fix(modals): fadeout tooltip modal

---

packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx

This PR fixes a broken test in the `react-colorpickers` package.
It looks like some assertions occur immediately after a color dialog is dismissed. I've updated the test to use `waitForElementToBeRemoved` prior to making assertions against elements that don't exist anymore (after the dialog is closed).

fix(colorpickers): fix broken color picker dialog test

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/package.json
packages/colorpickers/yarn.lock

Puts dependencies in the right place and with the right versions.
Notice the `buttons` move has a substantial positive impact on the bundle size.

fix(colorpickers): move react-buttons to a direct dependency

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/elements/Colorpicker/index.tsx
packages/colorpickers/src/elements/ColorpickerDialog/index.tsx

The hex input should not suggest spelling corrections.
Set `hasArrow` to `false` in order to override `TooltipModal` default.

fix(colorpickers): disable hex spell checking and arrow by default

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/styled/Colorpicker/StyledSliders.ts

This small change prevents the `Field`-wrapped range inputs from adding subpixel height. With `bedrock` enabled, these fields are currently bumping to `22.33px`. This change constrains the height to the expected `22px`.

fix(colorpickers): prevent subpixel slider height increase

---

packages/modals/.size-snapshot.json
packages/modals/src/styled/StyledTooltipModal.ts

The arrow should mimic the `large` styling on Tooltip. This eliminates the odd border break currently seen in production.
https://github.com/zendeskgarden/react-components/blob/b24b687152095a887f11697e48da9d5c93f5c694/packages/tooltips/src/styled/StyledTooltip.ts#L82-L100

fix(modals): TooltipModal arrow styling

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/package.json
packages/colorpickers/src/elements/Colorpicker/ColorWell.tsx
packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
packages/colorpickers/stories/examples/ColorpickerDialog/WithIconButton.tsx
packages/modals/.size-snapshot.json
packages/modals/src/elements/TooltipModal/TooltipModal.tsx
packages/tooltips/.size-snapshot.json
packages/tooltips/package.json
packages/tooltips/src/elements/Tooltip.tsx
packages/tooltips/yarn.lock

* Fixes the color well issue where the dialog is closed after selecting the color well.
* Fixes `ref` override in `Tooltip` 
* Persist mouse event for React v16x consumers
* Adds a tooltip example to the icon button color dialog example. 
~- [ ] :ok_hand: design updates are Garden Designer approved (add the
~- [ ] :guardsman: includes new unit tests~

fix(colorpickers|tooltips): color well and tooltip fixes

---

packages/dropdowns/package.json

Update the peer dependencies within `react-dropdowns` to include React and ReactDom v17. This package was missed in the initial v17 upgrade.
Relates to #1038

fix(deps): update dropdowns peer dependencies to include React v17

---

packages/colorpickers/package.json
packages/colorpickers/yarn.lock

Add missing `react-popper` needed by https://github.com/zendeskgarden/react-components/blob/main/packages/colorpickers/src/elements/ColorpickerDialog/index.tsx.

fix(colorpickers): add missing popper dependency

---

packages/colorpickers/package.json

Resolves the following install warning:
```
@zendeskgarden/react-colorpickers > react-popper@2.2.3" has unmet peer dependency "@popperjs/core@^2.0.0
```

fix(colorpickers): add missing react-popper peer dependency

---

.storybook/preview-head.html
.storybook/preview.js

Prevent zendeskgarden/css-components#326 from nuking the storybook stylesheet link.

chore(docs): use evergreen bedrock CSS link

---

.storybook/preview.js
packages/accordions/.size-snapshot.json
packages/accordions/src/styled/accordion/StyledButton.ts
packages/accordions/src/styled/stepper/StyledIcon.spec.tsx
packages/accordions/src/styled/stepper/StyledIcon.ts
packages/accordions/src/styled/stepper/StyledInnerContent.ts
packages/accordions/src/styled/stepper/StyledLabel.spec.tsx
packages/accordions/src/styled/stepper/StyledLabel.ts

A selection of `Stepper` and `Accordion` styling was either relying on the cascade or outright missing specified color, font, and line-height styling. Also preferred the `props.theme.colors.foreground` key where applicable. I removed global storybook styling that was masking differences between bedrock/non-bedrock CSS.

fix(accordions): stepper and accordion typeface styling

---

packages/modals/.size-snapshot.json
packages/modals/src/styled/StyledTooltipModalBackdrop.ts

Applies CSS (`pointer-events: none;`) to the tooltip modal backdrop when a user dismisses the tooltip modal. This allows elements underneath the tooltip modal to be interactive during the trade-out transition.
I've dialed up the fade-out transition speed to three seconds in a temporary demo to showcase a slowed-down version of the user-interaction: [color dialog](https://nostalgic-sinoussi-4e909a.netlify.app/?path=/story/components-colorpickers-colorpickerdialog--uncontrolled) and [tooltip modal](https://nostalgic-sinoussi-4e909a.netlify.app/?path=/story/components-modals-tooltipmodal--default).

fix(modals): allow pointer-events to pass through fading tooltip modal

---

packages/modals/package.json
packages/modals/yarn.lock

Upgrades `@zendeskgarden/container-modal` to latest version. This addresses a bug where choosing a `Select` option within a modal dismisses the modal.
Verified locally that choosing a `Select` option within a modal no longer dismisses the modal.

chore(modals): upgrade container-modal

---

packages/modals/package.json
packages/modals/yarn.lock

Remove the `@types/react-transition-group` that already exists in `devDependencies`.

chore(modals): remove @types/react-transition-group direct dependency

---

packages/modals/README.md

This PR updates the modals `README` example to use correct prop names.

chore(modals): update README example to use correct props

---

packages/modals/package.json
packages/notifications/.size-snapshot.json
packages/notifications/src/elements/toaster/ToastProvider.spec.tsx
packages/notifications/src/elements/toaster/ToastProvider.tsx
packages/notifications/src/elements/toaster/ToastSlot.tsx
packages/notifications/src/elements/toaster/useToast.spec.tsx

This PR adds the ability to apply custom props (and styles) to individual placement slots in the `Toast` notification. This can help with custom positioning if required by consumers.

feat(notifications): allow placement customizations for toast

---

.storybook/preview.js
packages/dropdowns/src/styled/select/StyledFauxInput.ts

Adds the ability to toggle a component's primary hue – intended for debugging wrapped `dropdowns` components, etc.
This tool really needed the `paintbrush` icon, so I stole it from Bedrock which was replaced with `link`. For consistency I'll update `ckeditor` and `css-components` accordingly after this PR.

chore: add "primary hue" tool to storybook

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/styled/select/StyledFauxInput.ts

The primary hue color picker addition to the website exposed that dropdown components are not picking up anything beyond the `DEFAULT_THEME`. This PR addresses that issue.

fix(dropdowns): ensure current theme is passed to underlying FauxInput

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/styled/Colorpicker/StyledAlphaRange.ts
packages/colorpickers/src/styled/Colorpicker/StyledHueRange.ts
packages/colorpickers/src/styled/common/StyledRange.ts
packages/forms/.size-snapshot.json
packages/forms/src/elements/Range.tsx
packages/forms/src/styled/range/StyledRangeInput.ts

Allow `Colorpicker` to remove competing `background` CSS from underlying `Range` components.
@austingreendev this should clear the way for #1051.

chore(forms, colorpickers): provide mechanism for removing Range lower track

---

packages/notifications/.size-snapshot.json
packages/notifications/package.json
packages/notifications/src/elements/toaster/useToast.ts
packages/notifications/yarn.lock

It seems like `nanoid` is causing Storybook to be in a perpetual loading state in Internet Explorer 11. A perpetual loading state can be reproduced locally and in production in IE11.
This PR replaces `nanoid` usages with `react-uid` so that Storybook can be loaded on IE11. 

fix(notifications): use IE11 compatible react-uid

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/elements/ColorpickerDialog/index.spec.tsx
packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
packages/colorpickers/stories/examples/ColorpickerDialog/Controlled.tsx
packages/colorpickers/stories/examples/ColorpickerDialog/Uncontrolled.tsx

This change allows consumers to pass props to the color dialog trigger element. Useful for passing `aria-label` and other props to the trigger element.

fix(colorpickers): allow props to be applied to color dialog trigger

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/styled/ColorpickerDialog/StyledTooltipModal.ts

The color picker dialog's tooltip modal `width` should be prioritized over the default tooltip modal `width`.

fix(colorpickers): override tooltip modal width

---

package.json
packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/styled/Colorpicker/StyledSliders.ts

While exploring a `website` z-index issue, I discovered that a parent's position (relative, absolute) can impact the positioning of range sliders within the colorpicker. Here is an example where I'm clearing `position: relative;` on the parent `Field`. Note that the sliders bump down.

fix(colorpickers): stabilize slider position styling

---

packages/dropdowns/yarn.lock

The downshift library released a [bug fix](https://github.com/downshift-js/downshift/pull/1264) in version `6.1.3` (Zendesk contribution 🎉 ).  
This PR updates the (outdated) `yarn.lock` file in `dropdowns` by running `yarn install`. Then it brings `downshift` to version `6.1.3` with `yarn upgrade downshift`. Both commands are ran in the `package/dropdowns` directory.

chore(dropdowns): update lock & upgrade downshift

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Combobox/Combobox.tsx
packages/dropdowns/stories/examples/Autocomplete/Default.tsx
packages/dropdowns/stories/examples/Combobox/Default.tsx
packages/dropdowns/stories/examples/Menu/Default.tsx
packages/dropdowns/stories/examples/Menu/Icon.tsx
packages/dropdowns/stories/examples/Multiselect/Default.tsx
packages/dropdowns/stories/examples/Select/Advanced.tsx
packages/dropdowns/stories/examples/Select/Default.tsx

The original intent of this PR was to add `isOpen` controls for debugging storybook dropdown demos. However, it brought to light a missing `useEffect` on `Combobox` for focusing the input when `isOpen` is set to true.

fix(dropdowns): handle combobox controlled open

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButton.ts
packages/forms/.size-snapshot.json
packages/forms/src/styled/input-group/StyledInputGroup.ts
packages/forms/src/styled/text/StyledTextInput.ts
packages/forms/stories/13-InputGroup.stories.tsx

Finesse `z-index` transitions for `InputGroup` and `ButtonGroup`.

fix(forms, buttons): finesse component group z-index transitions

---

packages/chrome/.size-snapshot.json
packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx
packages/chrome/stories/examples/Default.tsx

The `CollapsibleSubNavItem` is not correctly recalculating its `maxHeight` when it's children updates.
I've updated `CollapsibleSubNavItem` to recalculate its `maxHeight` when children changes. Also, introduced a new `itemCount` Storybook knob to help visualize the fix. Fixes https://github.com/zendeskgarden/react-components/issues/1090.
**BEFORE:**
**AFTER:**

fix(chrome): recalculate height of subnavs when children change

---

packages/typography/.size-snapshot.json
packages/typography/package.json
packages/typography/src/elements/CodeBlock.tsx
packages/typography/yarn.lock

This PR refactors the `CodeBlock` to use the `useScrollRegion` [hook](https://zendeskgarden.github.io/react-containers/?path=/docs/scrollregion-container--container).

chore(typography): use scroll region hook for code block

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/timeline/Timeline.tsx
packages/accordions/src/elements/timeline/components/Content.tsx
packages/accordions/src/elements/timeline/components/Item.tsx
packages/accordions/src/elements/timeline/components/OppositeContent.tsx
packages/accordions/src/index.ts
packages/accordions/src/styled/index.ts
packages/accordions/src/styled/timeline/StyledCircleStrokeIcon.ts
packages/accordions/src/styled/timeline/StyledContent.ts
packages/accordions/src/styled/timeline/StyledItem.spec.tsx
packages/accordions/src/styled/timeline/StyledItem.ts
packages/accordions/src/styled/timeline/StyledOppositeContent.spec.tsx
packages/accordions/src/styled/timeline/StyledOppositeContent.ts
packages/accordions/src/styled/timeline/StyledSeparator.ts
packages/accordions/src/styled/timeline/StyledTimeline.ts
packages/accordions/src/utils/index.ts
packages/accordions/src/utils/useTimelineContext.spec.tsx
packages/accordions/src/utils/useTimelineContext.ts
packages/accordions/src/utils/useTimelineItemContext.spec.tsx
packages/accordions/src/utils/useTimelineItemContext.ts
packages/accordions/stories/4-Timeline.stories.tsx

This pull request introduces a new `Timeline` component as described by internal RFC and Figma assets.
The `Timeline` component is used to render a list of chronological events. The `Timeline` component can be composed with other UIs to form more complex user experiences. For (unofficial) example, consumers can wrap [timeline items in tooltips](https://timeline-composition.netlify.app/iframe.html?id=components-accordions-timeline--default&args=&viewMode=story). Or they can place accordions, tabs, tables, etc. in timeline items. These higher level implementations are feature specific and is left as an exercise for the consumer at this time.

feat(accordions): create new timeline component

---

packages/dropdowns/package.json
packages/dropdowns/yarn.lock
packages/forms/.size-snapshot.json
packages/forms/package.json
packages/forms/src/elements/file-list/FileList.tsx
packages/forms/src/elements/file-list/components/Close.tsx
packages/forms/src/elements/file-list/components/File.tsx
packages/forms/src/elements/file-list/components/Item.tsx
packages/forms/src/elements/file-list/utils.tsx
packages/forms/src/index.ts
packages/forms/src/styled/file-list/StyledClose.ts
packages/forms/src/styled/file-list/StyledFile.ts
packages/forms/src/styled/file-list/StyledFileList.ts
packages/forms/src/styled/file-list/StyledFileListItem.ts
packages/forms/src/styled/file-list/StyledIcon.ts
packages/forms/src/styled/index.ts
packages/forms/stories/14-FileUpload.stories.tsx
packages/forms/stories/16-FileList.stories.tsx
packages/forms/yarn.lock

This pull request introduces a new `FileList` and `File` component in the `@zendeskgarden/forms` package. The component can be used to render a list of files, and can be used alongside the `FileUpload` component to build a complete file uploading experience.
Please see the accompanying (internal) file list RFC and Figma assets.
The `FileList` component shows a list of (uploaded) files. Consumers may use it with a `Progress` component from Garden's `@zendeskgarden/loaders` package. The `FileUpload` story demonstrates this.
Explore the demo using the bottom-most "View Deployment" link.  The file upload story can be compared to the current production story [here](https://zendeskgarden.github.io/react-components/?path=/story/components-forms-fileupload--default). The `FileList` and `File` …

feat(forms): create file list component

---

packages/pagination/.size-snapshot.json
packages/pagination/src/styled/Pagination/StyledPageBase.ts

Fix for disabled pages showing a `pointer` cursor on hover and `background-color` transition not being correctly applied.

fix(pagination): page disabled and background color transition styling

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/styled/items/StyledItemIcon.ts
packages/dropdowns/stories/examples/Menu/Advanced.tsx

Add missing `data-garden-[id/version]` attributes to `StyledItemIcon` components.
Closes #1128

fix(dropdowns): add missing data-garden- attributes to menu item icon elements

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/input-group/InputGroup.spec.tsx
packages/forms/src/styled/input-group/StyledInputGroup.ts

Addresses the double-border problem seen when [this example](https://garden.zendesk.com/components/input-group#read-only) is launched in codesandbox. The CSS is re-ordered  and styling precedence isn't holding up.
**before**
**after**

fix(forms): input group `Button` margin override

---

docs/versioning.md
packages/tabs/.size-snapshot.json
packages/tabs/src/elements/Tabs.spec.tsx
packages/tabs/src/elements/Tabs.tsx

Despite best-practice documentation for adding a parent `ThemeProvider`, Garden components should be able to also render standalone.

fix(tabs): render without a `ThemeProvider`

---

.storybook/main.js

Adds a `BROWSER` environment variable check, that can be used to [disable Storybook docs-addon](https://storybook.js.org/docs/react/configure/babel) for localhost BrowserStack testing against IE11. Command usage shown below.
```sh
BROWSER=ie11 yarn start
```

chore(storybook): add browser env for disabling addon-docs

---

.github/renovate.json

Flatten packageRules and update field names
See https://github.com/renovatebot/renovate/discussions/11732

chore(renovate): refactor config

---

packages/tooltips/package.json
packages/tooltips/yarn.lock

A bug in the `useTooltip` hook was discovered (and fixed) in https://github.com/zendeskgarden/react-containers/pull/375. 
This PR pulls in the fix by upgrading `@zendeskgarden/container-tooltip` in the `tooltips` package.

chore(tooltips): update container-tooltip

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Dropdown/Dropdown.spec.tsx
packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns/stories/examples/Autocomplete/Default.tsx

Addresses a bug where the `value` of the `input` was cleared once the user blurred out of it, resulting in the screen reader not announcing the value even if there was a selection made and was visible to sighted users.
This PR rolls back part of the changes in [this PR](https://github.com/zendeskgarden/react-components/pull/747) that caused an a11y regression described in [this issue](https://github.com/zendeskgarden/react-components/issues/1167). We no longer clear out the input's value and let the user clear it out themselves if they so choose. This ensures that the `input` always accurately reflects the selected value when not in use and the result of the user's input when in use.
This means the autocomplete will have a slightly different (albeit arguably more desirable) behavior from …

fix(dropdowns): Ensure the input value is preserved and announced by screen readers

---

babel.config.js

Updates Babel config to remove warnings emitted by Babel during builds.
Updates `babel.config.js` for building the packages with:
`['@babel/plugin-proposal-private-property-in-object', { loose: true }]`
as part of the `plugins`. This removes emitted warnings between configuration
conflicts with the `loose` property. Also removed `'@babel/proposal-object-rest-spread'`
from being added explicitly since it is part of `@babel/preset-env`.

chore(babel): update config for private-property-in-object plugin

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/package.json
packages/colorpickers/src/elements/ColorSwatch/index.spec.tsx
packages/colorpickers/src/elements/ColorSwatch/index.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
packages/colorpickers/src/index.ts
packages/colorpickers/src/styled/ColorSwatch/StyledCell.ts
packages/colorpickers/src/styled/ColorSwatch/StyledCheckIcon.spec.tsx
packages/colorpickers/src/styled/ColorSwatch/StyledCheckIcon.ts
packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatch.ts
packages/colorpickers/src/styled/ColorSwatch/StyledIcon.ts
packages/colorpickers/src/styled/ColorSwatch/StyledSwatchButton.ts
packages/colorpickers/src/styled/ColorpickerDialog/StyledTooltipModal.ts
packages/colorpickers/src/styled/index.ts
packages/colorpickers/stories/4-ColorSwatch.stories.tsx
packages/colorpickers/stories/5-ColorSwatchDialog.stories.tsx
packages/colorpickers/stories/examples/ColorSwatch/Controlled.tsx
packages/colorpickers/stories/examples/ColorSwatch/Uncontrolled.tsx
packages/colorpickers/stories/examples/ColorSwatchDialog/Controlled.tsx
packages/colorpickers/stories/examples/ColorSwatchDialog/Uncontrolled.tsx
packages/colorpickers/stories/examples/ColorSwatchDialog/WithIconButton.tsx
packages/colorpickers/stories/examples/utils.ts
packages/colorpickers/yarn.lock

This pull request introduces two new components in the `colorpickers` package:
`ColorSwatch`:
`ColorSwatchDialog`:
The color swatch implements the `useGrid` hook (https://github.com/zendeskgarden/react-containers/pull/343) for WAI-ARIA specified [behavior](https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-for-layout-grids). Feel free to refer to Garden's internal RFC for architecture and design assets.
The props for `ColorSwatch` is similar to that of `useGrid`, and are mostly forwarded to `useGrid`. The `ColorSwatch` allows for both controlled and uncontrolled usages. Uncontrolled usages are driven by internal state. Uncontrolled usages can begin with an initial state by using the `defaultRowIndex`, `defaultColIndex`, `defaultSelectedRowIndex`, and `defaultSelectedColIndex` …

feat(colorpickers): introduce color swatch

---

packages/avatars/src/elements/Avatar.tsx
packages/avatars/src/index.ts
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Combobox/Combobox.tsx
packages/dropdowns/src/elements/Fields/Label.tsx
packages/dropdowns/src/elements/Menu/Items/HeaderItem.tsx
packages/dropdowns/src/elements/Menu/Menu.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns/src/elements/Select/Select.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx
packages/dropdowns/src/index.ts

Some developers need access to `ILabelProps` and `IAvatarProps` in order to extend them.
* exported `ILabelProps`
* exported `IAvatarProps`

fix(types): export IAvatarProps and ILabelProps

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/DrawerModal/DrawerModal.tsx

Fixes a bug on the `DrawerModal` component backdrop requiring two clicks to exit when the modal content body is clicked.
The `DrawerModal` backdrop would normally close the modal when clicked the first time, however when the `DrawerModal.Body` or anything for that matter that wasn't the backdrop was clicked, it would require two clicks on the backdrop to close the modal. This PR fixes the bug by structuring the DOM elements in a way where events are propagated in a hierarchical manner, eliminating the need to click twice, even after `DrawerModal` content is clicked.
~~- [ ] :ok_hand: design updates are Garden Designer approved (add the
~~- [ ] :guardsman: includes new unit tests~~

fix(modals): drawer modal backdrop required two clicks to close

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/styled/items/StyledItemMeta.ts

Until now, Garden's design opinion has been to hide `ItemMeta` when a `Menu` is rendered using `isCompact`. This PR updates the component to reflect current designs, which simply alter the line height based on default vs compact display.
**Before** (can be seen [here](https://zendeskgarden.github.io/react-components/?path=/story/components-dropdowns-menu--advanced&args=isCompact:true)):
**After (see PR staging deployment for details)**

fix(dropdowns): display compact menu `ItemMeta` info

---

packages/typography/.size-snapshot.json
packages/typography/src/elements/CodeBlock.spec.tsx
packages/typography/src/elements/CodeBlock.tsx

Updates the `language` prop to fall back to `'tsx'` if an unsupported language is provided. Testing shows that, as a superset of c-like + javascript + JSX + typescript Prism tokenization, `language-tsx` currently seems to provide decent highlighting for languages such as Swift or Kotlin.
Resolves #1217 

fix(typography): improve fallback handling for invalid `CodeBlock` language

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Menu/Menu.tsx

In several cases – `Select`, `Autocomplete`, `Multiselect` – a `Menu` must match the width of its corresponding control. This PR prevents the expense of the `width` calculation to only occur when a menu is showing.

fix(dropdowns): improve `Menu` performance by deferring `getBoundingClientRect` call

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/elements/ColorSwatch/index.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
packages/colorpickers/stories/examples/ColorSwatch/Controlled.tsx
packages/colorpickers/stories/examples/ColorSwatchDialog/Controlled.tsx
packages/colorpickers/stories/examples/ColorSwatchDialog/WithIconButton.tsx

It was discovered that the color swatch dialog needed to support no color selection. This PR updates the color swatch dialog to support no color selection by accepting `-1` indices.
Previously, passing `-1` indices would cause the component to throw an error, since doing a matrix look up (`matrix[-1][-1]`) is invalid. Now, the color swatch dialog handles `-1` indices to mean no selected color. The component now sets `undefined` as a selected color when it encounters `-1` indices. 
I've also updated the controlled and custom icon stories for color swatch dialog to showcase no color selection. There may need to be design follow-ups for this. At this time, color swatch dialog preview defaults to `#fff` when no color is selected. For the custom icon example, it's up to the consumer. In the …

fix(colorpickers): allow no selection on color swatch dialog

---

package.json
packages/forms/src/elements/MultiThumbRange.tsx
packages/modals/yarn.lock
packages/notifications/yarn.lock
packages/tables/yarn.lock
yarn.lock

It looks like there are build issues with PR #1231. The logs suggest that there are TypeScript compilation issues resulting from `@types/react` version mismatch.
It looks like the culprit is `@types/react-transition-group` which generates a `yarn.lock` file that requires the latest version of `@types/react`. This problem actually already exists in the `react-notifications` package *if* the package dependencies are upgraded. This PR should unblock the TypeScript build issues that are encountered in #1231.
To fix this issue, I ran `yarn upgrade` in relevant sub-package directories, and then brought the version of the root `@types/react` to match the `@types/react-transition-group` dependency (`@types/react@17.0.33`).
1) Checkout `main` branch + ensure fresh dependency install
2) Run `yarn …

chore(deps): align root and sub-package @types/react

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/elements/ColorSwatchDialog/index.spec.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx

The uncontrolled color swatch navigation does not work correctly after the first mount.
The updated grid indices from `ColorSwatch` component (`onChange`) are not stored in the `ColorSwatchDialog` component. As a result, the focus indices are reset to `0, 0` after the first mount and subsequent navigations may not work correctly.
1) Navigate to the uncontrolled [Storybook example](https://zendeskgarden.github.io/react-components/?path=/story/components-colorpickers-colorswatchdialog--uncontrolled)
2) Open the color swatch dialog 
3) Use arrow keys to select `Red-400`
4) Press `ESC` to close the dialog
5) Press `Enter` to open the dialog
6) Press left arrow key, and notice that the focus does not move ❌ 
**Before**:
**After**: 

fix(colorpickers): retain previous indices for uncontrolled color swatch

---

packages/loaders/.size-snapshot.json
packages/loaders/src/elements/Spinner.tsx
packages/loaders/src/styled/StyledLoadingPlaceholder.ts
packages/loaders/src/styled/StyledSVG.ts

We found a bug where Spinner Placeholder does not match the dimensions the loaded Spinner. By default Placeholder has a 1:0.9 aspect ratio using `em`s. However Spinner has a 1:1 aspect ratio. Also, the placeholder currently has `display: inline` which collapses the placeholder dimensions relative to the Spinner itself. The display mode `display: block` better fits this placeholder for a block based SVG spinner element. 
**Note:** For the screenshots below, I removed the `display: flex` from the Storybook as it masks the bug and matches more closely the [CodeSandbox that reproduces the problem](https://codesandbox.io/s/elated-dust-e8ypl). 

fix(spinner): fix placeholder proportions

---

.github/renovate.json
package.json
packages/accordions/yarn.lock
packages/avatars/yarn.lock
packages/breadcrumbs/yarn.lock
packages/buttons/yarn.lock
packages/chrome/yarn.lock
packages/colorpickers/yarn.lock
packages/datepickers/yarn.lock
packages/dropdowns/yarn.lock
packages/grid/yarn.lock
packages/loaders/yarn.lock
packages/modals/yarn.lock
packages/notifications/yarn.lock
packages/pagination/yarn.lock
packages/tables/yarn.lock
packages/tabs/yarn.lock
packages/tags/yarn.lock
packages/tooltips/yarn.lock
packages/typography/yarn.lock
packages/utilities/yarn.lock
utils/build/rollup.config.js

- set schedule to match internal documentation
- add yarn-deduplicate
I verified that Renovate is [correctly managing](https://github.com/zendeskgarden/react-components/pull/1193/files) package lockfiles. But [lerna publish](https://github.com/zendeskgarden/react-components/commit/9d9905a0496bd902ec67f08cc8de3514045110b2) is not.
- I added `lerna exec yarn install` to the `version` lifecycle in order to keep package lockfiles in sync
- I took the liberty of addressing the `preventAssignment` build warnings we've been seeing for a while

chore: update renovate configuration

---

package.json

Oops, moving a little too fast with #1234.

fix: duplicate characters in `version` script

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Menu/Items/AddItem.tsx
packages/dropdowns/src/elements/Menu/Items/NextItem.tsx
packages/dropdowns/src/elements/Menu/Items/PreviousItem.tsx

In general, Garden prefers exporting one JSX component per file for clarity and readability. This PR sweeps up a few exceptions in order to accommodate a bug with `react-docgen-typescript` that fails to parse the correct component `displayName` when there are multiple assignments within the file.
Merging this PR will allow
- future Renovate `react-docgen-typescript` updates used by the `cmd-docgen` command in [`@zendeskgarden/scripts`](https://github.com/zendeskgarden/scripts)
- dependency updates for [website](https://github.com/zendeskgarden/website)-generated documentation
See https://github.com/styleguidist/react-docgen-typescript/issues/395 for details

chore: remove multiple `displayName` assignments per file

---

package.json

Current script update is interfering with Lerna's `version` lifecycle. Moving to `preversion` (which unlinks Lerna's `bootstrap` package node_modules) is causing a test fail with `Combobox`. So, until we can take advantage of something like [`yarn install --mode update-lockfile`](https://github.com/yarnpkg/yarn/issues/5738#issuecomment-905943984), it will be on individual Garden devs to ensure that package `yarn.lock` files are kept in sync.

chore: remove version lifecycle package lockfile updates

---

package.json
packages/modals/yarn.lock
packages/notifications/yarn.lock
packages/tables/yarn.lock
yarn.lock

Updating `@types/react` for the project and various packages.
This PR updates to the latest `@types/react` that address the type errors encountered with earlier versions of the `@types/react` package in #1231; thanks to the efforts of @hzhu with #1232 we were able to pin point the problem.
After updating `@types/react`, `yarn upgrade` was ran in the packages that used the package.

chore(deps): update @types/react

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/accordion/Accordion.spec.tsx
packages/accordions/src/elements/accordion/Accordion.tsx
packages/accordions/stories/examples/Uncontrolled.tsx
packages/accordions/yarn.lock

This pull request allows an uncontrolled component to be configured with an initial state.

feat(accordions): add default expanded sections prop

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButton.ts

Garden `:focus-visible` polyfill is handled via the `ThemeProvider` allowing the `isLink` button to apply the desired styling on mouse vs. keyboard interaction based on the `data-garden-focus-visible` attribute. With this in place, we can override top-level [css-bedrock](https://github.com/zendeskgarden/css-components/tree/main/packages/bedrock) `:focus` styling by simply setting it back to the link's base color.

fix(buttons): do not persist link color on click

---

.husky/pre-commit
.lintstagedrc
packages/forms/.size-snapshot.json
packages/forms/src/elements/file-list/FileList.spec.tsx
packages/forms/src/elements/file-list/components/Close.spec.tsx
packages/forms/src/elements/file-list/components/Close.tsx
packages/forms/src/elements/file-list/components/Delete.spec.tsx
packages/forms/src/elements/file-list/components/Delete.tsx
packages/forms/src/elements/file-list/components/File.spec.tsx
packages/forms/src/elements/file-list/components/File.tsx
packages/forms/src/elements/file-list/components/Item.spec.tsx
packages/forms/src/elements/file-list/components/Item.tsx
packages/forms/src/elements/file-list/utils.tsx
packages/forms/src/styled/file-list/StyledFile.spec.tsx
packages/forms/src/styled/file-list/StyledFile.ts
packages/forms/src/styled/file-list/StyledFileClose.spec.tsx
packages/forms/src/styled/file-list/StyledFileClose.ts
packages/forms/src/styled/file-list/StyledFileDelete.spec.tsx
packages/forms/src/styled/file-list/StyledFileDelete.ts
packages/forms/src/styled/file-list/StyledFileIcon.spec.tsx
packages/forms/src/styled/file-list/StyledFileIcon.ts
packages/forms/src/styled/file-list/StyledFileList.spec.tsx
packages/forms/src/styled/file-list/StyledFileListItem.spec.tsx
packages/forms/src/styled/file-list/StyledFileListItem.ts
packages/forms/src/styled/file-upload/StyledFileUpload.ts
packages/forms/src/styled/index.ts
packages/forms/src/utils/useFileContext.ts
packages/forms/stories/14-FileUpload.stories.tsx
packages/forms/stories/16-FileList.stories.tsx
packages/forms/stories/story-types.ts

This PR adds the following enhancements to the `File`, `FileList`, and `FileUpload` components:
- feat: new `File.Delete` component
- feat: File `success` and `error` validation styling
- feat: File `generic` type addition
- fix: compact styling (icons and spacing)
- fix: styling support for FileUpload `min-height`

feat(forms): add File component enhancements

---

packages/buttons/src/elements/Anchor.tsx

Just removing a repeated word from the prop description.

fix(buttons): Remove repeated word from prop description

---

packages/chrome/.size-snapshot.json

Updating `chrome` size snapshot.
After the Sheet feature for `chrome` was merged, the snapshot caused the tests on `main` to fail. This fixes CI for the branch.

chore(chrome): update size snapshot

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/Datepicker/Datepicker.spec.tsx
packages/datepickers/src/elements/Datepicker/Datepicker.tsx

Remove Datepicker Calender DOM elements to gain a performance improvement when rendering the Datepicker many times in an experience.
* Added `isOpen || isVisible` logic similar to [Menu component](https://github.com/zendeskgarden/react-components/blob/main/packages/dropdowns/src/elements/Menu/Menu.tsx#L170).
* Brought up missing coverage to 100% on unit tests

fix(datepicker): remove calender dom elements when hidden

---

packages/grid/demo/grid.stories.mdx

After offline discussion we will document the `debug` toggle from Garden Grid in the `grid.stories.mdx` file. 

docs(grid): visualize with debug

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/radio/StyledRadioInput.spec.tsx
packages/forms/src/styled/radio/StyledRadioInput.ts
packages/forms/src/styled/toggle/StyledToggleInput.ts

This PR aims to hide the inputs that are part of the Checkbox, Radio, and Toggle components in a more inclusive way. This technique comes from Sara Soueidan via her blog post, “Inclusively Hiding & Styling Checkboxes and Radio Buttons:” [Hiding the checkboxes inclusively](https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/#hiding-the-checkboxes-inclusively).
As Sara articulates in her blog post, there are assistive technologies — such as TalkBack, on Android phones — that enable low-vision and blind users to explore the web by touch. As far as checkboxes and radio buttons go, this means that the actual, semantic HTML inputs need to be the same size (i.e., occupy the same space) as the decorative inputs, so that someone exploring by touch can feel …

feat(forms): hide semantic Radio, Checkbox, and Toggle inputs more inclusively

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Multiselect/Multiselect.spec.tsx
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx

Since #1176, some of Garden's dropdown behaviors have changed slightly. This pull request addresses a small difference in behavior for the `Multiselect` component which results in a bug for some consumers.
When consumers pass in an `onKeyDown` handler, it overrides Garden's internal `onKeyDown` [code](https://github.com/zendeskgarden/react-components/blob/main/packages/dropdowns/src/elements/Multiselect/Multiselect.tsx#L167-L174) causing problems searching the multiselect. One example is that the `Space` key is not registered. Try searching for an item with a space in [this example](https://codesandbox.io/s/pr-demo-g90in?file=/src/Example.tsx).
Although, consumers should use `onInputChange` as shown on the [API docs](https://garden.zendesk.com/components/multiselect#api), the …

fix(dropdowns): compose onKeyDown handler for multiselect

---

.github/renovate.json

This PR removes options from the Renovate config due to causing failures in our dependency update PRs.
Removes [`postUpdateOptions`](https://docs.renovatebot.com/configuration-options/#postupdateoptions) and [`postUpgradeTasks`](https://docs.renovatebot.com/configuration-options/#postupgradetasks) from the configuration since both are only meant to run in self-hosted instances.
Addresses [issue #13810](https://github.com/renovatebot/renovate/issues/13810) and [discussion #13903](https://github.com/renovatebot/renovate/discussions/13903). It turns out the two configuration options were ignored initially and now throw when used due to a recent change by Renovate.

chore(renovate): remove post updates from config

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/DatepickerRange/components/Calendar.tsx
packages/datepickers/src/elements/DatepickerRange/components/End.tsx
packages/datepickers/src/elements/DatepickerRange/components/Start.tsx

While updating the website to pull subcomponent data from v8.48.0 source, I discovered these were missed in my previous PR.
https://github.com/zendeskgarden/react-components/pull/1273

fix(datepickers): add missing DatepickerRange subcomponent display names

---

packages/pagination/src/elements/CursorPagination/components/Last.tsx
packages/pagination/src/elements/CursorPagination/components/Next.tsx
packages/pagination/src/elements/CursorPagination/components/Previous.tsx

The [docgen](https://github.com/zendeskgarden/scripts/tree/main/src/cmd/docgen#readme) tooling gets confused for where to extract JSDoc header info when there are multiple component exports in a file. This PR removes unused component `export`s.
Running `garden cmd-docgen --pretty` against the `CursorPagination` subcomponents...
**Before** missing "extends"
**After** restored "extends"

fix(datepickers): remove unused exports in order to generate subcomponent "extends" documentation

---

packages/chrome/src/elements/sheet/Sheet.tsx

This PR removes dangling asterisks from prop type description comment for the `Sheet` component.

chore(chrome/sheet): remove dangling asterisk from type description

---

.stylelintrc
package.json

This PR formats and corrects the `.stylelintrc` to use the correct JSON structure. The ignored files have been removed from the `lint:css` command in favor of the `.stylelintrc` config.

chore(stylelint): correct config and simplify css lint cmd

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/accordion/Accordion.tsx
packages/accordions/src/elements/stepper/Stepper.tsx

Garden does not use `defaultProps` to re-state intrinsic default values. Doing so results in a generated prop API that is harder to read and (in this case) displays invalid values (i.e. `"undefined"` string), seen here:
Storybook...
**BEFORE**
**AFTER**

fix(accordions): API prop defaults

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/elements/ColorSwatch/index.tsx
packages/colorpickers/src/styled/ColorSwatch/StyledSwatchButton.ts

Provide improved accessibility experience and render pointer cursor.

Update pointer and aria label for color chips

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/stepper/components/Step.tsx

Addresses the initial render flash bug within `Stepper` where all the `Label` would have `ActiveIndex` styling for a split second.
**useEffect**
**UseLayoutEffect**

fix(stepper): render flash

---

packages/modals/demo/stories/DrawerModalStory.tsx
packages/modals/demo/stories/ModalStory.tsx
packages/modals/src/elements/DrawerModal/DrawerModal.tsx
packages/modals/src/elements/Modal.tsx
packages/modals/src/elements/TooltipModal/TooltipModal.tsx
packages/modals/yarn.lock
tsconfig.json

Updates `container-modal` version and fixes the types for `onClose` handler by using types for synthetic events from React package. 
Previously, native event types were used in `react-containers`. Since event handlers are passed to React, native event types did not work and required some instances of casting types to `any`.
This is a follow-on fix after addressing the root type [issues](https://github.com/zendeskgarden/react-containers/pull/425) in react-containers.

fix(modals): update container-modal & types

---

packages/buttons/.size-snapshot.json
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/styled/StyledButtonGroup.spec.tsx

styled-components v5 introduced the `&&` pseudoselector and has refined what a `&` does. Read more about it [here](https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting). 
Some styles are broken due to new and refined behavior of `&&` and `&`. In this case, the intended styles aren't applied when the component (`StyledButton`)'s props change. To fix this, the `&&` is used to scope the CSS to the `StyledButton`. To better understand the scoping, it was helpful for me to compare the before/after hash structure in the CSS classes.
**BEFORE**: styles (e.g borders) are lost when `isPrimary` is toggled
**AFTER**: styles (e.g borders) are retained when `isPrimary` is toggled

fix(buttons): fix precedence boost style bug

---

packages/modals/.size-snapshot.json
packages/modals/src/styled/StyledModal.spec.tsx
packages/modals/src/styled/StyledModal.ts

The modal is not responsive and is cut off on small mobile devices.
This pull request fixes the issue by removing the non-static positioning and applying a width in a mobile-first, responsive design approach. The modal has a default `width: auto` and as users scale up, the explicit width for tablets + desktop sizes are applied. Width sizes on larger displays remain the same as they were before.
**BEFORE**: notice that a modal in iPhone(s) is cut off:
**AFTER**: notice that a modal in iPhone(s) is fully visible:
There might be additional style enhancements on mobile in a follow up PR.

fix(modals): use auto width for responsive layout

---

packages/chrome/.size-snapshot.json
packages/chrome/src/styled/sheet/StyledSheetClose.ts
packages/chrome/src/styled/sheet/StyledSheetHeader.ts
packages/modals/.size-snapshot.json
packages/modals/src/elements/Close.spec.tsx
packages/modals/src/elements/Close.tsx
packages/modals/src/elements/DrawerModal/Close.spec.tsx
packages/modals/src/elements/DrawerModal/Close.tsx
packages/modals/src/elements/DrawerModal/DrawerModal.tsx
packages/modals/src/elements/DrawerModal/Header.spec.tsx
packages/modals/src/elements/DrawerModal/Header.tsx
packages/modals/src/elements/Header.spec.tsx
packages/modals/src/elements/Header.tsx
packages/modals/src/elements/Modal.tsx
packages/modals/src/styled/StyledClose.ts
packages/modals/src/styled/StyledDrawerModalClose.spec.tsx
packages/modals/src/styled/StyledDrawerModalClose.ts
packages/modals/src/styled/StyledDrawerModalHeader.spec.tsx
packages/modals/src/styled/StyledDrawerModalHeader.ts
packages/modals/src/styled/StyledHeader.spec.tsx
packages/modals/src/styled/StyledHeader.ts
packages/modals/src/utils/useModalContext.ts

The `Modal` (and `DrawerModal`) `Header` overflows past the `Close` button, which causes the title text to overlap with the button.
This PR fixes a visual bug when the `Header` text is long enough to wrap. `padding` has been added to the `Header` element for the `Modal` and `DrawerModal` components, with respect to RTL.
Before:
After:

fix(modals): add padding to header when close button is present

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/DatepickerRange/DatepickerRange.tsx
packages/datepickers/src/elements/DatepickerRange/components/Calendar.tsx
packages/datepickers/src/elements/DatepickerRange/components/End.tsx
packages/datepickers/src/elements/DatepickerRange/components/Month.tsx
packages/datepickers/src/elements/DatepickerRange/components/Start.tsx
packages/datepickers/src/elements/DatepickerRange/utils/datepicker-range-reducer.ts
packages/datepickers/src/elements/DatepickerRange/utils/useDatepickerRangeContext.ts

This pull request fixes https://github.com/zendeskgarden/react-components/issues/1092 and https://github.com/zendeskgarden/react-components/issues/1174.
The `DatepickerRange` has state synchronization issues that can cause unintended consequences. React throws a  :warning: for this. 
I think this is happening:
Component A's `setState` call is called in component B's reducer function. React will not be able to deterministically update component A, while it is working on component B. For example, what if component B is unmounted — then component A's `setState` call is lost. And if component A is unmounted, React is calling `setState` on an unmounted component.
In the case of `DatepickerRage`, the consumer passes `setState` via `onChange`. This `onChange` is then called in …

fix(datepickers): fix React state synchronization bug

---

.lintstagedrc
.storybook/preview.js

Adds "Strict mode" to the Storybook toolbar for enabling/disabling a `React.StrictMode` story decorator. This is being added as a convenience for component testing purposes. Strict mode is disabled by default.
A couple of stories to try with strict mode enabled:
- Buttons ➡️ ButtonGroup
- Click on any button
- Result: 💥 
- Dropdowns ➡️ Menu
-  Use keyboard to navigate menu
- Result: all `Item` navigation requires two keystrokes instead of one
It seems that anything connected with `@zendeskgarden/containers-selection` is problematic with strict mode. But I'm sure there's more when we use this to gain in-depth insight into problematic, unsafe lifecycles.

chore(demo): add StrictMode decorator

---

packages/datepickers/.size-snapshot.json
packages/datepickers/src/elements/DatepickerRange/components/Calendar.tsx
packages/datepickers/src/elements/DatepickerRange/components/Month.tsx

Refactor to remove prop drilling values and use the values from context instead because drilled values come from context anyways.

refactor(datepickers): use context rather than prop drilling

---

packages/buttons/.size-snapshot.json
packages/buttons/src/elements/Anchor.tsx
packages/buttons/src/elements/Button.tsx
packages/buttons/src/elements/ButtonGroup.tsx
packages/buttons/src/elements/ChevronButton.tsx
packages/buttons/src/elements/IconButton.tsx
packages/buttons/src/elements/ToggleButton.tsx
packages/buttons/src/elements/ToggleIconButton.tsx
packages/buttons/src/elements/components/EndIcon.tsx
packages/buttons/src/elements/components/StartIcon.tsx
packages/buttons/src/index.ts
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/styled/StyledIconButton.ts
packages/buttons/src/types/index.ts

Standardize interface and type definitions to fix doc-generated API readability.
Marked `ButtonGroup` as `@deprecated` per [website](https://garden.zendesk.com/components/button-group#:~:text=This%20is%20a%20legacy%20component%20and%20may%20be%20deprecated%20in%20the%20future.%20Garden%20does%20not%20presently%20recommend%20the%20use%20of%20Button%20groups.)

fix(buttons): refactor types and interfaces

---

packages/buttons/demo/toggleButton.stories.mdx
packages/buttons/demo/toggleIconButton.stories.mdx
packages/chrome/demo/sheet.stories.mdx
packages/colorpickers/demo/colorSwatch.stories.mdx
packages/colorpickers/demo/colorSwatchDialog.stories.mdx
packages/forms/demo/fileList.stories.mdx
packages/modals/demo/drawerModal.stories.mdx
packages/typography/demo/blockquote.stories.mdx
packages/typography/demo/code.stories.mdx
packages/typography/demo/codeBlock.stories.mdx

The designers have been busy recovering missing component designs in Figma. This PR adds those quick reference links to Storybook.

chore(demo): add design links

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/stepper/components/Content.spec.tsx
packages/accordions/src/elements/stepper/components/Content.tsx

Screen readers read aloud hidden + inactive Stepper content.
This fix applies an `aria-hidden="true"` to inner content element of inactive steps. As a result, screen readers do not read aloud inactive step content.
1) Turn on VoiceOver
2) Navigate to the [Stepper story](https://zendeskgarden.github.io/react-components/?path=/story/packages-accordions-stepper--stepper)
3) Use the VO command + arrow keys to cursor around the Stepper widget
4) Notice that VoiceOver reads aloud Stepper content that is hidden (inactive step)

fix(accordions): hide inactive content from screen readers

---

docs/development.md
docs/documentation.md
docs/typescript.md
packages/.template/src/elements/{{capitalize component}}.tsx
packages/.template/src/index.ts
packages/.template/src/types/index.ts
packages/grid/src/types/index.ts
utils/scripts/new.js

This PR marks the final step for refactoring shared, exported types and interfaces across the codebase 🎉 .
- ensures new components started with `yarn new` follow the standard
- documents standard TypeScript rules for types and interfaces

chore: refactor template interface and add TypeScript documentation

---

packages/accordions/.size-snapshot.json
packages/accordions/demo/stepper.stories.mdx
packages/accordions/demo/stories/StepperStory.tsx
packages/accordions/src/elements/stepper/components/Label.tsx
packages/accordions/src/types/index.ts

Allow consumers to pass in props for the default completed (check) icon.
The default checked icon is currently not read aloud on screen readers. This PR creates a new prop so that the SVG icon element can be configured with the appropriate ARIA attributes. Alternatively, consumers can pass their own, fully configured icons, to the `icon` prop. We'll need to document both usages on the website.
Consumers can now configure the default check icon and **can make it available to screen readers**:
Note: I will update the website + packages to reflect these changes once all Level Access tasks related to accordions package have been addressed. But updated website documentation will probably require a new task.

feat(accordions): pass icon props to default check icon

---

packages/accordions/.size-snapshot.json
packages/accordions/src/styled/timeline/StyledItem.ts

Timeline font styling renders as expected without the presence of `css-bedrock`.
Themed styling is applied to item text, whether or not `css-bedrock` is present as a top-level CSS reset:
- `line-height`
- `color`
- `font-size`

fix(accordions): add missing `Timeline` text styling

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx

This PR adds `composeEventHandlers` for the `onKeyDown` event. 
This fixes an issue with `onKeyDown` being passed in as a prop and overriding what the `Autocomplete` component `onKeyDown` is doing:
```
(e: KeyboardEvent<HTMLDivElement>) => {
if (isOpen) {
(e.nativeEvent as any).preventDownshiftDefault = true;
}
}
```
Adding `composeEventHandlers` allows consumers to pass in their own `onKeyDown`.

fix(dropdowns): compose keydown for autocomplete

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx

This PR reorders when props are spread to prevent overwriting internally defined events.

fix(dropdowns): stop overwriting of autocomplete keydown event

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Multiselect/Multiselect.tsx

Fixed an antipattern where `document` is accessed directly in Multiselect component. Instead it should access document through `useDocument` via the Theme Context. 
~- [ ] :ok_hand: design updates are Garden Designer approved (add the
~- [ ] :globe_with_meridians: demo is up-to-date (`yarn start`)~
~- [ ] :arrow_left: renders as expected with reversed (RTL) direction~
~- [ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)~
~- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~
~- [ ] :guardsman: includes new unit tests~
~- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11~

fix(multiselect): add useDocument

---

packages/tables/.size-snapshot.json
packages/tables/src/elements/Row.tsx

fix(tables): remove redundant rendering of row component

---

.gitignore

This PR adds `demo/*` back into `.gitignore`.

chore(git): add demo to gitignore

---

packages/colorpickers/package.json

This PR removes `popper.js` v2 from dependencies as it is not needed.

chore(colorpickers): remove popper.js direct dependency

---

packages/grid/.size-snapshot.json
packages/grid/src/elements/pane/components/Splitter.tsx
packages/grid/src/elements/pane/components/SplitterButton.tsx
packages/grid/src/styled/pane/StyledPaneSplitter.ts
packages/grid/src/styled/pane/StyledPaneSplitterButton.ts
packages/grid/src/utils/usePaneSplitterContext.ts

- Add missing drop shadow
- Distinguish mouse action from underlying splitter
- Hide button when splitter becomes too small to display

fix(grid): address splitter button design and interaction issues

---

.lintstagedrc

Adds `--passWithNoTests` flag to `jest` command when `lint-staged` is ran.

chore(lint-staged): update jest to pass with no tests

---

.storybook/main.js
package.json
yarn.lock

This PR removes `eslint` from running when `storybook` is building.

chore(storybook): remove eslint from webpack config

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Autocomplete/Autocomplete.spec.tsx
packages/dropdowns/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns/src/elements/Combobox/Combobox.spec.tsx
packages/dropdowns/src/elements/Combobox/Combobox.tsx

This PR has a fix for the `Enter` key firing `downshift.js` callbacks in the `Autocomplete` and `Combobox` components.
This PR addresses two instances of when the `Enter` key would fire `downshift` callbacks twice:
- `Autocomplete`: would fire `onStateChange` twice
- `Combobox`: would fire `onSelect` twice

fix(dropdowns): prevent enter key from firing callbacks twice

---

packages/forms/.size-snapshot.json
packages/forms/package.json
packages/forms/src/elements/Input.tsx
packages/forms/src/elements/common/Field.spec.tsx
packages/forms/src/elements/common/Field.tsx
packages/forms/src/elements/common/Hint.tsx
packages/forms/src/elements/common/Message.tsx
packages/forms/src/utils/useFieldContext.ts
packages/forms/yarn.lock

This PR adds the `Message` component ID in the `aria-describedby` attribute for a given `Input` (`Select`, `Radio`, etc) component within a `Field`. 
There was an update made to `@zendeskgarden/container-field` v2.1.0 which associates the `Message` component ID to the `aria-describedby` attribute of a given `Input` when it is present. The `aria-describedby` attribute is a combination of the `Hint` and `Message` component IDs, however the ID of either of those components will not be added if they are not present as children of the `Field` component.
In Safari (using VoiceOver), a concatenated list of text node IDs are not all read, only the first item is. However, other browsers behave as expected.

fix(forms): add message id to input aria-describedby attribute

---

packages/tabs/.size-snapshot.json
packages/tabs/src/elements/Tab.spec.tsx
packages/tabs/src/elements/Tab.tsx

This PR adds `role="tab"` to the `Tab` component when disabled.
Due to the `@zendeskgarden/container-tabs` passing in event handlers and setting the `tabIndex` from `getTabProps`, any `disabled` `Tab` was omitted from these props. This PR adds only the `role` of `tab` back into the disabled `Tab`.

fix(tabs): add role when tab is disabled

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/common/Hint.spec.tsx
packages/forms/src/elements/common/Hint.tsx
packages/forms/src/elements/common/Message.spec.tsx
packages/forms/src/elements/common/Message.tsx

This PR fixes a bug that causes a `Hint` or `Message` component to throw when rendered outside of a `Field`.

fix(forms): prevent message and hint component from throwing outside of field component

---

packages/loaders/.size-snapshot.json
packages/loaders/src/elements/Inline.spec.tsx
packages/loaders/src/elements/Inline.tsx

This PR adds `useText` hook to the `Inline` component in the `loaders` package, targeting the `aria-label` prop and ensures an English default of `"loading"` is set for the label.

fix(loaders): use text for inline loader label

---

packages/theming/.size-snapshot.json
packages/theming/src/utils/useText.spec.tsx
packages/theming/src/utils/useText.ts

This PR updates the `useText` hook to allow it to update when either the `value` of the selected `prop` (via `props[name]`) is updated or when the default `text` value changes.
For dynamic components that usually have changing labels based on user interaction or status change, the `useText` hook cannot be updated unless the component (or hook) using the `useText` hook is re-mounted (removed from the render tree and re-attached to the render tree). This prevents dynamic components that have changing text to update; this change enables the `useText` hook to remain mounted and update when the value or default value is changed.

fix(theming): allow use text to be dynamic when updated

---

packages/avatars/.size-snapshot.json
packages/avatars/src/styled/StyledStatusIndicator.ts

This PR fixes the `Avatar` status icon dimensions when `@zendeskgarden/css-bedrock` is used.
When the CSS from `@zendeskgarden/css-bedrock` is present on a document, the `Avatar` component status icon is not correctly sized due to `max-height` being set on an `svg` selector. This PR `unset`s the `max-height` to preserve the dimensions of the status icon.

fix(avatars): correct status icon sizing with css bedrock

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Select/Select.tsx

Removes any focusable descendant elements from being nested within the `Select` component.
Prior to this change, a `role="button"` was used for the wrapping container that housed a hidden `input` element, which caused the nested interactive elements violation to be flagged. To remediate, a role of `none` was used in place of `button` to remove any nesting of interactive roles.
An alternative was to add `type="hidden"` to the internal input used within the `Select` component, however this caused the menu items not to be read by the screen reader.

fix(dropdowns): remove nested controls violation from select

---

packages/accordions/.size-snapshot.json
packages/accordions/demo/stories/data.ts
packages/accordions/demo/timeline.stories.mdx

Provide missing link to `Timeline` component designs in Storybook, along with matching default data to the designs.

demo(accordions): add Figma designs for Timeline component

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

Adds clarifying text for code contribution and refines the PR checklist. The new PR checklist can be viewed [here](https://github.com/zendeskgarden/react-components/blob/95e5cc6fd0452fa8632e9fec50c6662d2e731633/.github/PULL_REQUEST_TEMPLATE.md).

docs: update contributing documentation and PR template

---

packages/avatars/.size-snapshot.json
packages/avatars/README.md
packages/avatars/demo/statusindicator.stories.mdx
packages/avatars/demo/stories/StatusIndicatorStory.tsx
packages/avatars/demo/~patterns/patterns.stories.mdx
packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
packages/avatars/src/elements/Avatar.tsx
packages/avatars/src/elements/StatusIndicator.spec.tsx
packages/avatars/src/elements/StatusIndicator.tsx
packages/avatars/src/index.ts
packages/avatars/src/styled/StyledAvatar.ts
packages/avatars/src/styled/StyledStandaloneStatus.ts
packages/avatars/src/styled/StyledStandaloneStatusCaption.ts
packages/avatars/src/styled/StyledStandaloneStatusIndicator.ts
packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
packages/avatars/src/styled/StyledStatusIndicator.ts
packages/avatars/src/styled/StyledStatusIndicatorBase.ts
packages/avatars/src/styled/index.ts
packages/avatars/src/styled/utility.ts
packages/avatars/src/types/index.ts

Adds the new `StatusIndicator` standalone component.
This PR contains a new component `StatusIndicator` that is exported from the `avatars` package. The new component has two props `type` (`"available" | "away" | "transfers" | "offline"`) and `isCompact`.
Available `type`:
Away `type`:
Transfers `type`:
Offline `type`:
Component frame:
Usage example:

feat(avatars): add status indicator component

---

packages/avatars/.size-snapshot.json
packages/avatars/src/elements/StatusIndicator.tsx

Follow [documented simple structure](https://github.com/zendeskgarden/react-components/blob/main/docs/api.md#simple) to ensure the `@extends` clause can be rendered via website generated docs.

fix(avatars): `StatusIndicator` code structure

---

packages/grid/.size-snapshot.json
packages/grid/src/elements/pane/components/Splitter.spec.tsx
packages/grid/src/elements/pane/components/Splitter.tsx

Allows event composition within the underlying `useSplitter` hook `getSeparatorProps` render prop function for the following:
- `onMouseDown`
- `onTouchStart`
- `onKeyDown`
- `onClick`

fix(grid): properly compose Pane.Splitter events

---

packages/loaders/.size-snapshot.json
packages/loaders/demo/progress.stories.mdx
packages/loaders/src/elements/Progress.spec.tsx
packages/loaders/src/elements/Progress.tsx

Following the convention set forth in the Status Indicator component, this PR adds the `useText` helper to the Progress component. This will both provide a default text label for the component and warn devs if a custom text label hasn't been provided.
This PR relates to [`website` PR #429](https://github.com/zendeskgarden/website/pull/429).

feat(progress): add useText helper with default value for ARIA label

---

packages/modals/.size-snapshot.json
packages/modals/demo/drawerModal.stories.mdx
packages/modals/demo/modal.stories.mdx
packages/modals/demo/stories/DrawerModalStory.tsx
packages/modals/demo/stories/ModalStory.tsx
packages/modals/demo/stories/TooltipModalStory.tsx
packages/modals/demo/tooltipModal.stories.mdx
packages/modals/src/elements/DrawerModal/Header.spec.tsx
packages/modals/src/elements/DrawerModal/Header.tsx
packages/modals/src/elements/Header.spec.tsx
packages/modals/src/elements/Header.tsx
packages/modals/src/elements/TooltipModal/Title.spec.tsx
packages/modals/src/elements/TooltipModal/Title.tsx
packages/modals/src/types/index.ts

Following the precedence set in other components (e.g., Ellipsis), this PR adds the `tag` prop to the Modal Header component. This will enable consumers to customize the underlying HTML element, with the intention being that they pass in a heading (h1-h2) tag. This would help us meet WCAG 2.1 [Success Criterion 1.3.1 Info and Relationships](https://www.w3.org/TR/WCAG21/#info-and-relationships) (level A), as well as [Success Criterion 2.4.2 Page Titled](https://www.w3.org/TR/WCAG21/#page-titled) (level A).
~Separate PRs for the Drawer and Tooltip Modal to follow.~
This PR covers the Modal, Drawer, and Tooltip Modal.

feat(modals): add tag prop to Modal, Drawer, and Tooltip Modal components

---

packages/forms/.size-snapshot.json
packages/forms/src/styled/common/StyledField.ts

This PR explicitly sets the direction of the `Field` styled component to be `ltr` when not in `rtl` mode.

fix(forms): field renders rtl and ltr

---

packages/tabs/.size-snapshot.json
packages/tabs/src/elements/Tab.spec.tsx
packages/tabs/src/elements/Tab.tsx
packages/tabs/src/styled/StyledTab.ts

styled-components will only omit a component prop if it is not a valid HTML attribute...and since the `<Tab>` component's `disabled` prop is named the same as a valid HTML attribute, both it and the attached `aria-disabled` attribute has been rendered onto the `<StyledTab>` component.
This PR changes the `<Tab>` component to ensure that we only pass the `aria-disabled` attribute to the `<StyledTab>` component. This will both remove duplicate code and help us meet [WCAG 2.1 Success Criterion 4.1.2 Name, Role, Value](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html).
See the the styled-components docs for more info:
- [Passed props](https://styled-components.com/docs/basics#passed-props)
- [Attaching additional props](https://styled-components.com/docs/basics#attaching-additi …

fix(tabs): remove duplicate disabled attribute from StyledTab component

---

packages/loaders/.size-snapshot.json
packages/loaders/src/elements/Dots.spec.tsx
packages/loaders/src/elements/Spinner.spec.tsx
packages/loaders/src/styled/StyledSVG.ts

To make the Dots and Spinner components accessible to assistive tech users — and to make them conform to [WCAG 2.1 Success Criterion 4.1.2 Name, Role, Value](https://www.w3.org/TR/WCAG21/#name-role-value) (level A) — this PR changes the SVG role from `progressbar` to `img`.

fix(loaders): changed Dots and Spinner roles from progressbar to img

---

.storybook/preview.js

Conditionally remove the tool, since `StrictMode` does not impact production.
https://reactjs.org/docs/strict-mode.html

chore(demo): prevent strict mode tool in production Storybook

---

packages/notifications/.size-snapshot.json
packages/notifications/demo/alert.stories.mdx
packages/notifications/demo/notification.stories.mdx
packages/notifications/demo/stories/AlertStory.tsx
packages/notifications/demo/stories/NotificationStory.tsx
packages/notifications/src/elements/content/Close.spec.tsx
packages/notifications/src/elements/content/Close.tsx

This PR continues work started in [PR 1357](https://github.com/zendeskgarden/react-components/pull/1357) by adding the `useText` utility to the notifications `<Close />` subcomponent.
The hardcoded fallback value is "Close" to remain generic between notifications vs. alerts.
Here's an example of the warning produced when a component renders with default useText:
Also added `aria-label` as a configurable prop in each Notification and Alert stories:

fix(notifications): adds useText utility to encourage aria-label on Close component

---

packages/tables/.size-snapshot.json
packages/tables/demo/stories/TableStory.tsx
packages/tables/demo/table.stories.mdx
packages/tables/src/elements/Head.tsx
packages/tables/src/index.ts
packages/tables/src/styled/StyledHead.spec.tsx
packages/tables/src/styled/StyledHead.ts
packages/tables/src/types/index.ts

Adds `isSticky` prop to `Head` component for `react-tables` package. 
Example usage preview:

feat(tables): add isSticky prop to Head component

---

packages/notifications/.size-snapshot.json
packages/notifications/src/elements/global-alert/GlobalAlert.spec.tsx
packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts
packages/notifications/src/styled/global-alert/StyledGlobalAlertTitle.ts

`<GlobalAlert />` is missing theme-awareness of RTL (`theme.rtl`). This PR adds it.
~~When `<GlobalAlert.Title />` is a child in `<GlobalAlert />` and the document/theme is `rtl`, The title stays left of the content (the padding does switch from left to right correctly, however).~~
~~The root issue is that inline text (in this case, a `div` that is `display: inline`) is treated as combined with all immediate sibling text nodes, and despite being flex items they naturally won't reflow.~~
This is a pretty simple one-liner.
One extra factor noted by the reporter is that margins are incorrect in RTL, even with RTL applied via `styled-components`, But this only happens if you use an LTR language in RTL mode. So, using Arabic, for example, does show the correct margins when RTL is hooked up …

fix(notifications): lets GlobalAlert.Title flow correctly in RTL documents

---

lerna.json

Upgrading Lerna to v6 accidentally flipped on `useNx` under the hood. Turning this back off until we've landed on a path forward on using Nx long-term.
`useNx` defaulted to `false` in v5, but was flipped to `true` in v6.

chore: turn off Nx with lerna

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/Header.tsx

This PR fixes a modal `<Header>` regression where the `isDanger` styling prop is failing to affect the color of the text.
**Before and After**
regressed in #1446

fix(modals): restore `Header` danger styling

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/demo/colorPickerDialog.stories.mdx
packages/colorpickers/demo/colorSwatchDialog.stories.mdx
packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
packages/colorpickers/src/elements/ColorpickerDialog/index.tsx
packages/modals/.size-snapshot.json
packages/modals/demo/stories/TooltipModalStory.tsx
packages/modals/demo/tooltipModal.stories.mdx
packages/modals/src/elements/TooltipModal/Title.tsx
packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
packages/modals/src/elements/TooltipModal/TooltipModal.tsx
packages/modals/src/utils/useTooltipModalContext.tsx

This PR addresses these two problems:
1. Currently, ColorSwatchDialog and ColorpickerDialog use TooltipModal under the hood to render their dialogs. Because these two components don't use `TooltipModal.Title`, the modal container has an invalid IDREF on `aria-labelledby`.
2. There is an unnecessary `aria-describedby` on the modal container.
Solutions implemented in this PR to address the above:
1. Let TooltipModal determine which ARIA attributes to use depending on the existence of a `<Title />` child. Context is used to achieve this, similar to `isCloseButtonPresent` (also in `react-modals`). The resulting `aria-label` is passed through `useText`.
2. In both Color picker components, wrapped the (currently undocumented, but accepted) `aria-label` with `useText` to require consumers to set …

fix: enables accessible label in TooltipModal, ColorpickerDialog, and ColorSwatchDialog

---

packages/dropdowns/.size-snapshot.json
packages/dropdowns/src/elements/Menu/Items/AddItem.spec.tsx
packages/dropdowns/src/elements/Menu/Items/Item.tsx
packages/dropdowns/src/elements/Menu/Items/NextItem.spec.tsx
packages/dropdowns/src/elements/Menu/Items/PreviousItem.spec.tsx

Followup PR for #1489 to fix Menu Items (Add, Next, Previous) and ensure only the corresponding icon is present.

fix(dropdowns): hide selected check from menu action items when not disabled

---

packages/modals/.size-snapshot.json
packages/modals/demo/modal.stories.mdx
packages/modals/demo/stories/ModalStory.tsx
packages/modals/demo/stories/TooltipModalStory.tsx
packages/modals/demo/tooltipModal.stories.mdx
packages/modals/src/elements/Header.tsx
packages/modals/src/elements/Modal.spec.tsx
packages/modals/src/elements/Modal.tsx
packages/modals/src/elements/TooltipModal/TooltipModal.tsx
packages/modals/src/utils/useModalContext.ts
packages/modals/src/utils/useTooltipModalContext.tsx

When no `<Header />` child is present on `<Modal />`, the dialog element's `aria-labelledby` should be replaced with a descriptive `aria-label`. Consumers will be nudged to provide a label via console log, if none is given.
This is an identical fix to what recently merged for `TooltipModal` ([link](https://github.com/zendeskgarden/react-components/pull/1488)).
A small change was also made to `TooltipModal` to check modal container props instead of consumer props for `aria-labelledby`. 
See [Detail](https://github.com/zendeskgarden/react-components/pull/1488#:~:text=(optional)-,Detail,-First%2C%20the%20fixed) on 1488 (link above) for exact change and its DOM effects.

fix(modals): enables accessible label on Modal when no Header is given

---

packages/modals/.size-snapshot.json
packages/modals/demo/drawerModal.stories.mdx
packages/modals/demo/stories/DrawerModalStory.tsx
packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
packages/modals/src/elements/DrawerModal/DrawerModal.tsx
packages/modals/src/elements/DrawerModal/Header.tsx
packages/modals/src/utils/useModalContext.ts
packages/modals/src/utils/useTooltipModalContext.tsx

When no `<DrawerModal.Header />` is present on `<DrawerModal />`, the dialog element's `aria-labelledby` should be replaced with a descriptive `aria-label`. Consumers will be nudged to provide a label via console log, if none is given.
This is an identical fix to what recently merged for TooltipModal (https://github.com/zendeskgarden/react-components/pull/1488).
A small change was also made to `TooltipModal` to check modal container props instead of consumer props for `aria-labelledby`. 
See [Detail](https://github.com/zendeskgarden/react-components/pull/1488#:~:text=(optional)-,Detail,-First%2C%20the%20fixed) on 1488 (link above) for exact change and its DOM effects.

fix(modals): enables accessible label in DrawerModal when no Header is given

---

packages/grid/demo/paneProvider.stories.mdx
packages/notifications/demo/global-alert.stories.mdx

Adding Figma design links for `GlobalAlert` and `Pane` components.

chore(storybook): add figma design for pane and global alert

---

packages/notifications/.size-snapshot.json
packages/notifications/src/elements/toaster/ToastProvider.spec.tsx
packages/notifications/src/elements/toaster/ToastSlot.tsx
packages/notifications/src/elements/toaster/styled.ts

Removes the previous transient props `$zIndex` and `$placement` for backwards compatibility with `styled-components` v4.

fix(notifications): remove invalid attributes and transient props from toast

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/FileUpload.tsx

"Small" change to give FileUpload a valid role when focused.
This change quite literally forces the role by superseding consumer props. In general, consumers have the ability to add *any* children (including other buttons) to FileUpload, but per the Garden design, it's discouraged to nest other interactive elements.
Previously, the upload zone was announced as a generic "group" (default for `div`s). Now announced as a button:

fix(forms): force FileUpload's container to role='button'

---

package.json
packages/avatars/.size-snapshot.json
packages/avatars/src/elements/Avatar.tsx
packages/avatars/src/elements/StatusIndicator.tsx
packages/buttons/.size-snapshot.json
packages/buttons/src/elements/Anchor.tsx
packages/chrome/src/elements/sheet/components/Close.spec.tsx
packages/forms/.size-snapshot.json
packages/forms/src/elements/FileUpload.tsx
packages/forms/src/elements/MultiThumbRange.spec.tsx
packages/grid/src/elements/pane/Pane.spec.tsx
packages/loaders/.size-snapshot.json
packages/loaders/src/elements/Inline.tsx
packages/loaders/src/elements/Progress.tsx
packages/notifications/src/elements/Alert.spec.tsx
packages/notifications/src/elements/global-alert/GlobalAlert.tsx
packages/notifications/src/elements/global-alert/GlobalAlertClose.tsx
yarn.lock

Various fixes to acommodate new eslint rules (tested locally via `yarn link`).
<details>
<summary>List of errors flagged during local upgrade.</summary>
<pre><code>.../garden/react-components/packages/avatars/src/elements/Avatar.tsx
77:11  error  Use &lt;img alt=...>, or &lt;img alt=...> instead of the "img" role to ensure accessibility across all devices  jsx-a11y/prefer-tag-over-role
.../garden/react-components/packages/avatars/src/elements/StatusIndicator.tsx
40:7  error  Use &lt;output> instead of the "status" role to ensure accessibility across all devices                      jsx-a11y/prefer-tag-over-role
41:9  error  Use &lt;img alt=...>, or &lt;img alt=...> instead of the "img" role to ensure accessibility across all devices  jsx-a11y/prefer-tag-over-role …

chore(deps): config-eslint updates 

---

packages/tags/.size-snapshot.json
packages/tags/demo/stories/TagStory.tsx
packages/tags/demo/tag.stories.mdx
packages/tags/demo/~patterns/stories/FauxInputStory.tsx
packages/tags/src/elements/Close.spec.tsx
packages/tags/src/elements/Close.tsx
packages/tags/src/styled/StyledClose.spec.tsx
packages/tags/src/styled/StyledClose.ts

This fix follows the same pattern as the [recent changes](https://github.com/zendeskgarden/react-components/pull/1509) to `File.Close`, but on `Tag.Close`:
1. Uses a native `button` with `tabindex='-1'` (to prevent tab focus).
2. Wraps implicit `aria-label` prop with `useText`.
a. Uses generic text by default (`'Close'`).
The main thing this fixes, like in `File.Close`, is the operability of `Tag`. When a customer navigates to the component, they'll be able to interact with it in and out of Browse(JAWS/NVDA) and Quick Nav (VO) modes.
Also applies a few reset styles to the icon button.
Instead of rendering a `div`, a `button` is provided:
And the friendly `useText` message is provided when an `aria-label` isn't defined on `Tag.Close`:

fix: improves accessibility of Tag close button

---

packages/tables/.size-snapshot.json
packages/tables/demo/stories/TableStory.tsx
packages/tables/demo/table.stories.mdx
packages/tables/src/elements/Cell.spec.tsx
packages/tables/src/styled/StyledCell.ts

Applies visually hidden styles to `Cell` (and inherited components e.g. HeaderCell) when `hidden` prop is given.
It uses the same pattern already used in `Label` for forms.

feat(tables): add [hidden] prop support to Cell

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/DrawerModal/DrawerModal.spec.tsx
packages/modals/src/elements/DrawerModal/DrawerModal.tsx

This PR fixes an edge case found in the `Drawer` component with the focus management being handled in all cases.
The underlying bug is around how focus is returned to the trigger element that opened the modal and `restoreFocus` - if an element has focus other than the `document.body` (or no focus) as the `Drawer` is rendered, it will lock out the actual trigger element from reclaiming focus.

fix(modals/drawer): correctly set focus on trigger element when focus is restored

---

packages/tables/.size-snapshot.json
packages/tables/demo/stories/TableStory.tsx
packages/tables/src/elements/Cell.spec.tsx
packages/tables/src/elements/Cell.tsx
packages/tables/src/elements/HeaderCell.spec.tsx
packages/tables/src/elements/HeaderCell.tsx
packages/tables/src/styled/StyledCell.ts
packages/tables/src/styled/StyledHiddenCell.ts
packages/tables/src/styled/index.ts

Inadvertently introduced a style regression in `Cell` (react-tables) by using visually hidden styles when the `hidden` prop is used. Namely, CSS properties like `position`, `width`, and removal of `padding` when the cell is a header causes column width issues.
This fix conditionally renders an inner `div` with visually hidden styles instead of manipulating the outer `td`/`th`.
*Note: the left column in the below images has a static width, which was being overridden by visually hidden styles*
Before:
After:
There are really two ways to go about this fix:
1. Use an inner element with hidden styles
2. Apply a `text-indent` with `overflow: hidden` to push content out of the content box.
There are trade offs to both approaches, namely that 1 adds a new element, and 2 has page flow …

fix(tables): hide content of Table cell without breaking table layout

---

packages/forms/.size-snapshot.json
packages/forms/src/elements/input-group/InputGroup.spec.tsx
packages/forms/src/styled/input-group/StyledInputGroup.ts

Resets the start margin of the `TextInput` styled component in an `InputGroup`, fixing a bug where `overflow: hidden` in a parent element will display the `Input` incorrectly.
Before:
After:

fix(forms): reset margin start for text input in input group

---

packages/breadcrumbs/src/elements/Breadcrumb.tsx
packages/grid/src/elements/pane/components/Splitter.tsx
packages/modals/src/elements/Close.tsx
packages/modals/src/elements/DrawerModal/Close.tsx
packages/modals/src/elements/TooltipModal/Close.tsx
packages/theming/.size-snapshot.json
packages/theming/src/index.ts
packages/theming/src/types/index.ts
packages/theming/src/utils/useText.spec.tsx
packages/theming/src/utils/useText.ts
packages/theming/src/utils/useWindow.spec.ts
packages/theming/src/utils/useWindow.ts
yarn.lock

The addition of `useWindow` is needed for `Comobobox v.next`. The addition of the `condition` parameter will help clean up some wonky uses of the `useText` hook.
p.s. I took the opportunity to address the build warning and update browserslist `caniuse-lite`.
Here is a simplified `Anchor` component diff showing how `isExternal` can be passed to `useText` rather than artificially manipulating the hook parameters:

feat(theming): add `useWindow` utility and enhance `useText` with optional `condition` parameter

---

packages/drag-drop/demo/draggable-list.stories.mdx
packages/drag-drop/demo/draggable.stories.mdx
packages/drag-drop/demo/dropzone.stories.mdx

Adds Figma links to drag and drop storybook.

chore(drag-drop): adds figma link to drag and drop storybook

---

packages/theming/.size-snapshot.json
packages/theming/src/utils/getColor.ts

This update only feed portions of the theme to the resolver that are actually used by the utility – `palette` and `colors`. This micro-optimizes the time spent to stringify `theme`.

fix(theming): improve `getColor` memoization resolver performance

---

packages/avatars/.size-snapshot.json
packages/avatars/package.json
packages/avatars/src/elements/Avatar.tsx

Prevents an unnecessary console warning when `Avatar`'s `statusLabel` prop isn't provided, despite no status/badge being configured by a consumer.
Fixes #1537 
Adds a conditional to `Avatar`'s implementation of `useText` to suppress the validation until a status can be displayed.

fix(avatars): suppress `statusLabel` useText warning when there is no configured status

---

packages/breadcrumbs/.size-snapshot.json
packages/breadcrumbs/src/styled/StyledBreadcrumb.ts
packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts

Add missing `retrieveComponentStyles` to `breadcrumbs`.

fix(breadcrumbs): add global theme styles override

---

packages/forms/.size-snapshot.json
packages/forms/package.json
packages/forms/src/elements/common/Message.tsx

Adds a `validation !== undefined` condition to `useText` that prevents evaluation for a `Message` without validation treatment.
Updates `react-theming` peer dependency to v8.65.0 where the new `condition` parameter was added to `useText`.

fix(forms): prevent `validationLabel` warning on `Message` when `validation` is undefined

---

packages/theming/.size-snapshot.json
packages/theming/src/utils/focusStyles.spec.tsx
packages/theming/src/utils/focusStyles.ts
packages/theming/src/utils/getFocusBoxShadow.spec.ts
packages/theming/src/utils/getFocusBoxShadow.ts

- feat: add `boxShadow` retention to `getFocusBoxShadow`
- fix: prevent `focusStyles` from overriding existing `styles: { boxShadow: ... }`
- feat: add `spacerHue` and `spacerShade` color overrides to `getFocusBoxShadow` and `focusStyles`

feat(theming): enhance focus utilities with additional parameter overrides

---

packages/chrome/.size-snapshot.json
packages/chrome/src/elements/subnav/CollapsibleSubNavItem.tsx

Fixes the focus color for `CollapsibleSubNavItem` within the `Chrome` context; follows the same behavior of `SubNavItem`.

fix(chrome): consistent focus style for sub nav items

---

README.md
docs/adrs/001-theming-peer-dependency.md
docs/adrs/README.md

Brings the decision made 2023.04.24 re: the `@zendeskgarden/react-theming` peer dependency into GitHub, along with a README for indexing future ADRs.

doc(adrs): add theming peer dependency ADR-001

---

packages/tables/.size-snapshot.json
packages/tables/src/elements/OverflowButton.spec.tsx
packages/tables/src/styled/StyledOverflowButton.ts

Persists `OverflowButton` visibility on `Table` rows.
Removes all conditional render logic when it comes to opacity toggling.
There have been additional updates to the `OverflowButton.spec.tsx` to account for this change.
Prior to this change, `OverflowButton`s would be visible only when its given row was being interacted with.
**Before:**
**Current:**

fix(tables): persist overflow button visibility

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/package.json
packages/dropdowns.next/src/views/combobox/StyledLabel.ts

A few minor fixes, detailed below...
- revert the underlying `Label`'s `vertical-align: center` which isn't playing nice with the `Combobox` flex layout
- bump the `theming` peer to 8.67.0, since we're taking advantage of `focusStyles` override parameters from that release
- correct the `styled-components` peer to 5.1 as that is the [transient props](https://styled-components.com/docs/api#transient-props) feature release

fix(combobox): correct peer dependencies and label pixel shift

---

packages/avatars/.size-snapshot.json
packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
packages/avatars/src/styled/StyledStandaloneStatusIndicator.ts

Fixes a visual bug when `box-sizing` computes to a value other than `content-box` for the `StatusIndicator` icon container element.
This fix also includes another fix to the `StatusIndicator` storybook pattern. It wraps the `Avatar` in an `IconButton` component.

fix(avatars): explicitly set box sizing for status indicator icon container

---

packages/chrome/.size-snapshot.json
packages/datepickers/.size-snapshot.json
packages/modals/.size-snapshot.json
utils/build/rollup.config.js

Ensures that `dependencies` for packages are not bundled into the distributable for our component packages. This reduces code duplication and limits multiple instances of a given library (eg `date-fns`) which can lead to unintended issues.
This affects any component package that uses a nested import path.
Three packages have been affected:
- `chrome`: `dom-helpers` nested import of `dom-helpers/activeElement`
- `datepickers`: `date-fns` nested imports of various utilities
- `modals`: `dom-helpers` nested import of `dom-helpers/activeElement`

fix(build): ensure nested external dependencies are not bundled

---

packages/accordions/src/utils/useAccordionContext.ts
packages/datepickers/src/elements/DatepickerRange/utils/useDatepickerRangeContext.ts

This PR changes any project level paths to conventional `node.js` file resolution algorithm, using relative and module path imports.

chore(packages): use relative and module paths for imports

---

packages/accordions/.size-snapshot.json
packages/accordions/src/elements/stepper/components/Content.tsx
packages/accordions/src/styled/stepper/StyledContent.ts
packages/accordions/src/styled/stepper/StyledInnerContent.ts

Use a pure CSS implementation to animate/transition height for the active `Step` in `Stepper` component. This fixes a bug found with dynamically changing heights in a `Stepper.Step`, since there are instances where changing the height after the `Stepper.Content` has been rendered does not change the height.
There is long-standing issue with animating `height` change that affects the web, and the implementation here makes use of `grid` (specifically `transition`ing the `grid-template-rows` CSS property) to handle that animation.
This treatment can be applied across the `accordions` package where this is relevant.

fix(accordions): allow dynamic height for stepper content

---

packages/dropdowns.next/package.json
packages/dropdowns.next/yarn.lock

Fixes a bug where if a user has selected options from a multiselectable combobox, then removes them via keyboard, focus never leaves the input when attempting to navigate away.
zendeskgarden/react-containers#551

fix(combobox): prevent combobox focus retention on multiselectable tag removal

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/package.json
packages/dropdowns.next/src/views/combobox/StyledValue.ts
packages/dropdowns.next/yarn.lock

- Upgrades `@zendeskgarden/container-combobox` with fixes detailed below
- Update the input value HTML replacement CSS with `white-space: pre` to preserve user-input spaces
zendeskgarden/react-containers#552

fix(combobox): keyboard interactions and value space rendering

---

packages/buttons/.size-snapshot.json
packages/buttons/package.json
packages/buttons/src/elements/Button.tsx
packages/buttons/src/elements/ButtonGroup.spec.tsx
packages/buttons/src/elements/ButtonGroup.tsx
packages/buttons/yarn.lock

Uplifts the `ButtonGroup` component to be to React v18  ready.
The `ButtonGroup` refactor removes `@zendeskgarden/container-buttongroup` in favor of `@zendeskgarden/container-selection`. It implements the `useSelection` container in the same fashion as the `useButtonGroup` had previously done.

refactor(buttons): button group react v18 uplift

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/views/combobox/StyledInput.ts

It appears that implicit instance reference logic changed from styled-components v5 to v6. The addition of `&` fixes for environments (i.e. codesandbox) that are using the latest styled-components.
https://codesandbox.io/s/brave-mopsa-rx85mj

fix(combobox): ensure input focus reset

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/combobox/Combobox.tsx

By considering the current multiselectable selection, we can reduce `optionTagProps` state down to the bare minimum needed for `Tag` rendering. Compare to previous, which allowed `optionTagProps` to grow to N, where N = the number of `Option` components experienced by the user over the lifespan of `Combobox` usage.
Online (together with offline) conversation that prompted the update: https://github.com/zendeskgarden/react-components/pull/1559#discussion_r1237413385

chore(combobox): prevent `optionTagProps` state bloat

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/combobox/Combobox.tsx

The `values` portion of the `setOptionTagProps` updater function was an empty `{}` – but only in controlled mode 😕. I'm removing this optimization prior to release as there are too many pitfalls.
Also updated `selectionValue` prop type to be `any` in order to satisfactorily accept object & object arrays along with string/string arrays.

chore(dropdowns.next): rollback option tag props optimization

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns.next/src/elements/combobox/Combobox.tsx
packages/dropdowns.next/src/elements/combobox/TagGroup.tsx
packages/dropdowns.next/src/types/index.ts
packages/dropdowns.next/src/views/combobox/StyledInput.ts
packages/dropdowns.next/src/views/index.ts

Addresses some touchy expand/collapse state bugs for multiselectable tag groups. The `TagGroup` is an internal-only component that renders a list of `Tag` components and `{children}` (the `StyledTagsButton`) as a final sibling.
Also shimmed in:
- an input `aria-labelledby` label readout hack for screenreaders
- preventing double readout of `isEditable={false}` combobox value

fix(combobox): address multiselectable state issues with new `TagGroup` component

---

packages/tabs/.size-snapshot.json
packages/tabs/src/elements/Tabs.spec.tsx
packages/tabs/src/utils/toTabs.ts

Fixes an issue where valid `Tab` composition/inheritance is not being looped into the top-level `useTabs` hook.
Regressed with [v8.69.5](https://github.com/zendeskgarden/react-components/releases/tag/v8.69.5)

fix(tabs): loosen `toTabs` type checking

---

utils/scripts/tag.mjs

In [execa v6.0.0](https://github.com/sindresorhus/execa/releases/tag/v6.0.0), `execa.command` -> `execaCommand`

fix(scripts): execa command

---

packages/loaders/.size-snapshot.json
packages/loaders/src/elements/Skeleton.spec.tsx
packages/loaders/src/styled/StyledSkeleton.ts

Improves animation performance in `Skeleton` loader.
CSS properties like `left` will cause a reflow/repaint when they change, resulting in heavy DOM thrashing when animated. There are some [recommended](https://web.dev/animations-guide/) properties we can leverage instead.
Here is a before and after snapshot of animating using `left`, then switching to `translateX`:
Layout/styles recalc is 120 times per second:
Layout recalc is now zero, and styles recalc is at a much more reasonable 4-8 times per second, max:
The improvement in `layouts / sec` and `style calcs / sec` in the second image in particular shows a much better persistence of the loader.
As an added bonus, there's substantial CPU reduction as well.

fix(loaders): optimize performance of skeleton loader

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/package.json
packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns.next/src/elements/combobox/Combobox.tsx
packages/dropdowns.next/src/views/combobox/StyledTagsButton.ts
packages/dropdowns.next/src/views/combobox/StyledValue.ts
packages/dropdowns.next/yarn.lock

The underlying logic container bump to Downshift v8 applies updated input click-to-expand functionality that falls more in line with the [APG specification](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#:~:text=It%20is%20displayed%20when%20the%20combobox%20receives%20focus%20even%20if%20the%20combobox%20is%20editable%20and%20empty). By adopting this update, Garden's new `Combobox` now has click-to-expand behavior parity with the deprecated [Autocomplete](https://garden.zendesk.com/components/autocomplete) component.
zendeskgarden/react-containers#565

fix(combobox): enhance listbox expand/collapse on input mouse click

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/package.json
packages/dropdowns.next/src/context/useFieldContext.ts
packages/dropdowns.next/src/elements/combobox/Combobox.tsx
packages/dropdowns.next/src/elements/combobox/Field.tsx
packages/dropdowns.next/src/elements/combobox/Hint.tsx
packages/dropdowns.next/src/elements/combobox/Message.tsx
packages/dropdowns.next/src/types/index.ts
packages/dropdowns.next/yarn.lock

This PR leverages the latest `@zendeskgarden/container-combobox` with stabilized internal IDs that are not affected by render effects or partial component re-renders. In addition, the prop getters for `Hint` and `Message` were missed in the initial implementation. They have been recovered here, correcting a11y `aria-describedby` relationships for the combobox input field.
zendeskgarden/react-containers#580

fix(combobox): stabilize IDs and add missing hint/message props

---

packages/colorpickers/.size-snapshot.json
packages/colorpickers/src/elements/Colorpicker/index.tsx

With React v18 - [Legacy mode](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis) (mounting with `ReactDOM.render()`), there is a chance that `colorpicker` will rerender infinitely when a new color is picked via `ColorWell`.
Reproducible:
https://codesandbox.io/s/quizzical-franklin-fxq9zy?file=/src/Example.tsx
We fix this by updating local state when `color` props changed in the same rendering cycle, instead of using `useEffect`. 
Docs:
https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes
These changes can be tested via this sandbox https://codesandbox.io/s/garden-color-picker-new-lgm7s7:
- this is the fork of https://codesandbox.io/s/quizzical-franklin-fxq9zy sandbox above
- I updated the sandbox with some …

fix(colorpicker): prevent infinite rerender in React v18 Legacy mode

---

packages/dropdowns.next/package.json
packages/dropdowns.next/yarn.lock

Fix ID mismatch with `Combobox` when rendered in production SSR environments

fix(combobox): stabilize production SSR ID generation

---

packages/modals/.size-snapshot.json
packages/modals/src/elements/TooltipModal/TooltipModal.spec.tsx
packages/modals/src/elements/TooltipModal/TooltipModal.tsx
packages/modals/src/types/index.ts

Adds `appendToNode` to `TooltipModal`.
~~:ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
~~:arrow_left: renders as expected with reversed (RTL) direction~~
~~:metal: renders as expected with Bedrock CSS (`?bedrock`)~~
~~:wheelchair: tested for [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa) accessibility compliance~~
~~:memo: tested in Chrome, Firefox, Safari, and Edge~~

feat(modals): adds appendToNode prop to TooltipModal

---

packages/grid/.size-snapshot.json
packages/grid/src/elements/pane/components/Splitter.spec.tsx
packages/grid/src/styled/pane/StyledPaneSplitter.ts
packages/grid/src/styled/pane/StyledPaneSplitterButton.ts

Fix a CSS regression that slipped through with #1578.
The `stylelint` update eagerly attempts to replace `top`+`right`+`bottom`+`left` CSS positioning with a single `inset` property. In the case of the styled splitter, the properties are lazy instantiated leaving two or more of the four `undefined`. The result is broken positioning for all `Pane.Splitter` components since [v8.69.4](https://github.com/zendeskgarden/react-components/releases/tag/v8.69.4).

fix(grid): `Pane.Splitter` position styling regression

---

packages/modals/demo/stories/TooltipModalStory.tsx

Update the Previous button in Tooltip modal storybook example to use the Basic style, to make it consistent with the website [example](https://garden.zendesk.com/components/tooltip-modal#placement).
Before
After

docs(TooltipModal): Match storybook example with website example for consistency

---

packages/dropdowns.next/README.md
packages/dropdowns/README.md
packages/dropdowns/demo/autocomplete.stories.mdx
packages/dropdowns/demo/combobox.stories.mdx
packages/dropdowns/demo/menu.stories.mdx
packages/dropdowns/demo/multiselect.stories.mdx
packages/dropdowns/demo/select.stories.mdx
packages/dropdowns/src/elements/Dropdown/Dropdown.tsx
packages/dropdowns/src/elements/Menu/Menu.tsx
packages/dropdowns/src/elements/Trigger/Trigger.tsx

- Adds Menu example to README
- Updates deprecation links & marks Menu/Dropdown/Trigger as deprecated.

chore(dropdowns): Add menu to readme, mark legacy dropdowns deprecated

---

packages/dropdowns.next/package.json
packages/dropdowns.next/yarn.lock

For details on what's including in the updated `container-menu`, see react-container's [PR #603](https://github.com/zendeskgarden/react-containers/pull/603).

chore(deps): bump container-menu to 0.2.2 in react-dropdowns.next

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/combobox/OptGroup.spec.tsx
packages/dropdowns.next/src/views/combobox/StyledListbox.ts

Hides separator if an `OptGroup` or `ItemGroup` is the first descendent of a `Combobox` or `Menu` and no visible group label is given.
Use case comes from the need to have the top-most items in a menu in a selectable group. When no `legend` is used, an extra separator is rendered.
Before this change:
After this change:
~~:metal: renders as expected with Bedrock CSS (`?bedrock`)~~
~~:arrow_left: renders as expected with reversed (RTL) direction~~

feat(dropdowns.next): hides separator in label-less, first group child in Combobox/Menu

---

packages/dropdowns.next/package.json
packages/dropdowns.next/yarn.lock

Adds `container-menu@0.3.0` to `react-dropdowns.next`. Includes these features/fixes:
- [fix(menu): prevents focus from moving out of the menu unless it is actually closed](https://github.com/zendeskgarden/react-containers/commit/8efc805b625022b74b0a3bc14d1a2aa4edcc95fe) 
- [feat(menu): passes clicked item's value to onChange](https://github.com/zendeskgarden/react-containers/commit/ccb87294fd004aa31c0449deaae9103dcc72507d)

chore(deps): bump container-menu to v0.3.0 in react-dropdowns.next

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/menu/Menu.spec.tsx
packages/dropdowns.next/src/elements/menu/Menu.tsx

Implements rotating chevron icon for the built-in Garden Button on `Menu`. This will reduce the overhead for consumers to implement their Menu trigger, which we consistently recommend having this icon, anyway.
Also includes minor update to a test which became invalid with the addition of the chevron.
~~:ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~

feat(dropdowns.next): adds rotating chevron to default menu button

---

packages/chrome/.size-snapshot.json
packages/chrome/src/elements/nav/NavItem.spec.tsx
packages/chrome/src/styled/nav/StyledNav.ts
packages/chrome/src/styled/nav/StyledNavItem.ts

Updates nav item foreground vs. background contrast when `hue` is applied to the `Chrome` component.

fix(chrome): improve custom `Nav` color contrast

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/menu/Menu.spec.tsx
packages/dropdowns.next/src/elements/menu/Menu.tsx

Fixes an invalid prop spread of `buttonProps` so `disabled` can be set to the default menu button.
~~:ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
~~:wheelchair: tested for [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_customize&levels=aaa) accessibility compliance~~
~~:memo: tested in Chrome, Firefox, Safari, and Edge~~

fix(dropdowns.next): allows buttonProps to flow into container-menu props

---

utils/scripts/tag.mjs

Add missing command option separator.

chore: fix `lerna-version` command in tag script

---

packages/accordions/.size-snapshot.json
packages/accordions/src/styled/accordion/StyledRotateIcon.ts

fix(accordions): prevent flex shrink on chevron

---

packages/dropdowns.next/.size-snapshot.json
packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns.next/src/elements/combobox/Listbox.tsx

This PR fixes `Combobox` event handling that over-aggressively dismisses the listbox on mousedown – preventing a user from interacting with the scrollbar.

fix(combobox): prevent listbox close on scrollbar click

---

.storybook/main.js
package-lock.json
packages/forms/src/elements/MultiThumbRange.tsx
utils/build/rollup.config.js

The `MultiThumbRange` is a problematic Garden component from a design POV and will be removed in the next major release.
Commented out rollup `sizeSnaphot` due to random CI match [failures](https://app.circleci.com/pipelines/github/zendeskgarden/react-components?branch=jzempel%2Fdeprecate-multithumbrange). Will need to reevaluate the value of this plugin in the future.

chore(forms): mark `MultiThumbRange` deprecated

---

packages/accordions/src/elements/accordion/components/Panel.tsx
packages/accordions/src/styled/accordion/StyledInnerPanel.ts
packages/accordions/src/styled/accordion/StyledPanel.spec.tsx
packages/accordions/src/styled/accordion/StyledPanel.ts

Provides an important accessibility fix that prevents focusable content from being accessed when an `Accordion` panel is collapsed. The approach here applies both the HTML [inert](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) attribute and transitional visibility to the panel content.
closes #1383

fix(accordions): hide collapsed panel content

---

packages/forms/src/elements/Textarea.tsx

This PR removes a `useEffect` that puts a React 18, _controlled_, autosized (with `minRows` & `maxRows` defined) `Textarea` into an infinite loop after the window has been resized. Testing shows that the existing `useLayoutEffect` is sufficient for handling both controlled and uncontrolled component resizing.
closes #1563

fix(forms): prevent `Textarea` autosize infinite loop

---

packages/typography/demo/span.stories.mdx
packages/typography/src/elements/span/Span.spec.tsx
packages/typography/src/styled/StyledFont.spec.tsx
packages/typography/src/styled/StyledFont.tsx
packages/typography/src/types/index.ts

Similar to other Garden components (such as [Label](https://garden.zendesk.com/components/input#label)), this PR adds the ability to visually hide text – via `<Span hidden>` – without hiding the text from screen readers.
Simplified pivot from #1612

feat(typography): add support for accessible, visually hidden `Span` styling

---

package-lock.json
packages/dropdowns.next/demo/stories/data.ts
packages/dropdowns.next/package.json
packages/dropdowns.next/src/elements/combobox/Option.spec.tsx
packages/dropdowns.next/src/elements/combobox/Option.tsx
packages/dropdowns.next/src/elements/combobox/utils.ts
packages/dropdowns.next/src/types/index.ts
packages/dropdowns.next/src/views/combobox/StyledOption.ts

The new `<Option isHidden>` prop facilitates accessible rendering for selected options (ex: tags for nested multiselectable options) without needing to have those options visually present within the `Combobox` listbox.
zendeskgarden/react-containers#621

feat(combobox): add `isHidden` prop to `Option` component

---

.circleci/config.yml
lerna.json
utils/scripts/tag.mjs

The config updates and fixes in the PR allow the positional tag `version` specifier to work as intended. For example: `npm run tag preminor` would ensure that the version is set with `-next.x` notation and that it is published under the `next` tag.

chore: fix config to support `next` prerelease

---

package.json
utils/scripts/tag.mjs

Further sets up the `next` branch for release and prevents publish pushes to `main` 😬

chore(scripts): fix `tag` to release on `next` branch

---

packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns.next/src/elements/combobox/Combobox.tsx

Currently, a disabled `Combobox` is swapping the static value with the input value on click (focus). Note that keyboard focus is not available for disabled comboboxes.
Here is an example of the current bug where "cherry" is a custom `renderValue` that gets displaced by the empty input value on click focus.
https://github.com/zendeskgarden/react-components/assets/143773/2b40db14-9375-4bc8-824c-23cd77828f0c

fix(combobox): prevent disabled combobox from swapping static/input values on click

---

docs/migration.md
package-lock.json
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/colorpickers/package.json
packages/datepickers/package.json
packages/drag-drop/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/theming/package.json
packages/tooltips/package.json
packages/typography/package.json

Updates `styled-components` peer dependency version.
- Component packages bumped to `^5.1.0`.
- `react-theming` bumped to `^4.2.0 || ^5.1.0` (from `^4.2.0 || ^5.0.0`)
- Updates `migration.md` with breaking change notes.
No component code changes necessary at this time.

feat: bump peer dep styled-components to v5.1.0 minimum

---

docs/changelogs/v8.md
package-lock.json

Cherry picks commits from `main` [since v8.47.2](https://github.com/zendeskgarden/react-components/compare/be0e20f0b016a227ed1ab6b5b13cb04971969d3b...main).
- [chore(changelog): add v8.74.2 [skip ci]](https://github.com/zendeskgarden/react-components/commit/3c342aec531125b815177559e65475306ef2ba8f)
- [chore(deps-dev): bump ip from 2.0.0 to 2.0.1](https://github.com/zendeskgarden/react-components/commit/7c3a5ff968f0fc917385962cdb410ffa84a29c21)
- [chore(deps): bump axios from 1.5.1 to 1.6.2](https://github.com/zendeskgarden/react-components/commit/ca1a288c2df96c952d1b3e744bbea20e62bf17d0)

chore(next): updates from `main`

---

.storybook/main.js
.storybook/preview.js
packages/theming/src/elements/ThemeProvider.tsx
packages/theming/src/types/index.ts

Adds the Storybook background tool from #1673.
...also picks up the improved (corrected) `theme` prop type from the POC.

chore: add Storybook tool for dark mode

---

docs/migration.md
packages/accordions/src/elements/timeline/components/Item.tsx
packages/accordions/src/index.ts
packages/avatars/src/index.ts
packages/buttons/src/elements/Button.tsx
packages/buttons/src/index.ts
packages/chrome/demo/stories/ChromeStory.tsx
packages/chrome/src/elements/header/HeaderItem.spec.tsx
packages/chrome/src/elements/header/HeaderItem.tsx
packages/chrome/src/elements/nav/NavItem.spec.tsx
packages/chrome/src/elements/nav/NavItem.tsx
packages/chrome/src/index.ts
packages/chrome/src/types/index.ts
packages/dropdowns.legacy/src/utils/garden-placements.ts
packages/dropdowns.legacy/src/utils/gardenPlacements.spec.ts
packages/dropdowns/src/views/combobox/StyledFloatingListbox.ts
packages/dropdowns/src/views/menu/StyledMenu.ts
packages/forms/src/elements/common/Field.tsx
packages/forms/src/elements/faux-input/FauxInput.tsx
packages/forms/src/index.ts
packages/grid/src/index.ts
packages/modals/src/index.ts
packages/notifications/src/index.ts
packages/pagination/src/index.ts
packages/theming/demo/stories/ArrowStylesStory.tsx
packages/theming/demo/stories/MenuStylesStory.tsx
packages/theming/src/index.ts

- Refines type naming to match Garden typescript style guidelines.
- Removes deprecated types and interfaces
- Updates `migration.md` with changes
- ~~:globe_with_meridians: demo is up-to-date (`npm start`)~~

feat!: renames and prunes type/constant exports from packages

---

packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchInput.ts
packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts

- Use updated Garden `focusStyles`
- Restore `cursor: pointer` styling
- Fix cell content positioning shift

fix(colorpickers): `ColorSwatch` focus styling

---

package-lock.json
packages/dropdowns.legacy/demo/autocomplete.stories.mdx
packages/dropdowns.legacy/demo/combobox.stories.mdx
packages/dropdowns.legacy/demo/menu.stories.mdx
packages/dropdowns.legacy/demo/multiselect.stories.mdx
packages/dropdowns.legacy/demo/select.stories.mdx
packages/dropdowns.legacy/src/elements/Autocomplete/Autocomplete.tsx
packages/dropdowns.legacy/src/elements/Combobox/Combobox.tsx
packages/dropdowns.legacy/src/elements/Dropdown/Dropdown.tsx
packages/dropdowns.legacy/src/elements/Menu/Menu.tsx
packages/dropdowns.legacy/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns.legacy/src/elements/Select/Select.tsx
packages/dropdowns.legacy/src/elements/Trigger/Trigger.tsx
packages/grid/demo/grid.stories.mdx

Missing renamed import corrections.

fix: updates constant imports in grid story and lingering dropdowns.next references

---

package-lock.json
packages/dropdowns.next/src/elements/menu/MenuList.tsx
packages/dropdowns.next/src/elements/menu/utils.ts

Configures RTl override in Floating UI (FUI).
FUI determines RTL from `direction: rtl` in the style cascade. This PR sets an override to the [`platform` utility function](https://floating-ui.com/docs/platform#isrtl) that now points to `theme.rtl`.

fix: allows menu to position correctly in RTL

---

docs/migration.md
docs/migrations/v8.md
package-lock.json
packages/dropdowns/demo/stories/data.ts
packages/dropdowns/src/elements/combobox/OptGroup.spec.tsx
packages/dropdowns/src/elements/combobox/OptGroup.tsx
packages/dropdowns/src/elements/combobox/utils.ts
packages/dropdowns/src/types/index.ts

Adds `legend` prop to `OptGroup` + deprecates `label`

feat(dropdowns)!: replaces label prop with legend in OptGroup

---

docs/migration.md
packages/tables/README.md
packages/tables/demo/stories/TableStory.tsx
packages/tables/demo/table.stories.mdx
packages/tables/src/elements/Table.tsx
packages/tables/src/index.ts

- Creates sub-component mapping for `react-tables`
- Updates demo
- Deprecates legacy stand-alone exports 
- :memo: tested in Chrome, Firefox, Safari, and Edge

feat(tables): adds sub-component mapping

---

package-lock.json
packages/dropdowns.next/package.json

Controlled `inputValue` behavior for `Combobox` regressed in [v8.74.1](https://github.com/zendeskgarden/react-components/releases/tag/v8.74.1) due to a "cursor jump" fix in #1705. This PR updates the underlying container with a fix that keeps `inputValue` sync'd with underlying Downshift.
https://github.com/zendeskgarden/react-containers/pull/628

fix(dropdowns): controlled `Combobox` input value regression

---

docs/migration.md
packages/chrome/README.md
packages/chrome/demo/chrome.stories.mdx
packages/chrome/demo/stories/ChromeStory.tsx
packages/chrome/demo/stories/CollapsibleSubNavItemStory.tsx
packages/chrome/demo/stories/SubNavCollapsibleItem.tsx
packages/chrome/demo/subNavCollapsibleItem.stories.mdx
packages/chrome/src/elements/footer/Footer.tsx
packages/chrome/src/elements/header/Header.tsx
packages/chrome/src/elements/nav/Nav.tsx
packages/chrome/src/elements/subnav/SubNav.tsx
packages/chrome/src/index.ts

- Creates subcomponent mapping for `react-chrome`
- `FooterItem` -> `Footer.Item`
- `HeaderItem` -> `Header.Item`
- `HeaderItemIcon` -> `Header.ItemIcon`
- `HeaderItemText` -> `Header.ItemText`
- `HeaderItemWrapper` -> `Header.ItemWrapper`
- `NavItem` -> `Nav.Item`
- `NavItemIcon` -> `Nav.ItemIcon`
- `NavItemText` -> `Nav.ItemText`
- `CollapsibleSubNavItem` -> `SubNav.CollapsibleItem`
- `SubNavItem` -> `SubNav.Item`
- `SubNavItemText` -> `SubNav.ItemText`
- Updates documentation
- Deprecates legacy subcomponent exports
- ~~:guardsman: includes new unit tests. …

feat(chrome): adds sub-component mapping

---

docs/migration.md
packages/tabs/README.md
packages/tabs/demo/stories/TabsStory.tsx
packages/tabs/demo/tabs.stories.mdx
packages/tabs/src/elements/Tabs.spec.tsx
packages/tabs/src/elements/Tabs.tsx
packages/tabs/src/index.ts
packages/tooltips/demo/stories/TooltipStory.tsx
packages/tooltips/demo/tooltip.stories.mdx
packages/tooltips/src/elements/Tooltip.spec.tsx
packages/tooltips/src/elements/Tooltip.tsx
packages/tooltips/src/index.ts

- Creates sub-component mapping for `react-tabs` and `react-tooltips`
- Updates demo
- Deprecates legacy stand-alone exports 
- :memo: tested in Chrome, Firefox, Safari, and Edge

feat: adds sub-component mapping to tabs and tooltips

---

docs/migration.md
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/colorpickers/package.json
packages/datepickers/package.json
packages/drag-drop/package.json
packages/dropdowns.legacy/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/theming/package.json
packages/tooltips/package.json
packages/typography/package.json

Bumps minimum peer dep version of `styled-components` to sidestep a [bug](https://github.com/styled-components/styled-components/pull/3564) present between `v5.1.0` and `v5.3.0`.
- ~~:globe_with_meridians: demo is up-to-date (`npm start`)~~

fix: bumps styled-components peer dep to 5.3.1

---

docs/migration.md
packages/grid/README.md
packages/grid/demo/grid.stories.mdx
packages/grid/demo/stories/GridStory.tsx
packages/grid/src/elements/Col.tsx
packages/grid/src/elements/Grid.tsx
packages/grid/src/elements/Row.tsx

Adds subcomponent properties on `Grid`: `Grid.Row` and `Grid.Col`.

feat(grid): adds subcomponent mapping to Grid

---

docs/migration.md
packages/dropdowns/README.md
packages/dropdowns/demo/combobox.stories.mdx
packages/dropdowns/demo/stories/ComboboxStory.tsx
packages/dropdowns/demo/~patterns/stories/ListboxStory.tsx
packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns/src/elements/combobox/Field.tsx
packages/dropdowns/src/elements/combobox/Hint.tsx
packages/dropdowns/src/elements/combobox/Label.tsx
packages/dropdowns/src/elements/combobox/Message.tsx
packages/dropdowns/src/views/combobox/StyledHint.ts
packages/dropdowns/src/views/combobox/StyledLabel.ts
packages/dropdowns/src/views/combobox/StyledMessage.ts
packages/typography/demo/stories/data.ts

Adds sub-component mapping to `Field` (v9 `react-dropdowns`) to match `Field` (`react-forms`).

feat(dropdowns): adds subcomponent mapping to Field

---

docs/migration.md
packages/chrome/demo/stories/SheetStory.tsx
packages/theming/src/elements/ThemeProvider.spec.tsx
packages/theming/src/elements/ThemeProvider.tsx
packages/theming/src/types/index.ts
utils/test/garden-test-utils.tsx

Removes `focusVisibleRef` from `<ThemeProvider>` and updates the migration guide.
This PR also establishes the temporary `next-color` branch that will batch redesigned color palette changes until all components are ready for release on the `next` branch. Follow-on color work will verify that focus treatment is working as expected for all Garden components.

feat(theming)!: remove `focusVisibleRef` prop and polyfill scoping element

---

docs/migration.md
packages/notifications/README.md
packages/notifications/demo/alert.stories.mdx
packages/notifications/demo/notification.stories.mdx
packages/notifications/demo/stories/AlertStory.tsx
packages/notifications/demo/stories/NotificationStory.tsx
packages/notifications/demo/stories/WellStory.tsx
packages/notifications/demo/well.stories.mdx
packages/notifications/src/elements/Alert.tsx
packages/notifications/src/elements/Notification.tsx
packages/notifications/src/elements/Well.tsx
packages/notifications/src/elements/content/Close.tsx
packages/notifications/src/elements/content/Paragraph.tsx
packages/notifications/src/elements/content/Title.tsx

Adds subcomponent mapping configuration as described in `migration.md` in this PR.

feat(notifications): adds subcomponent mapping

---

docs/migration.md
packages/modals/README.md
packages/modals/demo/modal.stories.mdx
packages/modals/demo/stories/ModalStory.tsx
packages/modals/src/elements/Body.tsx
packages/modals/src/elements/Close.tsx
packages/modals/src/elements/Footer.tsx
packages/modals/src/elements/FooterItem.tsx
packages/modals/src/elements/Header.tsx
packages/modals/src/elements/Modal.spec.tsx
packages/modals/src/elements/Modal.tsx
packages/modals/src/index.ts

Adds supcomponent mapping to `Modal` along with update to `migration.md`.

feat(modals): adds subcomponent mapping to Modal

---

docs/migration.md
package-lock.json
packages/accordions/demo/stories/StepperStory.tsx
packages/accordions/demo/stories/TimelineStory.tsx
packages/accordions/src/types/index.ts
packages/breadcrumbs/src/styled/StyledChevronIcon.tsx
packages/chrome/src/elements/header/HeaderItemIcon.tsx
packages/chrome/src/elements/nav/NavItemIcon.tsx
packages/forms/src/elements/MediaInput.tsx
packages/forms/src/types/index.ts
packages/typography/src/elements/span/Icon.tsx
packages/typography/src/elements/span/StartIcon.tsx

Updates multiple packages so their `icon` prop types are consistent with other packages. Also updates several component type signatures as well.
See `migration.md` for full changelog.
There are several icon components still using `div` styled component that nest an `svg` icon inside them. I didn't touch these as they're still spreading props and setting their ref to the styled `div`, not the `svg` directly.
- …

feat: updates icon component and prop types for cross-package consistency

---

.storybook/main.js
.storybook/preview.js

Removes toolbar control for strict mode, instead making it the default behavior. Sets `framework.options.strictMode` to `true`.
This PR depends on the following PR to add this feature:

feat: use strict mode as storybook default

---

docs/migration.md
package-lock.json
packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
packages/theming/src/elements/theme/index.ts
packages/theming/src/types/index.ts
packages/theming/src/utils/getColorV8.ts

This PR adds a new `variables` section to Garden's `colors` theme. These variables will provide the precedent lookup for most Garden component colors. The BREAKING CHANGE is the removal of `colors.background` and `colors.foreground` – now obviated by the v9 variables.
The forthcoming `getColor` utility replacement PR will utilize the new `variables` to obtain light/dark mode-based colors.

feat(theming)!: add `variables` to theme `colors`

---

docs/migration.md
packages/chrome/demo/stories/ChromeStory.tsx
packages/chrome/src/elements/body/Body.tsx
packages/chrome/src/elements/body/Content.spec.tsx
packages/chrome/src/elements/body/Content.tsx
packages/chrome/src/elements/footer/Footer.tsx
packages/chrome/src/index.ts
packages/chrome/src/types/index.ts
packages/chrome/src/utils/useBodyContext.ts

Removes `hasFooter` prop from `react-chrome`'s `Body` component. Uses React context similar to how other components detect when a child is present in the JSX tree.

feat(chrome)!: detect Footer automatically with Context

---

package-lock.json
packages/dropdowns/demo/stories/ComboboxStory.tsx
packages/dropdowns/package.json
packages/dropdowns/src/elements/combobox/Option.tsx
packages/dropdowns/src/elements/combobox/Tag.tsx
packages/dropdowns/src/elements/combobox/TagGroup.tsx
packages/dropdowns/src/elements/combobox/utils.ts
packages/dropdowns/src/types/index.ts

- Carrying down the [work](https://github.com/zendeskgarden/react-containers/pull/637) from container-combobox, updating `Option` to no longer accept objects for the `value` prop.
- Updates any peripheral components which used to process objects, to now only accept strings.
- Updates migration guide.

feat(dropdowns)!: removes object type from Option `value` prop

---

packages/dropdowns.next/src/views/combobox/StyledOption.ts

Change from `overflow-wrap: break-word` to `overflow-wrap: anywhere` to prevent Option/Item content from overflowing the Listbox/Menu container.
| Before  | After |
| ------- | ----- |
| <img width="241" alt="Screenshot 2024-04-04 at 9 11 37 AM" src="https://github.com/zendeskgarden/react-components/assets/143773/9c99f60b-5077-424a-9c96-ff0feea90562">  | <img width="252" alt="Screenshot 2024-04-04 at 9 11 50 AM" src="https://github.com/zendeskgarden/react-components/assets/143773/4a152f6f-425e-425c-8307-e403e89a45d1">  |

fix(dropdowns.next): prevent combobox `Option` and menu `Item` overflow

---

packages/forms/demo/inputGroup.stories.mdx
packages/forms/demo/stories/InputGroupStory.tsx
packages/forms/src/styled/input-group/StyledInputGroup.ts

Ensures a toggled button's border stacks properly within an `<InputGroup>`.
| Before  | After |
| ------- | ----- |
| <img width="288" alt="Screenshot 2024-04-04 at 10 02 39 AM" src="https://github.com/zendeskgarden/react-components/assets/143773/f9a2e8c1-acfb-453b-b783-e5595d12b2f6"> | <img width="279" alt="Screenshot 2024-04-04 at 10 03 06 AM" src="https://github.com/zendeskgarden/react-components/assets/143773/6bc8b757-0dce-4879-b90c-dfde5450c7f0"> |

fix(forms): `InputGroup` toggle button stacking

---

docs/migration.md
packages/buttons/src/styled/StyledButton.ts
packages/chrome/src/styled/subnav/StyledSubNavItem.tsx
packages/dropdowns/src/views/combobox/StyledTrigger.ts
packages/forms/src/elements/input-group/InputGroup.spec.tsx
packages/forms/src/styled/file-list/StyledFile.ts
packages/forms/src/styled/file-upload/StyledFileUpload.ts
packages/forms/src/styled/text/StyledTextFauxInput.ts
packages/forms/src/styled/text/StyledTextInput.ts
packages/forms/src/styled/tiles/StyledTile.ts
packages/grid/src/styled/pane/StyledPaneSplitter.ts
packages/modals/src/styled/StyledClose.ts
packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts
packages/notifications/src/styled/global-alert/StyledGlobalAlertButton.ts
packages/notifications/src/styled/global-alert/StyledGlobalAlertClose.ts
packages/theming/demo/stories/ArrowStylesStory.tsx
packages/theming/demo/utilities.stories.mdx
packages/theming/src/index.ts
packages/theming/src/types/index.ts
packages/theming/src/utils/focusStyles.spec.tsx
packages/theming/src/utils/focusStyles.ts
packages/theming/src/utils/getColor.ts
packages/theming/src/utils/getFocusBoxShadow.spec.ts
packages/theming/src/utils/getFocusBoxShadow.ts
packages/theming/src/utils/menuStyles.ts

The main consumer-facing change is the replacement `color` and `spacerColor` parameters on the `getFocusBoxShadow` and `focusStyles` utilities. All other PR updates are internal and include:
- component calls to `focusStyles` and `getFocusBoxShadow` (note these are meant to have parity in this PR – redesigned light/dark color treatment will happen later)
- replacing `theming` package references to deprecated `getColorV8` and `PALETTE_V8`
- exporting utility `type` parameters
Temporary inspection of the object parameter `...args` allows the functions to straddle between v8 and v9 usage. No changes will be necessary on the `main` v8 codebase. See `getFocusBoxShadow.ts` for details.

fix(theming)!: update utilities for refactored `getColor`

---

package-lock.json
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/colorpickers/package.json
packages/datepickers/package.json
packages/drag-drop/package.json
packages/dropdowns.next/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/tooltips/package.json
packages/typography/package.json

This should've happened in conjunction with #1754 where all component packages now rely on the `getColorV8` utility. Next best is to have this go out with the next patch release. In accordance with Garden [ADR-001](https://github.com/zendeskgarden/react-components/blob/main/docs/adrs/001-theming-peer-dependency.md), this is not considered a breaking change.

fix: update theming peer dependency to ^8.75.0

---

package-lock.json
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/colorpickers/package.json
packages/datepickers/package.json
packages/drag-drop/package.json
packages/dropdowns.legacy/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/tooltips/package.json
packages/typography/package.json

`^9.0.0` version range doesn't capture prereleases and seems to still require the `--force` flag when running an install. Using `>=9.0.0-next` which captures only v9 next versions. We can revert back to `^9.0.0` right before v9 is fully published.
Separately, updates a few missed peer dep versions from #1779.

fix(deps): use -next versions for react-theming peer dep

---

packages/accordions/src/elements/accordion/components/Header.tsx
packages/accordions/src/elements/timeline/components/Content.tsx
packages/accordions/src/styled/accordion/StyledRotateIcon.spec.tsx
packages/accordions/src/styled/accordion/StyledRotateIcon.ts
packages/accordions/src/styled/timeline/StyledItemIcon.ts
packages/theming/src/index.ts
packages/theming/src/styled/StyledBaseIcon.ts
packages/theming/src/utils/StyledBaseIcon.ts

Adds the base styled icon component to `react-theming`, along with updates to two components to demonstrate usage.
A follow up PR will update the remaining component instances (13 in total).
The primary goals of this base component:
- Make the `cloneElement` call centralized
- Omit `theme` from the resulting prop spread
Separately, using this PR as an opportunity for [transient props](https://styled-components.com/docs/faqs#transient-props-since-51) to prevent further prop-to-DOM leaking in the affected components.

feat: adds styled icon base component

---

packages/notifications/src/elements/Notification.spec.tsx
packages/notifications/src/elements/Notification.tsx
packages/notifications/src/elements/content/Close.tsx

- Sets `Nofitication`'s role to `alert` to improve compatibility with JAWS, Narrator, and NVDA.
- Set `aria-hidden` to Notification's `Close` button to improve UX. 
I've tested the following combinations using the latest version of the browser and screen-reader:
- Chrome + JAWS
- Chrome + NVDA
- Edge + Narrator
- Chrome + Narrator
- Chrome + VoiceOver
- Safari + VoiceOver
1. "Incremental notifications": This is current pattern where a role of `status` or `alert` is applied to `Notification`. When the Notification incrementally mounts, the SR will read out loud its content.
2. "Persistent `aria-live` region": This region has an `aria-live` attribute set to either `polite` or `assertive` and is mounted by the `ToastProvider` on load. Changes to its content will be announced incrementally by …

fix(Notifications): improve screen-reader support

---

packages/colorpickers/src/styled/ColorPicker/StyledAlphaRange.ts
packages/colorpickers/src/styled/ColorPicker/StyledPreview.ts
packages/colorpickers/src/styled/ColorPickerDialog/StyledButtonPreview.ts
packages/theming/demo/stories/GetColorStory.tsx
packages/theming/src/index.ts
packages/theming/src/types/index.ts
packages/theming/src/utils/getCheckeredBackground.spec.ts
packages/theming/src/utils/getCheckeredBackground.ts
packages/theming/src/utils/getColor.ts

...and swap out redundant usage.
Note that final checkered colors will be established throughout the v9 design cycle. The `'border.default'` variable was a best guess for now (and closest to the existing v8 color).

feat(theming): add new `getCheckeredBackground` utility

---

docs/migration.md
packages/chrome/README.md
packages/chrome/demo/stories/ChromeStory.tsx
packages/chrome/src/elements/header/HeaderItem.spec.tsx
packages/chrome/src/elements/nav/NavItem.spec.tsx
packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
packages/chrome/src/styled/nav/StyledLogoNavItem.ts
packages/chrome/src/types/index.ts
packages/theming/src/elements/palette/__snapshots__/index.spec.ts.snap
packages/theming/src/elements/palette/index.ts

Removes references to `PALETTE.product.message` and `PALETTE.product.connect`. Updates migration guide.

feat!: removes stale product colors from palette

---

packages/datepickers/demo/datepicker.stories.mdx
packages/datepickers/demo/stories/DatepickerStory.tsx
packages/forms/src/styled/text/StyledTextInput.ts

Implements a general sibling combinator for `Message`s in a `Field`. This way an `Input` and`Message` can have intermediary elements but the latter can still space correctly (like in the case of `DatePicker`).
Currently, `DatePicker` doesn't hvae any spacing when a `Message` is present. This happens because the menu wrapper sits between them, and the existing adjacent sibling combinator invalidates this scenario:
Compare to `Input`, which has the correct `margin-top` when a `Message` is used:
Now using the general sibling combinator:
- …

fix(forms): updates Message to receive margin when intermediaries are present

---

CHANGELOG.md
docs/changelogs/v8.md
package-lock.json
packages/datepickers/demo/datePicker.stories.mdx
packages/datepickers/demo/stories/DatePickerStory.tsx
packages/forms/src/styled/text/StyledTextInput.ts

Sync `main@8.76.2` into `next`

chore(next): update from `main@8.76.2`

---

CHANGELOG.md

Reverts prettier auto-formatting caused by https://github.com/zendeskgarden/react-components/pull/1801/commits/54ed37105f2765539b4bd7d104084892dca4af4e

chore(CHANGELOG): remove extra lines

---

.storybook/preview.js
packages/theming/demo/utilities.stories.mdx
packages/theming/src/utils/getColor.ts

Adds two new global Storybook controls, `colors.dark` and `colors.light` under a dedicated "Variables" section that allows color variable tweaks for every component demo.

chore(storybook): add global dark/light color variables control

---

package-lock.json
packages/drag-drop/demo/~patterns/stories/components.tsx
packages/drag-drop/package.json
packages/drag-drop/src/elements/dropzone/Dropzone.spec.tsx
packages/drag-drop/src/styled/draggable-list/StyledDropIndicator.ts
packages/drag-drop/src/styled/draggable/StyledDraggable.spec.tsx
packages/drag-drop/src/styled/draggable/StyledDraggable.ts
packages/drag-drop/src/styled/draggable/StyledGrip.ts
packages/drag-drop/src/styled/dropzone/StyledDropzone.ts

Colors updated for the following components & stories using new v9 color palette:
- Draggable
- Draggable.Grip
- DraggableList.DropIndicator
- Dropzone

feat(drag-drop): adds light/dark mode colors

---

packages/modals/src/styled/StyledModal.ts

Increases `box-shadow` opacity to 80% in dark mode to match latest design specs

fix(modals): increase `box-shadow` opacity in dark mode 

---

packages/buttons/src/styled/StyledIconButton.spec.tsx
packages/buttons/src/styled/StyledIconButton.ts

Design brought this color mismatch to our attention. Icons should be `foreground.subtle`.

fix(buttons): update `IconButton` foreground color

---

packages/tags/src/elements/Tag.spec.tsx
packages/tags/src/styled/StyledClose.ts
packages/tags/src/styled/StyledTag.spec.tsx
packages/tags/src/styled/StyledTag.ts
packages/tags/src/types/index.ts

Verified the following in both light and dark modes:
- `<Tag>`
- `<Tag hue="grey">` and `<Tag hue="neutralHue">`
- `<Tag hue="blue">` and `<Tag hue="primaryHue">`
- `<Tag hue="red">` and `<Tag hue="dangerHue">`
- `<Tag hue="green">` and `<Tag hue="successHue">`
- `<Tag hue="yellow">` and `<Tag hue="warningHue">`
- `<Tag hue="azure">`
- `<Tag hue="lemon">`
- `<Tag hue="#FD5A1E">`
Note there are two outstanding questions with design:
- Dark mode color for `<Tag hue="grey">`
- Hover (focus?) treatment for the `Tag.Close` button
Note that when testing with Storybook, a string can be manually entered into the `hue` color picker – often resulting in an error. Simply click the "Remount component" button in the toolbar once you've entered the correct value.

feat(tags): new light/dark mode colors

---

packages/dropdowns.legacy/src/styled/menu/StyledMenu.ts
packages/dropdowns/src/views/menu/StyledMenu.ts
packages/theming/demo/stories/ArrowStylesStory.tsx
packages/theming/src/utils/arrowStyles.spec.tsx
packages/theming/src/utils/arrowStyles.ts

Improves `arrowStyles` to avoid overcast issues on arrow border when drop shadows are applied to the arrow container.
Using an extreme case to highlight the impact of drop shadows on the arrow border
- Two boxes clipped into a triangular shape lay over each other
- `::before` (in pink) inherits the border styles from container. The clipping mask is set so that the border smoothly merges with the container's (using `inset == 0`). The overlap is meant to prevent a gap due to pixel rounding.
- `::after` (in green) has a transparent border and a clipping mask that slightly extends upward to conceal the container's border without hiding its content.
reviewer)

fix: refine `arrowStyles` CSS to avoid overcast issues with drop shadows

---

packages/tooltips/src/elements/Tooltip.spec.tsx
packages/tooltips/src/styled/StyledTooltip.ts

Adds light / dark mode support for Tooltips

feat(tooltips): new light/dark mode colors

---

packages/tooltips/src/elements/Tooltip.spec.tsx
utils/test/garden-test-utils.tsx

Adds a small utility fn to `garden-test-utils` to simplify testing across color modes. `getRenderFn` returns the correct `render` fn for the `mode`.
`getRenderFn` aims to reduce boilerplate code when testing colors in multiple modes using `it.each()`. 
See this [comment](https://github.com/zendeskgarden/react-components/pull/1818#discussion_r1619349923).

test: add `getRenderFn` utility

---

packages/tabs/src/elements/Tab.tsx
packages/tabs/src/elements/TabList.tsx
packages/tabs/src/elements/TabPanel.tsx
packages/tabs/src/elements/Tabs.tsx
packages/tabs/src/styled/StyledTab.ts
packages/tabs/src/styled/StyledTabList.ts
packages/tabs/src/styled/StyledTabPanel.ts
packages/tabs/src/styled/StyledTabs.ts
packages/tabs/src/utils/useTabsContext.ts

The previous `verticalStyling` catch-all function in `StyledTabs` was not well-structured, allowing component CSS to leak into child `Tabs` so that if any parent sets the `isVertical` prop, all children would be vertically styled regardless of their `isVertical` prop setting.
This PR eradicates the `verticalStyling` function by portioning all of its properties out to relevant components, conditionally and precisely applying CSS depending on the context. The updated styles follow Garden's [API rules](https://github.com/zendeskgarden/react-components/blob/main/docs/api.md#rules) by utilizing `sizeStyles` and `colorStyles` accordingly.
closes #1817

fix(tabs): prevent `isVertical` styling cascade

---

package-lock.json
packages/theming/package.json
packages/theming/src/utils/getColor.spec.ts
packages/theming/src/utils/getColor.ts

This PR follows up on https://github.com/zendeskgarden/react-components/pull/1798 and generates a 12-step color scale using the very lightweight [color2k](https://color2k.com/) library.
Garden's color palette were generated using [Leonardo](https://leonardocolor.io/#) using the following offset-based contrast ratios.
```
const targetRatios = {
100: 1.08,
200: 1.2,
300: 1.35,
400: 2,
500: 2.8,
600: 3.3,
700: 5,
800: 10,
900: 13,
1000: 16,
1100: 17.5,
1200: 19.5
};
```
`generateColorScale` generates a 200 color scale with [Color2K](https://color2k.com/) and returns a color scale object. Each key is an offset value and the corresponding value is the color that best matches the target contrast ratio for that offset. 🎨 
See [demo](https://stackblitz.com/edit/vitejs-vite-1v4hhp?file=src%2FApp.ts …

refactor(theming): improves custom color scale generation

---

docs/migration.md
package-lock.json
packages/tables/package.json
packages/tables/src/elements/Cell.tsx
packages/tables/src/elements/GroupRow.tsx
packages/tables/src/elements/Head.tsx
packages/tables/src/elements/HeaderCell.tsx
packages/tables/src/elements/HeaderRow.tsx
packages/tables/src/elements/OverflowButton.spec.tsx
packages/tables/src/elements/OverflowButton.tsx
packages/tables/src/elements/Row.spec.tsx
packages/tables/src/elements/Row.tsx
packages/tables/src/elements/SortableCell.tsx
packages/tables/src/elements/Table.tsx
packages/tables/src/styled/StyledBaseRow.ts
packages/tables/src/styled/StyledCell.ts
packages/tables/src/styled/StyledGroupRow.ts
packages/tables/src/styled/StyledHead.spec.tsx
packages/tables/src/styled/StyledHead.ts
packages/tables/src/styled/StyledHeaderCell.ts
packages/tables/src/styled/StyledHeaderRow.ts
packages/tables/src/styled/StyledOverflowButton.ts
packages/tables/src/styled/StyledRow.ts
packages/tables/src/styled/StyledSortableButton.ts
packages/tables/src/styled/StyledTable.ts
packages/tables/src/styled/index.ts
packages/tables/src/styled/style-utils.ts

Adds `light` / `dark` mode support for Table components.
In addition to updating to light/dark compatibility, this PR also:
- Uses base styling from `IconButton` for `OverflowButton` (with height/width overrides)
- Removes `isHovered`, `isFocused`, and `isActive` props from `OverflowButton`

feat(tables): new light/dark mode colors

---

packages/grid/demo/grid.stories.mdx
packages/grid/src/styled/StyledCol.ts
packages/grid/src/styled/StyledGrid.ts
packages/grid/src/styled/StyledRow.ts
packages/grid/src/styled/pane/StyledPaneSplitter.ts
packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts

Completed recolor work for `Pane.Splitter`, `Pane.SplitterButton` and `<Grid debug>`

feat(grid): new light/dark mode colors

---

packages/modals/demo/stories/TooltipModalStory.tsx
packages/modals/src/elements/TooltipModal/Close.tsx
packages/modals/src/styled/StyledDrawer.spec.tsx
packages/modals/src/styled/StyledDrawer.ts
packages/modals/src/styled/StyledDrawerFooter.ts
packages/modals/src/styled/StyledModal.ts
packages/modals/src/styled/StyledTooltipModalBody.ts
packages/modals/src/styled/StyledTooltipModalClose.ts
packages/modals/src/styled/StyledTooltipModalTitle.ts

Part 2 of the Modals [recoloring](https://github.com/zendeskgarden/react-components/pull/1808) effort. 
- Adds light / dark mode colors to `TooltipModal` and `Drawer`
- Fix Modal shadows to align with latest wires

feat(modals): new light/dark mode colors for `TooltipModal` and `Drawer`

---

packages/tabs/src/elements/Tab.tsx
packages/tabs/src/elements/TabList.tsx
packages/tabs/src/elements/TabPanel.tsx
packages/tabs/src/elements/Tabs.tsx
packages/tabs/src/styled/StyledTab.ts
packages/tabs/src/styled/StyledTabList.ts
packages/tabs/src/styled/StyledTabPanel.ts
packages/tabs/src/styled/StyledTabs.ts

Adds new light/dark mode colors to `Tabs`
- Adds new light/dark mode colors to `Tabs`
- Refactors using transient props

feat(tabs): new light/dark mode colors

---

packages/pagination/src/styled/OffsetPagination/StyledGapListItem.ts
packages/pagination/src/styled/OffsetPagination/StyledList.ts
packages/pagination/src/styled/OffsetPagination/StyledPageBase.spec.tsx
packages/pagination/src/styled/OffsetPagination/StyledPageBase.ts

Components updated:
- `OffsetPagination`
- `CursorPagination`

feat(pagination): new light/dark mode colors

---

packages/breadcrumbs/src/elements/Breadcrumb.spec.tsx
packages/breadcrumbs/src/elements/Breadcrumb.tsx
packages/breadcrumbs/src/styled/StyledBreadcrumbItem.spec.tsx
packages/breadcrumbs/src/styled/StyledBreadcrumbItem.ts
packages/breadcrumbs/src/styled/StyledChevronIcon.tsx

Updates breadcrumbs with V9 colors.

feat(breadcrumbs): adds light/dark mode colors

---

packages/avatars/demo/stories/AvatarStory.tsx
packages/avatars/demo/~patterns/stories/MenuStory.tsx
packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
packages/avatars/package.json
packages/avatars/src/elements/Avatar.spec.tsx
packages/avatars/src/elements/Avatar.tsx
packages/avatars/src/elements/StatusIndicator.tsx
packages/avatars/src/styled/StyledAvatar.spec.tsx
packages/avatars/src/styled/StyledAvatar.ts
packages/avatars/src/styled/StyledStandaloneStatusIndicator.ts
packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
packages/avatars/src/styled/StyledStatusIndicator.ts
packages/avatars/src/styled/StyledStatusIndicatorBase.ts
packages/avatars/src/styled/utility.ts

Updates `Avatar` and `StatusIndicator` with new color palette.
Also updates pattern examples to use [Menu](https://garden.zendesk.com/components/menu).

feat(avatars): adds light/dark mode colors

---

.github/workflows/ci.yaml

Lets `renovate[bot]` + `dependabot[bot]` automatically deploy to staging

ci: let known `[bots]` deploy to staging

---

packages/tooltips/src/styled/StyledTooltip.ts

- Increases arrow size for small / med tooltips by modifying inset value

fix(tooltips): increase arrow size for small / med tooltips

---

packages/typography/src/elements/CodeBlock.spec.tsx
packages/typography/src/styled/StyledCodeBlockLine.spec.tsx
packages/typography/src/styled/StyledCodeBlockLine.ts
packages/typography/src/styled/StyledCodeBlockToken.ts

This PR accommodates some `CodeBlock` color design tweaks for:
- line numbering
- line highlighting
- diff foreground/background

fix(typography): `CodeBlock` colors

---

packages/colorpickers/demo/stories/data.ts
packages/colorpickers/src/elements/ColorPicker/ColorWell.tsx
packages/colorpickers/src/elements/ColorPicker/index.tsx
packages/colorpickers/src/elements/ColorPickerDialog/index.tsx
packages/colorpickers/src/elements/ColorSwatch/index.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
packages/colorpickers/src/styled/ColorPicker/StyledAlphaRange.ts
packages/colorpickers/src/styled/ColorPicker/StyledColorPicker.ts
packages/colorpickers/src/styled/ColorPicker/StyledColorWell.ts
packages/colorpickers/src/styled/ColorPicker/StyledColorWellThumb.ts
packages/colorpickers/src/styled/ColorPicker/StyledHueRange.ts
packages/colorpickers/src/styled/ColorPicker/StyledPreview.ts
packages/colorpickers/src/styled/ColorPicker/StyledSliders.ts
packages/colorpickers/src/styled/ColorPickerDialog/StyledButtonPreview.ts
packages/colorpickers/src/styled/ColorSwatch/StyledColorSwatchLabel.ts
packages/colorpickers/src/styled/common/StyledRange.spec.tsx
packages/colorpickers/src/styled/common/StyledRange.ts
packages/colorpickers/src/styled/types.ts
packages/colorpickers/src/types/index.ts

Adds dark / light mode support to `@zendeskgarden/react-colorpickers`
- Adds dark / light mode support to `ColorPicker`, `ColorPickerDialog`, `ColorSwatch`, and `ColorSwatchDialog`
- Simplify CSS with `isOpaque` option
- Use transient props to avoid invalid DOM attributes

feat(colorpickers): adds light/dark mode colors

---

packages/chrome/src/styled/StyledSkipNav.ts
packages/chrome/src/styled/header/StyledHeader.ts
packages/draggable/src/styled/draggable/StyledDraggable.ts
packages/forms/src/styled/range/StyledRangeInput.ts
packages/grid/src/styled/pane/StyledPaneSplitterButtonContainer.ts
packages/modals/src/styled/StyledDrawer.ts
packages/modals/src/styled/StyledModal.ts
packages/notifications/src/styled/StyledBase.ts
packages/theming/demo/stories/ArrowStylesStory.tsx
packages/theming/src/elements/ThemeProvider.spec.tsx
packages/theming/src/elements/theme/__snapshots__/index.spec.ts.snap
packages/theming/src/elements/theme/index.ts
packages/theming/src/types/index.ts
packages/theming/src/utils/menuStyles.ts
packages/tooltips/src/styled/StyledTooltip.ts

Provides a light/dark variable set for shadow sizes `small`, `medium`, and `large`. Updates relevant components that currently define custom `neutralHue` colors with dark/light transparency overrides in `v9` styles:
- Chrome – `SkipNav` and `Header`
- `Draggable`
- `RangeInput`
- `PaneSplitterButton` (container)
- Modals – `Modal` and `Drawer`
- `Notification`
- Theming – `menuStyles`
- `Tooltip` (including when `isLight` is given)

feat(theming): adds shadow variables to theme + updates styled components

---

packages/dropdowns.legacy/src/elements/Combobox/Combobox.spec.tsx
packages/dropdowns.legacy/src/styled/items/StyledAddItem.ts
packages/dropdowns.legacy/src/styled/items/StyledItem.spec.tsx
packages/dropdowns.legacy/src/styled/items/StyledItem.ts
packages/dropdowns.legacy/src/styled/items/StyledItemIcon.ts
packages/dropdowns.legacy/src/styled/items/StyledItemMeta.ts
packages/dropdowns.legacy/src/styled/items/StyledNextIcon.tsx
packages/dropdowns.legacy/src/styled/items/StyledPreviousIcon.tsx
packages/dropdowns.legacy/src/styled/items/header/StyledHeaderIcon.ts
packages/dropdowns.legacy/src/styled/menu/StyledSeparator.ts
packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectMoreAnchor.ts

IMPORTANT REVIEWER NOTE: due to the fact that this is a deprecated package, I took a path of minimal code disruption. Meaning 1:1 `getColorV8` -> `getColor` replacements and:
- no `$prop` updates (we can decide if this needs to happen after v9 releases)
- no `colorStyles` & `sizeStyles` consolidation
- no style enhancements (such as the primary blue border for active options / focused items) to emphasize the importance of a a11y upgrade to Garden's new `Combobox` & `Menu`

feat(dropdowns.legacy): new light/dark mode colors

---

docs/migration.md
package-lock.json
packages/buttons/demo/anchor.stories.mdx
packages/buttons/src/elements/Anchor.spec.tsx
packages/buttons/src/elements/Anchor.tsx
packages/buttons/src/elements/Button.spec.tsx
packages/buttons/src/elements/Button.tsx
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/types/index.ts

The same default styling applies to `<Button isLink>`. Due to expected usage, the link-styled `Button` does not offer a capability to remove the underline. Note that existing hover/focus/active styling remains unchanged.

feat(buttons): underline `Anchor` by default

---

packages/chrome/src/styled/body/StyledContent.tsx
packages/chrome/src/styled/sheet/StyledSheetBody.ts
packages/dropdowns/src/views/combobox/StyledTrigger.ts
packages/grid/src/styled/StyledGrid.ts
packages/grid/src/styled/pane/StyledPaneContent.ts
packages/modals/src/styled/StyledBody.ts
packages/modals/src/styled/StyledDrawerBody.ts
packages/modals/src/styled/StyledTooltipModalBody.ts
packages/tabs/src/styled/StyledTabList.ts
packages/tabs/src/styled/StyledTabPanel.ts
packages/theming/src/utils/menuStyles.ts

Currently, system controls (scrollbars) are forced to their default color even in Garden dark mode (`normal`).
This PR sets the `color-scheme` property throughout several components to ensure system controls switch between light and dark theme alongside Garden's theme.
To ensure the theme is retained regardless of system settings, the value is set using the `only` keyword ([see spec](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#syntax)).
To test, I include the following snippet inside the content of the affected component in dark theme (and then swap the value to `dark` when testing light theme).
```
<ThemeProvider theme={pt => ({ ...pt, colors: { ...pt.colors, base: 'light' } })}>
Nested content
</ThemeProvider>
```
I then applied `overflowY` or `overflowX` with `auto` …

feat: applies color-scheme to align garden and system themes

---

packages/dropdowns.next/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns.next/src/views/combobox/StyledTrigger.ts

The styling of `<Combobox isBare>` would break for users with OS settings set to always show scrollbars.
This update fixes it by setting the `overflow-y` of the input wrapper to `visible` when `isBare` is enabled. After fix:

fix(dropdowns.next): `Combobox` with `isBare` option never shows horiz scrollbar to preserve styling

---

packages/dropdowns.legacy/src/styled/menu/StyledMenu.ts
packages/dropdowns/src/views/menu/StyledMenu.ts
packages/theming/src/utils/arrowStyles.spec.tsx
packages/theming/src/utils/arrowStyles.ts
packages/tooltips/src/elements/Tooltip.spec.tsx
packages/tooltips/src/styled/StyledTooltip.ts

This PR refines the `arrowStyles` logic to output deterministic arrow dimensions.
- Simplifies Tooltip styles to avoid relying on arrow `inset`
- Ensures the rendered height of the arrow matches with the `size` argument
For this example, `ArrowStylesStory` was modified to display a box-shadow matching the arrow `size` input. 
```
box-shadow: ${p => p.hasBoxShadow && `0 0 0 ${p.size}px lavender`};
```
This preview shows the impact of changing the `size` and `inset` inputs. The arrow was recolored to better show its dimensions.
Notice that the tip of the arrow ends where the drop shadow ends.
As a result, tooltip arrow rendered sizes match with V8:

fix(tooltips): renders correct arrow dimensions based on tooltip size

---

packages/accordions/demo/stories/TimelineStory.tsx
packages/accordions/src/styled/timeline/StyledItemIcon.ts
packages/accordions/src/types/index.ts
packages/avatars/demo/stories/AvatarStory.tsx
packages/avatars/demo/~patterns/stories/MenuStory.tsx
packages/avatars/src/styled/StyledAvatar.spec.tsx
packages/avatars/src/styled/StyledAvatar.ts
packages/avatars/src/types/index.ts
packages/tags/src/types/index.ts
packages/typography/demo/code.stories.mdx
packages/typography/src/elements/span/Span.spec.tsx
packages/typography/src/styled/StyledFont.tsx
packages/typography/src/types/index.ts

Updates related prop documentation and sets the following props to be able to receive color variable key strings:
- Timeline.Item `surfaceColor`
- Avatar
- `backgroundColor`
- `foregroundColor`
- `surfaceColor`
- Span `hue`
`Tag` is a description update only as the primary `hue` colors already received intended light/dark treatment.

feat: allow color-related props to receive color variable keys in addition to hex values

---

docs/migration.md

Removed in #1702 but slipped past the doc :wink:

chore(theming): add `withTheme` removal to migration guide

---

packages/dropdowns.next/src/elements/menu/ItemGroup.tsx

Garden `Menu` closely follows APG menu examples by providing a transient `li` around grouped items. They don't clarify in the attributes table, but this element needs `role="none"` or there will be semantic HTML violations, as shown in the Storybook when Menu is expanded:

fix(dropdowns.next): adds missing role to ItemGroup

---

packages/forms/src/elements/common/Message.spec.tsx
packages/forms/src/styled/common/StyledMessageIcon.ts

This fixes an accessibility issue to ensure the `Message` icon's `aria-label` is available to screen readers.

fix(forms): ensure `Message` validation icon has a role of "img"

---

packages/modals/src/styled/StyledFooter.spec.tsx
packages/modals/src/styled/StyledFooter.ts
packages/theming/src/index.ts

This is a v9 cleanup PR to remove the `PALETTE_V8` export (undocumented for Garden internal use only; no migration docs needed) and fixes a missed variable color treatment for Chrome `Footer`.

chore(theming): remove `PALETTE_V8` export

---

package-lock.json
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/colorpickers/package.json
packages/datepickers/package.json
packages/draggable/package.json
packages/dropdowns.legacy/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/theming/package.json
packages/tooltips/package.json
packages/typography/package.json

This PR gets the peer dependency ranges on `react` and `react-dom` dialed-in for v9. The previous `>=16.8.0` notation [accurately](https://semver.npmjs.com/) includes everything since React hooks. However, some package managers incorrectly report React 18 (for example) as an invalid peer. The updated `^16.8.0 || ^17.0.0 || ^18.0.0` _or_ will satisfy all package managers. More importantly, the top end of the range is capped at v18 so Garden can manage the addition of future React versions _after_ testing.

fix: React peer dependency ranges

---

.github/workflows/ci.yaml
lerna.json

Configures `v8` for future CI, version, and publish against Garden's version 8 codebase. No further v8 development will occur on `main` – which will become the new v9 home for Garden.

chore: configure `v8` branch for maintenance

---

docs/migration.md

Repeat of #1895 on `main` with updated commits.

docs: enhance migration guide

---

packages/avatars/src/styled/StyledAvatar.spec.tsx
packages/avatars/src/styled/StyledAvatar.ts

Fixes bug introduced in #1885 where `Avatar` with `status` defaulted to transparent background.
Before vs. avatar:
- ~~:globe_with_meridians: demo is up-to-date (`npm start`)~~

fix(avatars): use default background surfaceColor with statuses

---

packages/theming/src/utils/arrowStyles.ts
packages/tooltips/src/styled/StyledTooltip.ts

Fixes a regression created in https://github.com/zendeskgarden/react-components/pull/1882
- Refines `defaultInset` to better render on retina and regular monitors 
- Adds ability to shift the arrow placement alongside the edge of the parent container. This addresses the case when a parent container is too short for be supported by the default arrow placement logic.
For example:
The arrow of a small tooltip using `end-bottom` placement will extend past the container's boundaries because of the border-radius

fix(tooltips): fix arrow position when using `end-bottom` placement

---

.github/workflows/ci.yaml
utils/scripts/tag.mjs

Pulls in the fix from `main` (previously made on `next` v9).

fix: ensure `tag` script releases to the correct default branch

---

packages/avatars/src/styled/StyledAvatar.spec.tsx
packages/avatars/src/styled/StyledAvatar.ts
packages/avatars/src/styled/StyledStatusIndicator.spec.tsx
packages/avatars/src/styled/StyledStatusIndicator.ts
packages/avatars/src/styled/StyledStatusIndicatorBase.ts

Fix `StatusIndicator` styling to match [v7](https://606fa12ea4f2996a9cfd97aa--zendeskgarden.netlify.app/avatars/#text)
- Allows `StatusIndicator` to stretch up to a `max-size`
- Fix `StatusIndicator` positioning for large `Avatar`

fix(avatars): rectify `StatusIndicator` sizing and position

---

packages/tabs/src/styled/StyledTabList.ts

Improves Tab border animation when toggling between light / dark mode.
See https://github.com/zendeskgarden/website/pull/626#issuecomment-2289073829.
A more comprehensive PR to cover other color transitions will follow.

fix(tabs): add border-color transition for smoother animation

---

packages/tags/src/types/index.ts

This small fix addresses a doc problem seen on the website where the "colors" link is incorrectly set to an external URL.
**Before**
**After**

fix(tags): ensure prop sheet refers to internal website URL

---

packages/tabs/src/styled/StyledTab.ts

This CSS update more effectively distinguishes between `border-[side]`, `border-width`, and `border-color`, allowing any one of these properties to be set independently without interfering with the others.
Needed to handle a website example regression seen with https://garden.zendesk.com/components/theme-provider#targeting.

fix(tabs): border styling

---

packages/tabs/src/styled/StyledTab.ts

This fix allows for the Tab's focus ring to resize based on Tab single / multi line content. 
The focus ring's height on a single line `Tab` content was kept at 20px
Users rendering an icon above the Tab label may need place the icon accordingly to avoid an overlap with the focus ring.
Here's a [sandbox](https://codesandbox.io/p/sandbox/icon-tabs-forked-rh479h) with the fix applied demonstrating this use-case.

fix(tabs): allow focus ring to resize based on content

---

packages/typography/src/styled/StyledCodeBlock.ts

Sets the background color for `CodeBlock` to `background.recessed` in order to offset from the default background in dark mode.

fix(typography): set `CodeBlock` background to `background.recessed`

---

docs/adrs/002-theme-default-prop-removal.md
docs/adrs/README.md

Adds the "Removal of `theme` default prop" ADR. See reference PR for context: https://github.com/zendeskgarden/react-components/pull/1905

docs: add removal of `theme` default prop ADR

---

packages/dropdowns/src/elements/menu/MenuList.tsx
packages/theming/src/utils/menuStyles.ts

Fixes three subtle bugs between `Menu` and `Combobox` to prevent mouse interactivity of menus/listboxes until animation is complete.
Before:
https://github.com/user-attachments/assets/da5f6e42-1b0f-4ffe-8c37-ff09d1d93da8
After:
https://github.com/user-attachments/assets/81b7d753-e460-4179-b683-9123d9ace604
Prevents `StyledFloatingMenu`from rendering before its children (keeping in lock step with the [child render condition](https://github.com/zendeskgarden/react-components/blob/main/packages/dropdowns/src/elements/menu/MenuList.tsx#L160)). This stops a 2px wide box from occasionally rendering in the milliseconds before items have populated.
Before:
https://github.com/user-attachments/assets/36235913-464a-46eb-923c-689cdba0a15b
After: …

fix(dropdowns): prevents menus focus focusing items early during animation

---

packages/modals/src/styled/StyledTooltipDialog.ts
packages/modals/src/styled/StyledTooltipDialogTitle.ts

Adds end padding to first descendant of `StyledTooltipDialog` if `Close` btn exists

fix(tooltips): ensure correct padding for `TooltipDialog`'s inner elements if `Close` btn exists

---

packages/chrome/src/elements/sheet/Sheet.spec.tsx
packages/chrome/src/elements/sheet/Sheet.tsx
packages/chrome/src/styled/sheet/StyledSheet.ts

Applies `inert` attribute when the `Sheet` is closed in order to prevent tab focus through the sheet's interactive elements.

fix(chrome): prevent focus on closed `Sheet`

---

docs/migration.md

This PR is meant to add clarity for teams getting started with the migration process, as we've heard from a few teams that these initial steps aren't immediately clear.
For best reviewing experiencing, see the rich markdown file [here](https://github.com/zendeskgarden/react-components/blob/8abcc5b442029b093677606f88f118c48b436589/docs/migration.md), under breaking changes near the start of the guide.

docs: adds verbosity to initial v9 migration steps

---

packages/loaders/src/elements/Dots.spec.tsx
packages/loaders/src/elements/Inline.spec.tsx
packages/loaders/src/elements/Progress.spec.tsx
packages/loaders/src/styled/StyledInline.ts
packages/loaders/src/styled/StyledProgress.ts
packages/loaders/src/styled/StyledSVG.spec.tsx
packages/loaders/src/styled/StyledSVG.ts
packages/loaders/src/types/index.ts
packages/theming/src/utils/getColor.spec.ts
packages/theming/src/utils/getColor.ts

Follow-on from #1885 that rounds out color variable prop treatment for `loaders`.
Improves `getColor` to allow for `inherit` and `currentcolor` keywords in addition to `transparent` (which is already supported).

feat(loaders): allow color props to receive color variable keys in addition to hex values

---

packages/avatars/demo/avatar.stories.mdx
packages/colorpickers/src/elements/ColorSwatch/index.tsx

The `z-index` fix prevents the following stacking problem with `<ColorSwatchDialog hasArrow>`...
Slips in a `string` control fix for `<Avatar badge="...">`

fix(colorpickers): prevent arrow from positioning over a `ColorSwatchDialog` tooltip

---

docs/changelogs/v6.md
docs/changelogs/v7.md
docs/changelogs/v8.md
docs/migration.md
docs/migrations/v6.md
docs/migrations/v7.md
packages/colorpickers/src/elements/ColorPickerDialog/index.tsx
packages/colorpickers/src/elements/ColorSwatchDialog/index.tsx
packages/modals/src/elements/TooltipDialog/TooltipDialog.tsx
packages/modals/src/types/index.ts
packages/theming/demo/stories/GetColorStory.tsx

- expose `TooltipModal` internal-only `offset` prop to decrease space between `ColorPickerDialog`/`ColorSwatchDialog` and trigger (per designs)
- prevent render thrashing on `getColor` storybook demo
- split migration guides out of historical changelogs for improved `website` documentation

chore: v9 QA sweep

---

packages/breadcrumbs/demo/stories/BreadcrumbStory.tsx

This fix aligns the Storybook demo with the v9 `website` and intended designs

chore(breadcrumbs): remove `Anchor` underline in demo

---

packages/dropdowns/src/elements/menu/Menu.tsx

Adds missing `restoreFocus` prop description for `Menu`.

docs: add missing `restoreFocus` prop description in `Menu`'s StoryBook page

---

.github/workflows/ci.yaml
package-lock.json
package.json

Uses `coverallsapp/github-action` to restore Coveralls PR comments. Speed up test job. 🚄 
- Uses and pins `coverallsapp/github-action` to commit SHA associated with latest v2.3.0 (see [best-practices](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions))
- Removes `coveralls` npm package
- Restores missing PR comments
- Speeds up `test` job by running test concurrently (removed `--runInBand`):
- before: [2m50s](https://github.com/zendeskgarden/react-components/actions/runs/11059811052/job/30729248993)
- after: [1m47s](https://github.com/zendeskgarden/react-components/actions/runs/11078039523/job/30784742139)
- Confirmed reports upload [successfully](https://coveralls.io/builds/70048435).

ci: restore Coveralls PR comments

---

packages/tables/src/styled/StyledOverflowButton.ts

Replaces invalid `<div>` from Table `OverflowButton` w/ `<span>`
- According to [W3 specs](http://www.w3.org/TR/2012/WD-html5-20120329/the-button-element.html#the-button-element), a <button> must contain only Phrasing content. Phrasing content is defined as including `<span>` but not `<div>`.
- Related to changes made to OverflowButton in https://github.com/zendeskgarden/react-components/pull/1833

fix(tables): replace invalid `<div>` from Table `OverflowButton` w/ `<span>`

---

packages/chrome/src/elements/SkipNav.tsx
packages/chrome/src/elements/body/Content.tsx
packages/chrome/src/elements/header/Header.tsx
packages/chrome/src/elements/header/HeaderItem.tsx
packages/chrome/src/elements/header/HeaderItemText.tsx
packages/chrome/src/elements/nav/Nav.tsx
packages/chrome/src/elements/nav/NavItem.tsx
packages/chrome/src/elements/nav/NavItemText.tsx
packages/chrome/src/elements/sheet/Sheet.tsx
packages/chrome/src/elements/sheet/components/Footer.tsx
packages/chrome/src/elements/sheet/components/Header.tsx
packages/chrome/src/styled/StyledSkipNav.ts
packages/chrome/src/styled/body/StyledContent.tsx
packages/chrome/src/styled/header/StyledBaseHeaderItem.ts
packages/chrome/src/styled/header/StyledHeader.ts
packages/chrome/src/styled/header/StyledHeaderItem.ts
packages/chrome/src/styled/header/StyledHeaderItemText.ts
packages/chrome/src/styled/header/StyledLogoHeaderItem.ts
packages/chrome/src/styled/nav/StyledLogoNavItem.ts
packages/chrome/src/styled/nav/StyledNav.ts
packages/chrome/src/styled/nav/StyledNavButton.ts
packages/chrome/src/styled/nav/StyledNavItemText.ts
packages/chrome/src/styled/sheet/StyledSheet.spec.tsx
packages/chrome/src/styled/sheet/StyledSheet.ts
packages/chrome/src/styled/sheet/StyledSheetFooter.spec.tsx
packages/chrome/src/styled/sheet/StyledSheetFooter.ts
packages/chrome/src/styled/sheet/StyledSheetHeader.spec.tsx
packages/chrome/src/styled/sheet/StyledSheetHeader.ts
packages/chrome/src/styled/sheet/StyledSheetWrapper.spec.tsx
packages/chrome/src/styled/sheet/StyledSheetWrapper.ts

This PR updates various components in `Chrome` to use [transient props](https://styled-components.com/docs/api#transient-props) where appropriate. These changes are necessary in  preparation for the upgrade to `styled-components@6.x.x` to ensure we avoid DOM violation errors after the transition.

refactor(chrome): use transient props where appropriate

---

packages/buttons/src/elements/Anchor.tsx
packages/buttons/src/elements/Button.tsx
packages/buttons/src/elements/ChevronButton.tsx
packages/buttons/src/elements/IconButton.tsx
packages/buttons/src/styled/StyledAnchor.spec.tsx
packages/buttons/src/styled/StyledAnchor.ts
packages/buttons/src/styled/StyledButton.spec.tsx
packages/buttons/src/styled/StyledButton.ts
packages/buttons/src/styled/StyledIconButton.spec.tsx
packages/buttons/src/styled/StyledIconButton.ts

This PR updates various components in `react-buttons` to use [transient props](https://styled-components.com/docs/api#transient-props) where appropriate. These changes are necessary in  preparation for the upgrade to `styled-components@6.x.x` to ensure we avoid DOM violation errors after the transition.

refactor(buttons): use transient props where appropriate

---

packages/datepickers/demo/datePicker.stories.mdx
packages/datepickers/demo/~patterns/patterns.stories.mdx
packages/datepickers/demo/~patterns/stories/CalendarStory.tsx
packages/datepickers/src/elements/DatePicker/DatePicker.spec.tsx
packages/datepickers/src/elements/DatePicker/DatePicker.tsx
packages/datepickers/src/types/index.ts

Adds `appendToNode` to `DatePicker`. See accompanying storybook [patterns] demo for details.

feat(datepickers): provide `appendToNode` prop for handling `DatePicker` calendar rendering

---

packages/dropdowns.legacy/src/elements/Menu/Items/AddItem.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/HeaderItem.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/Item.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/ItemMeta.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/MediaBody.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/MediaFigure.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/NextItem.tsx
packages/dropdowns.legacy/src/elements/Menu/Items/PreviousItem.tsx
packages/dropdowns.legacy/src/elements/Menu/Menu.tsx
packages/dropdowns.legacy/src/elements/Multiselect/Multiselect.tsx
packages/dropdowns.legacy/src/styled/items/StyledItem.spec.tsx
packages/dropdowns.legacy/src/styled/items/StyledItem.ts
packages/dropdowns.legacy/src/styled/items/StyledItemIcon.ts
packages/dropdowns.legacy/src/styled/items/StyledItemMeta.ts
packages/dropdowns.legacy/src/styled/items/StyledNextIcon.tsx
packages/dropdowns.legacy/src/styled/items/StyledPreviousIcon.tsx
packages/dropdowns.legacy/src/styled/items/header/StyledHeaderItem.ts
packages/dropdowns.legacy/src/styled/items/media/StyledMediaBody.ts
packages/dropdowns.legacy/src/styled/items/media/StyledMediaFigure.ts
packages/dropdowns.legacy/src/styled/menu/StyledMenu.ts
packages/dropdowns.legacy/src/styled/menu/StyledMenuWrapper.ts
packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectItemsContainer.ts
packages/dropdowns.legacy/src/styled/multiselect/StyledMultiselectMoreAnchor.ts
packages/forms/src/elements/MediaInput.tsx
packages/forms/src/elements/faux-input/FauxInput.tsx
packages/forms/src/types/index.ts

This PR updates various components in `react-dropdowns.legacy` to use [transient props](https://styled-components.com/docs/api#transient-props) where appropriate. These changes are necessary in  preparation for the upgrade to `styled-components@6.x.x` to ensure we avoid DOM violation errors after the transition.

refactor(dropdowns.legacy): use transient props where appropriate

---

packages/theming/demo/~patterns/patterns.stories.mdx
packages/theming/demo/~patterns/stories/GetColorStory.tsx
packages/theming/demo/~patterns/stories/GetColorV8Story.tsx
packages/theming/src/utils/getColor.ts
packages/theming/src/utils/getColorV8.ts

As advertised by the supporting stories, this PR swaps `getColor` and `getColorV8` `JSON.stringify` argument memoization with a custom key generation backed by `WeakMap` cached object comparisons. The before/after results are shown below...
**Before (`JSON.stringify`)**
| Uncached | Cached |
| --- | --- |
| <img width="567" alt="json-nocache" src="https://github.com/user-attachments/assets/914b257e-9fde-4d98-a037-81586b7c9ec2"> | <img width="564" alt="json-cache" src="https://github.com/user-attachments/assets/883dbdf3-fef5-4a47-b4ce-4381b01fbbd4"> |
**After (custom `toKey`)**
| Uncached | Cached |
| --- | --- |
| <img width="534" alt="tokey-nocache" src="https://github.com/user-attachments/assets/c38329df-d10b-4f42-9be9-80ca233562be"> | <img width="531" alt="tokey-cache" …

fix(theming): `getColor` memoization peformance

---

packages/dropdowns/src/elements/combobox/Combobox.tsx
packages/dropdowns/src/elements/combobox/Listbox.tsx
packages/dropdowns/src/elements/combobox/OptGroup.tsx
packages/dropdowns/src/elements/combobox/Option.tsx
packages/dropdowns/src/elements/combobox/OptionMeta.tsx
packages/dropdowns/src/elements/menu/Item.tsx
packages/dropdowns/src/elements/menu/ItemGroup.tsx
packages/dropdowns/src/elements/menu/ItemMeta.tsx
packages/dropdowns/src/elements/menu/MenuList.tsx
packages/dropdowns/src/views/combobox/StyledCombobox.ts
packages/dropdowns/src/views/combobox/StyledFloatingListbox.ts
packages/dropdowns/src/views/combobox/StyledInput.ts
packages/dropdowns/src/views/combobox/StyledListbox.ts
packages/dropdowns/src/views/combobox/StyledOptGroup.ts
packages/dropdowns/src/views/combobox/StyledOption.ts
packages/dropdowns/src/views/combobox/StyledOptionMeta.ts
packages/dropdowns/src/views/combobox/StyledTagsButton.ts
packages/dropdowns/src/views/combobox/StyledTrigger.ts
packages/dropdowns/src/views/combobox/StyledValue.ts
packages/dropdowns/src/views/menu/StyledMenu.ts

This PR updates various components in `react-dropdowns` to use [transient props](https://styled-components.com/docs/api#transient-props) where appropriate. These changes are necessary in  preparation for the upgrade to `styled-components@6.x.x` to ensure we avoid DOM violation errors after the transition.

refactor(dropdowns): use transient props where appropriate

---

package-lock.json
packages/.template/package.json
packages/accordions/package.json
packages/avatars/package.json
packages/breadcrumbs/package.json
packages/buttons/package.json
packages/chrome/package.json
packages/colorpickers/package.json
packages/datepickers/package.json
packages/draggable/package.json
packages/dropdowns.legacy/package.json
packages/dropdowns/package.json
packages/forms/package.json
packages/grid/package.json
packages/loaders/package.json
packages/modals/package.json
packages/notifications/package.json
packages/pagination/package.json
packages/tables/package.json
packages/tabs/package.json
packages/tags/package.json
packages/tooltips/package.json
packages/typography/package.json

Fixes packages' `peerDependencies` referencing `react-theming@9.0.0-next`.

deps: point to correct `react-theming` peerDependency

---

docs/migration.md
packages/theming/src/utils/getColor.spec.ts
packages/theming/src/utils/getColor.ts
packages/theming/src/utils/getColorV8.spec.ts
packages/theming/src/utils/getColorV8.ts

Improve memoization key generation for `getColor` and `getColorV8` usage that doesn't provide the expected `theme` argument type. See updated tests for the issues solved by this PR.
Also slips in missing Migration Guide documentation.

fix(theming): harden `getColor` memoization key generation

---

packages/grid/src/elements/pane/components/SplitterButton.tsx

This PR addresses an issue where default tooltip positioning can result in cutting off the tooltip when a pane is expanded/contracted to the edge of the visible screen/container.

fix(grid): use `auto` tooltip positioning for `Pane.SplitterButton`

---

packages/theming/src/utils/getColor.ts

Revert in order to broaden legacy browser support.

fix(theming): swap `hasOwn` for `hasOwnProperty` call in `getColor`

---

package-lock.json
packages/chrome/package.json
packages/chrome/src/elements/sheet/Sheet.tsx
packages/chrome/src/types/index.ts

While working on a project with Garden dependencies, I realized that `react-chrome` fails to install in certain environments due to a missing `react-uid` dependency. This is often masked, since `react-notifications` pulls it in. Since Garden no longer recommends `react-uid` in favor of the more stable `useId` from `@zendeskgarden/container-utilities`, I updated the missing dependency and code accordingly (eventually, we'll also replace `uid` in notifications `useToast`).

fix(chrome): provide missing `useId` container dependency for `Sheet` component

---

packages/accordions/src/elements/stepper/components/Content.spec.tsx
packages/accordions/src/elements/stepper/components/Content.tsx
packages/accordions/src/styled/stepper/StyledInnerContent.ts

Similar to `Accordion` panel and `Sheet` content, this PR applies the HTML `inert` attribute in order to prevent tab navigation through focusable elements that are rendered within hidden `Stepper` content sections.
Compare with https://github.com/zendeskgarden/react-components/pull/1920

fix(accordions): set `inert` for hidden `Stepper` content

---

packages/dropdowns/demo/stories/ComboboxStory.tsx

The addition of a child element to the story's custom tags ensures truncation behaves like it would in the default case.
**Before**
**After**

chore(dropdowns): fix multiselectable combobox tags

---

packages/dropdowns/src/elements/combobox/Combobox.spec.tsx
packages/dropdowns/src/elements/combobox/Listbox.tsx

This update fixes how our Comboboxes interact with NVDA during animations. Previously, NVDA users might have experienced incomplete or inaccurate announcements of the selected option when the dropdown list was animating. This was due to the way NVDA processes rapid changes in the page, which sometimes led to announcements being out of sync with the visual state.
When interacting with the Select-Only Combobox, NVDA's announcement of the selected option (e.g., "Label combo box Poppy collapsed opens list") is often interrupted by an incorrect announcement of a now-inactive option previously referenced by `aria-activedescendant` (e.g., "Poppy Lee 4 of 16").
Analysis revealed that the dropdown animation is interfering with NVDA’s event queue, causing it to announce outdated or incorrect …

fix(Combobox): improve screen reader experience for Select-Only combobox w NVDA

---

lerna.json

Explicitly sets the `dist-tag` to `v8` instead of the [default](https://www.npmjs.com/package/@lerna/publish#--dist-tag-tag) `latest`

chore: set `dist-tag` to `v8`

---

packages/theming/demo/stories/GetColorStory.tsx
packages/theming/src/utils/getColor.ts

While this PR focuses on a very minor `getColor` fix, the main enhancement is the updated Storybook that shows the potential generated palette `hue` for any non-themed color value resolved by `getColor`.

fix(theming): return hex from generated `getColor` values

---

packages/theming/src/elements/ColorSchemeProvider.tsx
utils/test/jest.setup.js

I ran into a gnarly error while attempting to retrofit `ColorSchemeProvider` on to the Garden website along with a new component page and embedded example. Due to React's [useEffect cleanup logic](https://react.dev/reference/react/useEffect#my-cleanup-logic-runs-even-though-my-component-didnt-unmount) the placement of the provider's `mediaQuery` listener was being unexpectedly removed from the embedded example. As a result, changing the system color scheme updated the website as expected, but was not cascading to the embedded example.
The solution was to move the `useEffect` out of the hook and into the `ColorSchemeProvider` itself. Doing so ensures mounting/unmounting (and associated listener add/removal) works as expected.

fix(theming): nested `ColorSchemeProvider` system color scheme handling

---

.storybook/preview.js
packages/chrome/src/elements/header/HeaderItemWrapper.tsx
packages/chrome/src/styled/header/StyledHeaderItemWrapper.ts
packages/loaders/demo/dots.stories.mdx
packages/loaders/src/elements/Dots.tsx
packages/loaders/src/elements/Spinner.tsx
packages/loaders/src/styled/StyledLoadingPlaceholder.ts
packages/loaders/src/styled/StyledSVG.ts

During the `styled-components` transient naming work, a few props got missed. This PR ensures the following are properly ferried to the underlying view components:
- `<Header.ItemWrapper isRound={...} maxX={...} maxY={...}>`
- `<Dots size={...}>`
- `<Spinner size={...}>`
Also cleans up Storybook `VARIABLES` context args that were leaking into rendered styled components.

fix(chrome,loaders): ferry props to view component transient props

---

packages/forms/src/styled/text/StyledTextInput.tsx

Replace the `react-dom/server` `renderToString` import with a static SVG icon string. The import causes issues in some environments and adds unwanted bloat.
https://react.dev/reference/react-dom/server/renderToString#removing-rendertostring-from-the-client-code

fix(forms): remove `renderToString` for the calendar picker icon

---

package-lock.json
packages/dropdowns/package.json

This PR applies the `@zendeskgarden/container-menu` [fix](https://github.com/zendeskgarden/react-containers/pull/691) to Menu to ensure iframed Menu dropdowns close correctly when clicking outside the iframe (even in another window).
- ~~[ ] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
- ~~[ ] :arrow_left: renders as expected with reversed (RTL) direction~~
- ~~[ ] :black_circle: renders as expected in dark mode~~
- ~~[ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)~~

fix(dropdowns): ensure iframed Menu dropdowns close correctly when clicking outside the iframe

---

packages/theming/src/types/index.ts

This PR updates the outdated `IGardenTheme` type to reflect the new value for the `lg` `borderRadius` token. 
- ~~[ ] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
- ~~[ ] :globe_with_meridians: demo is up-to-date (`npm start`)~~
- ~~[ ] :arrow_left: renders as expected with reversed (RTL) direction~~
- ~~[ ] :black_circle: renders as expected in dark mode~~
- ~~[ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)~~
- ~~[ ] :guardsman: includes new unit tests. Maintain existing coverage (always >= 96%)~~
- ~~[ ] :wheelchair: tested for WCAG 2.1 AA accessibility compliance~~
- ~~[ ] :memo: tested in Chrome, Firefox, Safari, and Edge~~

fix(theming): reflect updated `lg` borderRadius in `IGardenTheme` definition

---

packages/modals/demo/stories/TooltipDialogStory.tsx
packages/modals/demo/tooltipDialog.stories.mdx
packages/modals/src/elements/TooltipDialog/TooltipDialog.tsx
packages/modals/src/types/index.ts
packages/tooltips/demo/stories/TooltipStory.tsx
packages/tooltips/demo/tooltip.stories.mdx
packages/tooltips/src/elements/Tooltip.tsx
packages/tooltips/src/types/index.ts

This PR adds `fallbackPlacements` support to both `Tooltip` and `TooltipModal`, aligning their behavior with `MenuList`.
- Adds support for the `fallbackPlacements` prop in `Tooltip` and `TooltipModal`.
- Allows users to specify alternative positions for the overlay when the default `placement` is not viable due to space constraints.
- Updates relevant Storybook stories.
https://github.com/user-attachments/assets/b45bf599-e6c4-4b85-9832-37ea39444bd2
- ~~[ ] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
- ~~[ ] :black_circle: renders as expected in dark mode~~
- ~~[ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)~~
- ~~[ ] :guardsman: includes new unit tests. Maintain existing coverage (always >= 96%)~~

feat(modals, tooltips): adds `fallbackPlacements` support to `Tooltip` and `TooltipModal`

---

package-lock.json
packages/avatars/package.json
packages/avatars/src/elements/Avatar.spec.tsx
packages/avatars/src/elements/Avatar.tsx
packages/avatars/src/styled/StyledAvatar.ts

This PR addresses two problems with the `Avatar` component:
- missing `box-shadow` status ring (due to stricter `&` reference with styled-components v7)
- problematic `statusLabel` accessibility structure detailed in the image below

fix(avatars): status ring styling and accessibility

---

package-lock.json
packages/tooltips/demo/~patterns/patterns.stories.mdx
packages/tooltips/demo/~patterns/stories/MenuStory.tsx
packages/tooltips/package.json
packages/tooltips/src/elements/Tooltip.tsx
packages/tooltips/src/styled/StyledTooltip.ts

Upgrades to `@zendeskgarden/container-tooltip` v2.0.0 and adds a menu pattern story to demonstrate that tooltips are dismissed when an associated trigger popup is opened.
Important note: we need to revisit the `container-tooltip` at some point to add a document listener (similar to the work done with `container-menu` that catches all un-focus events. Currently, the auto refocus to the trigger on menu close re-opens the tooltip. This is currently expected, but not the ultimate desired outcome. That bug will be dealt with under separate PRs.

fix(tooltips): prevent `Tooltip` from interfering with a popup (menu, dialog, etc.) trigger

---

packages/notifications/src/styled/global-alert/StyledGlobalAlert.spec.tsx
packages/notifications/src/styled/global-alert/StyledGlobalAlert.ts

The original `GlobalAlert` was designed to support stacking by defining a bottom border. The implementation used `box-shadow` to avoid affecting size. However, without `inset` the "border" was cut off. This PR fixes `GlobalAlert` to honor the original design intent.

fix(notifications): update `GlobalAlert` box-shadow to inset

---

packages/theming/demo/stories/ColorSchemeProviderStory.tsx
packages/theming/src/elements/ColorSchemeProvider.tsx
packages/theming/src/types/index.ts
packages/theming/src/utils/useColorScheme.spec.tsx

While bypassing `localStorage` would typically be discouraged, there are cases (iframe'd content for example) where `ColorSchemeProvider` usage might not want to compete with a higher-level provider's local storage. This PR introduces `<ColorSchemeProvider colorSchemeKey={null}>` for these cases.

feat(theming): allow `null` color scheme key to bypass `ColorSchemeProvider` local storage

---

package-lock.json
packages/avatars/demo/~patterns/stories/StatusMenuStory.tsx
packages/avatars/src/elements/StatusIndicator.spec.tsx
packages/avatars/src/elements/StatusIndicator.tsx
packages/avatars/src/styled/StyledStatusIndicator.ts
packages/avatars/src/styled/StyledStatusIndicatorBase.ts
packages/avatars/src/types/index.ts

Used to prevent a duplicate screenreader output of "status: online, image Online" when the `<StatusIndicator>` is used within an interactive context – such as a status menu.
Emerging designs are calling for the `extrasmall` avatar to render its status SVG. The updates look like this...

feat(avatars): allow `null` aria-label on `StatusIndicator` to mark as decorative

---

package-lock.json
packages/dropdowns/package.json

Description
This PR is a follow-up to https://github.com/zendeskgarden/react-containers/pull/699 and resolves an issue where clicking outside a menu dropdown does not close it when a nested item is auto-focused.
https://github.com/user-attachments/assets/ae46dcb4-9132-45b7-92b1-ad2a9d7a46e1
https://github.com/user-attachments/assets/209e9f36-1320-4934-98cf-1ac147e44c75
- ~~[ ] :ok_hand: design updates will be Garden Designer approved (add the designer as a reviewer)~~
- ~~[ ] :black_circle: renders as expected in dark mode~~
- ~~[ ] :metal: renders as expected with Bedrock CSS (`?bedrock`)~~
- ~~[ ] :guardsman: includes new unit tests. Maintain existing coverage (always >= 96%)~~

fix(dropdowns): ensure Menu closes on outside click when nested item is auto-focused

---

package-lock.json
packages/tooltips/package.json

This PR builds on the work from [#700](https://github.com/zendeskgarden/react-containers/pull/700). It updates the `Tooltip` component so that tooltips no longer appear immediately on focus after closing expanded popups, like menu dropdowns. This makes the UX smoother and less distracting.
https://github.com/user-attachments/assets/cb8ed237-71a1-442d-b677-235a2860c3f2
Tooltip no longer shows when focus is returned to the `Menu` trigger.
https://github.com/user-attachments/assets/aebcd35d-647a-4275-94b2-4f522ca48fc2

feat(react-tooltips): suppress tooltips that normally trigger on focus immediately after closing expanded popups

---

packages/typography/demo/kbd.stories.mdx
packages/typography/demo/stories/KbdStory.tsx
packages/typography/src/elements/Kbd.spec.tsx
packages/typography/src/elements/Kbd.tsx
packages/typography/src/index.ts
packages/typography/src/styled/StyledKbd.ts
packages/typography/src/styled/index.ts
packages/typography/src/types/index.ts

Adds `Kbd` to typography as a customization over the HTML [&lt;kbd&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/kbd) element.

feat(typography): add new `Kbd` component

---

packages/typography/demo/kbd.stories.mdx
packages/typography/src/styled/StyledKbd.ts

Switch to the well-supported browser `font-family: sans-serif` vs. Garden's monospace font stack. The monospace stack is good for rendering `Code` & `Codeblock`. But substandard when it comes to rendering individual special characters.
**Before**
**After**

fix(typography): improve `Kbd` font
